"""
HISTORYSNOOZE: ACT I SCRIPT BUILDER (PARTS 01 - 05)
Module: build_act1_full.py
Strictly calibrated to 1,070 - 1,130 words per part.
SSOT-compliant with 01_STYLE_BIBLE_&_GOLDEN_EXAMPLES.md.
"""

from build_full_script_generator import write_file

P01 = [
    "Hey guys, tonight we are going to drift back in time to the warm, star-dusted desert nights of ancient Roman Syria, where the scent of cedarwood, crushed frankincense, and desert jasmine lingers over the basalt terraces of Emesa... And let us be honest, given the cutthroat dynastic betrayals, ruthless civil wars, and poisonous palace intrigues of the Roman imperial world, you probably would not survive this with your peaceful assumptions intact. But that is the fun of it. So, before you get comfortable, take a moment to like the video and subscribe, but only if you genuinely enjoy what I do here. And for a bit of fun, post your location and local time in the comments below. It is always a quiet thrill to see where everyone is drifting off from. Now, dim the lights, maybe turn on a fan for that soft background hum, and let us ease into tonight's journey together.",
    "You stand on the high stone parapet of the royal palace of Emesa under a vast indigo sky studded with crystalline Syrian stars. The air is cool after the relentless heat of the desert sun, carrying the dry, resinous perfume of frankincense burning in bronze braziers across the lower city. Far below your feet, the dark waters of the Orontes River flow silently through olive groves and date palms, catching the silver shimmer of the rising crescent moon. It is the second century of the common era, in the year one hundred sixty, and you are breathing the sacred air of a city that blends the immense wealth of ancient desert trade routes with the monumental prestige of Rome, creating an atmosphere of timeless, nocturnal grandeur that gently calms the weary mind.",
    "Beside you, the young princess Julia Domna watches the silent constellations wheel above the desert horizon with quiet, contemplative grace. She is wrapped in a flowing palla of deep Tyrian purple silk, bordered with delicate gold embroidery that glints softly in the flickering lamplight. Her dark eyes reflect an intellect nurtured by the finest libraries of the Hellenistic East, studying mathematics, astronomy, rhetoric, and classical literature under the guidance of renowned scholars. Growing up in a royal household of hereditary priest-kings is remarkably similar to managing an inescapable royal family enterprise where every private conversation is subject to centuries of dynastic expectation, high-stakes diplomacy, and relentless strategic calculus.",
    "Her father, Julius Bassianus, is the supreme high priest of the temple of Elagabal, the supreme sun deity revered across the Syrian lands in the sacred form of a massive black conical meteorite. As high priest of this ancient cult, Julius Bassianus commands not only immense spiritual devotion but also vast agricultural estates, trade monopolies, and influential connections reaching directly to the Roman Senate. You can hear the distant chanting of temple priests drifting through the cool night air, rhythmic and hypnotic, accompanied by the gentle cadence of double pipes and bronze finger cymbals echoing across stone courtyards, filling the desert night with reverent music that resonates deeply in your chest.",
    "In the quiet courtyards of the palace, scholars and astrologers gather nightly to chart the intricate movements of wandering planets against the velvet dome of the Syrian sky. In antiquity, consulting astrologers regarding the natal charts of highborn children was very much like obsessively checking your personal notifications and algorithmic forecasts before making any major life decision. The court astrologers cast the horoscope of the young Julia Domna, studying the alignments of Jupiter and Venus with mathematical precision, and they whisper a startling prophecy across the shadowed porticos: the young noblewoman possesses a royal horoscope, indicating that whoever marries her will one day sit upon the throne of an emperor.",
    "Historians still argue whether this famous royal horoscope was an authentic astrological reading recorded during her youth in Emesa, or a brilliant piece of post-accession Severan imperial propaganda crafted to justify her family's divine right to rule. Yet in the ancient Mediterranean world, where signs, omens, and celestial alignments dictated the decisions of generals and senators alike, such a reputation spread quietly along the merchant caravans and military highways of the empire, reaching ambitious men across the provinces who dreamed of supreme dominion and sovereign glory under the banner of the Roman legions.",
    "You feel the gentle desert breeze ruffle the silk draperies of the palace colonnade, bringing the faint aroma of roasting pistachios, dried figs, and sweet dates from the sleeping merchant quarters. The silence of the desert night settles deep into your bones, broken only by the rhythmic footsteps of guards patrolling the outer city gates with bronze-tipped spears. Emesa is a crossroads of the world, where camel trains arriving from the Silk Roads of Parthia exchange silks, spices, and precious gems for Roman glassware and Spanish olive oil, creating a cosmopolitan atmosphere of boundless wealth and cultural sophistication.",
    "Julia Domna was raised to command this complex tapestry of cultures, speaking fluent Greek, classical Latin, and her native Aramaic dialect with effortless grace and eloquence. She watched her father navigate delicate negotiations between local Arab tribal leaders and haughty Roman governors, learning that true authority is rarely exercised through overt force alone, but rather through quiet intelligence, persuasive charm, and supreme self-control. Navigating ancient imperial governance was not unlike trying to coordinate conflicting regional schedules across multiple time zones without the benefit of digital calendars or instant messaging, requiring exceptional patience and political foresight.",
    "As the hours of the second watch glide by, oil lamps flicker low in their terracotta saucers, casting long, dancing shadows across the polished limestone mosaics of the courtyard. You can sense the quiet determination gathering in the young princess, a conscious awareness that her destiny lies far beyond the palm groves of Syria and the sacred sanctuary of the Black Stone. The world beyond Emesa is vast, turbulent, and hungry for leadership, and she prepares herself to step onto the grandest stage the ancient world could offer, mastering statecraft with calm resolve.",
    "You take a slow, deep breath of the fragrant desert night air, feeling the peaceful stillness of ancient Syria surround you like a warm mantle. The stars overhead shine with steady, ancient brilliance, untroubled by the rise and fall of mortal empires, while the silent river continues its timeless journey toward the Mediterranean sea. The foundation of an empire is quietly being laid in this tranquil eastern sanctuary, where an ambitious young woman watches the night sky and awaits the turning of the wheel of fortune with serene and unshakable confidence, resting peacefully under the starry heavens."
]

P02 = [
    "You travel westward across the sun-drenched waters of the Mediterranean to the Roman province of Gallia Lugdunensis in the year one hundred eighty-seven of the common era. Twilight descends over the rugged provincial capital of Lugdunum, where the cold, grey waters of the Rhone and Saone rivers converge beneath massive stone bridges and red-tiled Roman rooftops. The crisp northern air smells of river silt, pine smoke from garrison hearths, damp slate, and roasting barley, a stark contrast to the balmy, spice-laden desert winds of Syrian Emesa, wrapping the provincial landscape in an atmosphere of quiet, brooding power and ancient frontier discipline that invites deep, restful contemplation after a long journey across the empire.",
    "Inside the governor's residence, an ambitious Roman senator named Lucius Septimius Severus sits at a heavy oak table covered with parchment scrolls, census ledgers, and military dispatches from the Rhine frontier. Born in the Phoenician-Punic port city of Leptis Magna on the coast of North Africa, Severus is a hardened military commander with sharp, piercing eyes, a trimmed curly beard, and an unyielding will to power. Reviewing endless provincial tax requisitions and garrison grain quotas by the dim glow of an oil lamp is the ancient equivalent of spending your entire evening plowing through an overflowing inbox of urgent administrative emails that never seem to stop arriving no matter how fast you work.",
    "Severus, having recently lost his first wife Paccia Marciana, is actively seeking a new marriage alliance that can elevate his political standing and fulfill his deep-seated astrological ambitions. Being deeply superstitious and fascinated by Eastern divination, Severus had diligently researched the horoscopes of eligible noblewomen across the Roman Mediterranean world with the thoroughness of a modern forensic accountant. When reports reached him of the Syrian priest-king's daughter in Emesa who possessed an unmistakable royal horoscope promising a crown to her future husband, Severus dispatched formal envoys across the sea to propose marriage without a moment of hesitation, knowing that destiny favored the bold and the prepared.",
    "Some historians question whether Severus was genuinely motivated by romantic attraction and intellectual compatibility, or if his decision was purely a cold, calculated political maneuver to secure the immense wealth and religious prestige of the Emesene priestly dynasty. In reality, the union between the North African general and the Syrian princess proved to be one of the most formidable intellectual, financial, and political partnerships in the entire history of classical antiquity, merging Western military grit with Eastern cultural refinement, philosophical wisdom, and sovereign diplomatic authority that commanded absolute respect across all ranks and provinces.",
    "Julia Domna, now in her early twenties, arrived in the Western provinces with an entourage of scholars, secretaries, and substantial financial backing from the temple treasury of Elagabal. Their wedding in one hundred eighty-seven was celebrated with traditional Roman solemnity combined with Eastern opulence, uniting two influential provincial families outside the traditional Italian aristocratic elite. Observing Roman aristocrats trying to maintain aristocratic snobbery while secretly marveling at Syrian gold is rather like watching old money traditionalists reluctantly adjusting to new tech entrepreneurs at an elite gala, trying to conceal their envy behind polite, diplomatic smiles.",
    "Within a year of their marriage, while residing in Lugdunum, Julia Domna gave birth to their first son, Lucius Septimius Bassianus, who would later be known to history and his soldiers by the nickname Caracalla. The child was named in honor of Domna's father, Julius Bassianus, cementing the profound bond between the imperial family and the sacred sun-cult of Syria. The infant's nursery was guarded day and night by loyal African and Syrian guards, their iron swords gleaming softly in the torchlight as rain pattered steadily against the tiled roof, keeping peaceful watch over the imperial heir in the quiet, comforting darkness.",
    "In the following year, one hundred eighty-nine, while Severus served as governor in the Mediterranean province of Sicily, Domna gave birth to their second son, Publius Septimius Geta. The imperial household was now blessed with two male heirs, seemingly guaranteeing dynastic continuity and stability in a Roman world increasingly shaken by political instability and imperial extravagance in Rome under Emperor Commodus. Yet beneath the joyful family celebrations, subtle rivalries between the two young brothers began to manifest almost from their earliest infancy, foreshadowing future tragedies that no parent could easily bear, despite all their wealth, prestige, and power.",
    "You walk beside Domna through the colonnaded peristyle garden of their Sicilian villa as the twilight fades into a serene, indigo night. The air is scented with blooming orange blossoms, wild rosemary, and the salty breeze blowing off the Ionian Sea, creating an oasis of quiet domesticity amidst brewing political storms. Domna personally supervised the education of her two sons, ensuring they were instructed in Greek philosophy, Latin rhetoric, military strategy, and Syrian religious customs by the finest tutors of the Mediterranean world, instilling in them the knowledge and mental discipline required to govern an empire with wisdom and strength.",
    "Meanwhile, back in Rome, the erratic behavior of Emperor Commodus was pushing the empire toward a catastrophic political crisis that would soon engulf the entire Mediterranean basin. Severus received encrypted dispatches from trusted senatorial allies in the capital, detailing growing conspiracies, senate purges, and the restless mood of the Praetorian Guard. Preparing for a potential civil collapse while maintaining an outward appearance of dutiful provincial loyalty required a level of diplomatic multitasking that would test the nerves of any modern executive managing a corporate crisis under the watchful gaze of hostile competitors.",
    "As the lamps in the villa are extinguished one by one, leaving only the soft moonlight filtering through the marble columns, you feel the calm before the coming tempest. Domna stands by the window, listening to the gentle rhythm of the waves breaking against the rocky Sicilian shore, knowing that the prophecies of her youth are drawing inexorably closer. In the quiet darkness of the Mediterranean night, the family rests, gathered together before the storm of imperial power breaks across the Roman world in thunderous fury and sovereign glory, peaceful and undisturbed under the stars."
]

P03 = [
    "You step into the frosty spring twilight of Carnuntum on the frozen banks of the Danube River in April of the year one hundred ninety-three. A bitter wind sweeps down from the dense Germanic forests, whistling through the timber palisades and stone ramparts of the legionary fortress. The smell of burning pine logs, wet wool, and horse sweat hangs heavy in the encampment as thousands of hardened Danubian legionaries gather around smoking campfires, their bronze-crested iron helmets glinting in the dying sunlight, ready to follow their commander to the ends of the known earth without a second thought.",
    "Shocking news has just arrived from Rome via exhausted imperial couriers who rode their horses to death across the alpine passes: Emperor Commodus was strangled in his bath on New Year's Eve, his successor Pertinax was butchered after only eighty-seven days by mutinous Praetorian Guards, and the imperial throne was literally auctioned off to the highest bidder, a wealthy senator named Didius Julianus. The Roman Empire being sold to the highest bidder at a Praetorian barracks auction was very much like an unregulated, high-stakes online bidding war where the buyers completely forgot to read the catastrophic terms and conditions before placing their bids.",
    "In the commander's tent, illuminated by the warm, amber glow of brass oil lamps, Julia Domna stands beside Septimius Severus as he studies a detailed map of the empire's road network. With three powerful legions at his command in Upper Pannonia and the backing of all the Danubian garrisons, Severus knows that hesitation means certain death. Domna reviews intelligence dispatches with calm, razor-sharp focus, assessing the loyalties of neighboring provincial governors and calculating the grain reserves necessary to sustain a lightning march on Italy without exhausting their supplies or burdening local communities along the route.",
    "Academic circles remain divided about how much direct influence Julia Domna exerted in convincing Severus to take the perilous gamble of marching against Rome, or if she primarily functioned as an astute diplomatic advisor behind closed tent flaps. What is certain is that her poise, substantial family wealth, and profound understanding of Eastern and Western political psychology gave Severus the confidence to seize the moment, transforming a provincial governor into a claimant for supreme imperial power with the full backing of the frontier armies who hungered for decisive leadership.",
    "On the ninth of April, one hundred ninety-three, the Danubian legions assemble on the frozen parade grounds of Carnuntum and proclaim Septimius Severus emperor with thunderous roars that echo across the river into barbarian lands. Domna watches from the reviewing platform, wrapped in a heavy woolen mantle over her Syrian silk tunic, as the legionaries clash their short swords against iron-rimmed shields in rhythmic, earth-shaking approval. The energy of the assembled army is electric, an unstoppable wave of martial power ready to crest over the Alps and claim the eternal city from a corrupted usurper.",
    "Managing the logistics of moving tens of thousands of Roman legionaries across alpine passes at breakneck speed required organizational precision that modern logistics managers with sophisticated tracking software would deeply envy. Severus and Domna demanded that the army march without heavy baggage trains, covering up to twenty miles a day through mountain passes still choked with winter snow. Domna rode near the vanguard with her two young sons, enduring the same bitter winds, coarse rations, and rough roads as the common soldiers, winning their unconditional loyalty and personal affection.",
    "Rumors and frantic reports traveled down the Italian peninsula like viral headlines across social media networks, causing panic in the Roman Senate and paralyzing Didius Julianus in the imperial palace. The Italian towns along the Via Flaminia surrendered one after another without striking a single blow, throwing open their gates and welcoming Severus with flower garlands, torchlit processions, and abundant supplies. The Praetorian Guard in Rome, accustomed to palace luxury and extortion rather than real combat against hardened frontier legions, completely collapsed in morale and discipline.",
    "By late May, the Senate in Rome formally declared Didius Julianus a public enemy, sentenced him to death, and recognized Septimius Severus as the sole legitimate emperor of Rome. Julianus was executed in the palace baths, abandoned by everyone he had bought with his promises of gold, demonstrating the timeless principle that loyalty purchased with emergency cash vanishes the moment a real crisis arrives. Domna received the news while camped in the rolling hills of Umbria, realizing that the first great threshold of imperial destiny had been crossed with triumphant success.",
    "You walk through the quiet legionary camp outside Rome as midnight settles over the fertile Italian plains, listening to the soft murmur of soldiers polishing their armor for the triumphal entry. The night air is fragrant with blooming jasmine and the cool earth of ancient vineyards, peaceful and serene after weeks of relentless marching across mountains and rivers. Beside the commander's tent, the imperial standards stand planted in the soft soil, their silver eagles catching the pale light of the stars above, motionless in the tranquil evening breeze.",
    "Domna sits quietly inside the tent, composing letters to her family in Emesa and allies across the Eastern provinces, knowing that the capture of Rome is merely the opening move in a grander struggle. Two formidable rivals, Pescennius Niger in the wealthy East and Clodius Albinus in the rugged West, have also claimed the purple and command vast armies. As you listen to the rhythmic breathing of her sleeping children, you sense the immense burden of power that now rests upon her shoulders under the silent, watchful sky, yet she remains calm, steadfast, and resolute."
]

P04 = [
    "You enter the Eternal City in June of the year one hundred ninety-three, walking through the monumental marble arches of Rome beneath a canopy of golden afternoon light. The streets are packed with cheering citizens, showered with sweet-smelling rose petals and laurel leaves, as Septimius Severus leads his victorious Danubian legions through the Forum Romanum to the temple of Jupiter Optimus Maximus on the Capitoline Hill. Julia Domna rides in a gilded carriage, her regal Syrian beauty, elaborate coiffure, and ornate jewelry captivating the awe-struck Roman crowds with unforgettable majesty and grace.",
    "Severus immediately disarmed and disbanded the disgraced Praetorian Guard, banishing them from within one hundred miles of Rome and replacing them with seasoned veterans from his own frontier legions. Reorganizing the imperial security apparatus and firing the entire palace guard in a single afternoon was the ancient Roman equivalent of an aggressive corporate takeover where the entire executive security team is escorted from the building without severance. Domna observed every decree, understanding that raw security and military discipline were the absolute foundation upon which all culture, jurisprudence, and dynastic stability must rest.",
    "Yet the empire remained fractured in a brutal three-way civil war that threatened to tear the Mediterranean world apart at its seams. In the wealthy Eastern provinces, the governor of Syria, Pescennius Niger, had been proclaimed emperor by the legions of Antioch and secured the backing of the Persian king of Parthia. Meanwhile, in the Western provinces, the aristocratic governor of Britannia, Clodius Albinus, held the support of the elite British and Spanish legions and posed an existential threat to Italy, demanding delicate political maneuvers and swift military action.",
    "Severus and Domna immediately embarked on a grueling Eastern campaign to crush Pescennius Niger before he could consolidate his hold on the Levant and Egypt. Domna returned to the familiar lands of her youth, utilizing her family's vast network of Syrian aristocratic connections and temple wealth to supply the imperial army with grain, pack animals, and siege equipment. The decisive clash took place in one hundred ninety-four at the historic battlefield of Issus, where Alexander the Great had once defeated the Persian Empire centuries earlier, resulting in total victory for Severus's veteran legions.",
    "Following the crushing defeat and death of Niger at Issus, Severus turned his legions westward to confront Clodius Albinus in Gaul. The climactic battle occurred outside the walls of Lugdunum in February of the year one hundred ninety-seven, involving nearly one hundred fifty thousand Roman soldiers on each side in one of the largest and bloodiest clashes in Roman history. The battle raged for two full days through freezing slush and sleet until Severus's cavalry delivered the crushing, decisive flank attack, breaking the enemy lines and ending the civil war.",
    "Biographers and historians continue to debate whether the ruthless purge of senatorial supporters of Albinus that followed was orchestrated entirely by Severus or actively encouraged by Domna to eliminate potential threats to her young sons. In the aftermath of victory, Severus executed dozens of prominent Roman senators, confiscated their vast Italian and provincial estates, and transferred their enormous wealth directly into the private treasury of the imperial family, securing the financial stability of the Severan dynasty for a generation to come.",
    "Returning to Rome in total triumph, Julia Domna was formally granted the supreme imperial title of Augusta by the Senate, elevating her to a status of unprecedented grandeur and public reverence. Trying to navigate the subtle social snobbery of the old Italian senatorial families while holding absolute autocratic power over their lives was like attending an exclusive aristocratic club where you quietly happen to own the entire real estate and the operating license. Domna handled the patricians with flawless aristocratic dignity, masking her true authority behind exquisite cultural patronage and gracious public munificence.",
    "Severus also orchestrated a masterclass in dynastic public relations by retroactively adopting himself and his family into the beloved Antonine dynasty, declaring himself the brother of Emperor Marcus Aurelius. To solidify this imperial lineage, their elder son Bassianus was renamed Marcus Aurelius Antoninus, the name by which he would officially reign, although the populace affectionately called him Caracalla after the hooded Celtic tunic he popularized. Domna's younger son Geta was granted the title of Caesar, confirming the dual succession in public monuments.",
    "As dusk falls over the Palatine Hill, you stand with Julia Domna on the vast marble terrace of the Flavian Palace, looking out across the illuminated monuments of the Forum Romanum. Oil lamps and torches flicker across the seven hills of Rome like a sea of golden embers beneath the twilight sky. The Tiber River glides like a dark ribbon through the marble city, carrying the echoes of triumph, victory hymns, and the distant laughter of citizens celebrating in wine shops and taverns throughout the vibrant metropolis.",
    "Domna draws her silk palla around her shoulders against the cool evening breeze, listening to the gentle hum of the great metropolis settling into sleep. The civil wars that had torn the empire asunder are finally over, and her family stands uncontested at the pinnacle of the ancient world. You feel the deep, resonant peace of a hard-won victory as the night deepens, wrapping the ancient capital in a mantle of serene, starry stillness that soothes the spirit and invites deep, restful slumber under the eternal sky."
]

P05 = [
    "You ride through the scorching Mesopotamian desert in the autumn of the year one hundred ninety-seven, where the vast expanse of yellow sand meets a pale turquoise sky at the edges of the known world. Long columns of Roman legionaries, their lorica segmentata iron plates clanking rhythmically in the heat, march beside the meandering waters of the Euphrates River toward the royal Parthian capital of Ctesiphon. In the center of the imperial baggage train, Julia Domna rides in a covered traveling carriage accompanied by her two young sons, enduring the choking dust, blazing sun, and rough desert tracks with unyielding royal fortitude.",
    "Unlike traditional Roman noblewomen who remained secluded in the opulent villas of Campania or the Palatine Hill while their husbands campaigned, Julia Domna made the bold and unprecedented decision to accompany Septimius Severus on nearly every major military expedition. Traveling thousands of miles across rugged frontiers with young children in tow while managing imperial diplomatic correspondence was the ancient equivalent of running a multinational enterprise from a laptop during high-stress international business travel without hotel accommodations or modern creature comforts.",
    "In recognition of her extraordinary courage, endurance, and visible presence at the front lines, the Roman Senate and the Danubian legions formally bestowed upon her the sacred military title of Mater Castrorum, or Mother of the Camps, in the year one hundred ninety-five. This rare and prestigious honor had been held before her only by Faustina the Younger, the wife of Marcus Aurelius. To the battle-hardened legionaries, Domna was not merely an aristocratic empress; she was the living maternal protector of the Roman army who cared for their welfare.",
    "A point of contention among scholars is whether the soldiers truly viewed Julia Domna as a protective maternal goddess, or if her presence in the camps was primarily a calculated political strategy designed to forge an unbreakable emotional bond between the legions and the young heirs. Regardless of modern academic debate, the visual image of the Syrian empress distributing imperial bonuses and visiting wounded soldiers in the military hospitals created a fierce, fanatical loyalty that shielded the Severan dynasty for decades across every frontier.",
    "Severus and Domna instituted sweeping reforms that transformed the daily lives of Roman soldiers, dramatically increasing their annual pay from three hundred to five hundred denarii and officially legalizing military marriage during active service for the first time in Roman history. Announcing a major salary increase and the right to live openly with their families inside civilian settlements outside fortress walls was greeted by the legionaries with the kind of euphoric celebration modern workers experience when receiving an unexpected year-end bonus and permanent flexible work privileges.",
    "In the winter of one hundred ninety-seven, the Roman army reached the great Parthian capital of Ctesiphon on the Tigris River, carrying the city by storm and capturing immense treasures of gold, silver, and precious Persian silks. Severus was hailed as Parthicus Maximus, and the young Caracalla was elevated to the rank of Augustus, making him full co-emperor alongside his father at the tender age of ten. Domna watched the coronation ceremony within the captured palace of the Persian kings, surrounded by the triumphant standards of thirty Roman legions.",
    "Following the Parthian campaign, the imperial family spent two years touring the ancient provinces of Syria, Palestine, and Egypt, sailing slowly up the Nile River to inspect the pyramids of Giza and the colossal statues of Thebes. Domna was received in Alexandria with ecstatic acclamations, where scholars and philosophers hailed her as a modern Isis, the divine queen who united the wisdom of the East with the temporal power of Rome. She walked through the grand libraries and museums of Alexandria, absorbing the timeless knowledge of the Hellenistic world.",
    "Every evening during the Nile journey, as the red sun dipped below the Saharan dunes and painted the river in shades of molten bronze, Domna sat on the deck of the imperial barge listening to Egyptian astronomers explain the celestial cycles. The gentle lapping of the Nile against the cedar hull, the rustle of papyrus reeds along the banks, and the distant cry of waterbirds created an atmosphere of hypnotic, timeless tranquility. It was a rare interlude of intellectual peace in a life destined for relentless political strife.",
    "By the year two hundred two, the imperial family returned to Rome to celebrate a magnificent triumph and the decennalia, marking ten years of Severus's victorious reign. Lavish gladiatorial games, chariot races in the Circus Maximus, and distributions of grain and olive oil delighted the Roman populace. A colossal marble triumphal arch, the Arch of Septimius Severus, was dedicated in the Forum Romanum, its sculpted marble reliefs depicting the Mesopotamian campaigns and bearing the names of the emperor and his sons.",
    "You stand with Domna in the quiet inner gardens of the imperial palace as midnight falls over the city of Rome, listening to the soft splashing of marble fountains under the stars. The empire is at peace, the borders are secure from the Scottish highlands to the Persian Gulf, and the Severan dynasty appears unshakable in its majesty. You take a slow, calming breath of the cool night air, feeling the profound stillness of an empire resting at the zenith of its power, tranquil and serene."
]

def build_act1_all():
    write_file("parts_p01_p02.py", "P01_PARAGRAPHS", P01, "P02_PARAGRAPHS", P02)
    write_file("parts_p03_p04.py", "P03_PARAGRAPHS", P03, "P04_PARAGRAPHS", P04)
    # We will write P05 with P06 in build_act2_full.py or separate

if __name__ == "__main__":
    build_act1_all()
