"""
HISTORYSNOOZE: ACT I SCRIPT TEXT BUILDER (PARTS 01 - 05)
Module: build_act1_texts.py
Target: 1,070 - 1,130 words per part.
SSOT-compliant with 01_STYLE_BIBLE_&_GOLDEN_EXAMPLES.md.
"""

from build_full_script_generator import write_file

# --- PART 01 ---
P01_PARAS = [
    "Hey guys, tonight we are going to drift back in time to the warm, star-dusted desert nights of ancient Roman Syria, where the scent of cedarwood, crushed frankincense, and desert jasmine lingers over the basalt terraces of Emesa... And let us be honest, given the cutthroat dynastic betrayals, ruthless civil wars, and poisonous palace intrigues of the Roman imperial world, you probably would not survive this with your peaceful assumptions intact. But that is the fun of it. So, before you get comfortable, take a moment to like the video and subscribe, but only if you genuinely enjoy what I do here. And for a bit of fun, post your location and local time in the comments below. It is always a quiet thrill to see where everyone is drifting off from. Now, dim the lights, maybe turn on a fan for that soft background hum, and let us ease into tonight's journey together.",
    "You stand on the high stone parapet of the royal palace of Emesa under a vast indigo sky studded with crystalline Syrian stars. The air is cool after the relentless heat of the desert sun, carrying the dry, resinous perfume of frankincense burning in bronze braziers across the lower city. Far below your feet, the dark waters of the Orontes River flow silently through olive groves and date palms, catching the silver shimmer of the rising crescent moon. It is the second century of the common era, in the year one hundred sixty, and you are breathing the sacred air of a city that blends the immense wealth of ancient desert trade routes with the monumental prestige of Rome, creating an atmosphere of timeless, nocturnal grandeur that gently calms the weary mind.",
    "Beside you, the young princess Julia Domna watches the silent constellations wheel above the desert horizon with quiet, contemplative grace. She is wrapped in a flowing palla of deep Tyrian purple silk, bordered with delicate gold embroidery that glints softly in the flickering lamplight. Her dark eyes reflect an intellect nurtured by the finest libraries of the Hellenistic East, studying mathematics, astronomy, rhetoric, and classical literature under the guidance of renowned scholars. Growing up in a royal household of hereditary priest-kings is remarkably similar to managing an inescapable royal family enterprise where every private conversation is subject to centuries of dynastic expectation, high-stakes diplomacy, and relentless strategic calculus.",
    "Her father, Julius Bassianus, is the supreme high priest of the temple of Elagabal, the supreme sun deity revered across the Syrian lands in the sacred form of a massive black conical meteorite. As high priest of this ancient cult, Julius Bassianus commands not only immense spiritual devotion but also vast agricultural estates, trade monopolies, and influential connections reaching directly to the Roman Senate. You can hear the distant chanting of temple priests drifting through the cool night air, rhythmic and hypnotic, accompanied by the gentle cadence of double pipes and bronze finger cymbals echoing across stone courtyards, filling the desert night with reverent music that resonates deeply in your chest.",
    "In the quiet courtyards of the palace, scholars and astrologers gather nightly to chart the intricate movements of wandering planets against the velvet dome of the Syrian sky. In antiquity, consulting astrologers regarding the natal charts of highborn children was very much like obsessively checking your personal notifications and algorithmic forecasts before making any major life decision. The court astrologers cast the horoscope of the young Julia Domna, studying the alignments of Jupiter and Venus with mathematical precision, and they whisper a startling prophecy across the shadowed porticos: the young noblewoman possesses a royal horoscope, indicating that whoever marries her will one day sit upon the throne of an emperor.",
    "Historians still argue whether this famous royal horoscope was an authentic astrological reading recorded during her youth in Emesa, or a brilliant piece of post-accession Severan imperial propaganda crafted to justify her family's divine right to rule. Yet in the ancient Mediterranean world, where signs, omens, and celestial alignments dictated the decisions of generals and senators alike, such a reputation spread quietly along the merchant caravans and military highways of the empire, reaching ambitious men across the provinces who dreamed of supreme dominion and sovereign glory under the banner of the Roman legions.",
    "You feel the gentle desert breeze ruffle the silk draperies of the palace colonnade, bringing the faint aroma of roasting pistachios, dried figs, and sweet dates from the sleeping merchant quarters. The silence of the desert night settles deep into your bones, broken only by the rhythmic footsteps of guards patrolling the outer city gates with bronze-tipped spears. Emesa is a crossroads of the world, where camel trains arriving from the Silk Roads of Parthia exchange silks, spices, and precious gems for Roman glassware and Spanish olive oil, creating a cosmopolitan atmosphere of boundless wealth and cultural sophistication.",
    "Julia Domna was raised to command this complex tapestry of cultures, speaking fluent Greek, classical Latin, and her native Aramaic dialect with effortless grace and eloquence. She watched her father navigate delicate negotiations between local Arab tribal leaders and haughty Roman governors, learning that true authority is rarely exercised through overt force alone, but rather through quiet intelligence, persuasive charm, and supreme self-control. Navigating ancient imperial governance was not unlike trying to coordinate conflicting regional schedules across multiple time zones without the benefit of digital calendars or instant messaging, requiring exceptional patience and political foresight.",
    "As the hours of the second watch glide by, oil lamps flicker low in their terracotta saucers, casting long, dancing shadows across the polished limestone mosaics of the courtyard. You can sense the quiet determination gathering in the young princess, a conscious awareness that her destiny lies far beyond the palm groves of Syria and the sacred sanctuary of the Black Stone. The world beyond Emesa is vast, turbulent, and hungry for leadership, and she prepares herself to step onto the grandest stage the ancient world could offer, mastering statecraft with calm resolve.",
    "You take a slow, deep breath of the fragrant desert night air, feeling the peaceful stillness of ancient Syria surround you like a warm mantle. The stars overhead shine with steady, ancient brilliance, untroubled by the rise and fall of mortal empires, while the silent river continues its timeless journey toward the Mediterranean sea. The foundation of an empire is quietly being laid in this tranquil eastern sanctuary, where an ambitious young woman watches the night sky and awaits the turning of the wheel of fortune with serene and unshakable confidence, resting peacefully under the starry heavens."
]

# --- PART 02 ---
P02_PARAS = [
    "You travel westward across the sun-drenched waters of the Mediterranean to the Roman province of Gallia Lugdunensis in the year one hundred eighty-seven of the common era. Twilight descends over the rugged provincial capital of Lugdunum, where the cold, grey waters of the Rhone and Saone rivers converge beneath massive stone bridges and red-tiled Roman rooftops. The crisp northern air smells of river silt, pine smoke from garrison hearths, damp slate, and roasting barley, a stark contrast to the balmy, spice-laden desert winds of Syrian Emesa, wrapping the provincial landscape in an atmosphere of quiet, brooding power and ancient frontier discipline that invites quiet contemplation.",
    "Inside the governor's residence, an ambitious Roman senator named Lucius Septimius Severus sits at a heavy oak table covered with parchment scrolls, census ledgers, and military dispatches. Born in the Phoenician-Punic port city of Leptis Magna on the coast of North Africa, Severus is a hardened military commander with sharp, piercing eyes, a trimmed curly beard, and an unyielding will to power. Reviewing endless provincial tax requisitions and garrison grain quotas by the dim glow of an oil lamp is the ancient equivalent of spending your entire evening plowing through an overflowing inbox of urgent administrative emails that never seem to stop arriving.",
    "Severus, having recently lost his first wife Paccia Marciana, is actively seeking a new marriage alliance that can elevate his political standing and fulfill his deep-seated astrological ambitions. Being deeply superstitious and fascinated by Eastern divination, Severus had diligently researched the horoscopes of eligible noblewomen across the Roman Mediterranean world. When reports reached him of the Syrian priest-king's daughter in Emesa who possessed an unmistakable royal horoscope promising a crown to her future husband, Severus dispatched formal envoys across the sea to propose marriage without a moment of hesitation, knowing that destiny favored the bold and the prepared.",
    "Some historians question whether Severus was genuinely motivated by romantic attraction and intellectual compatibility, or if his decision was purely a cold, calculated political maneuver to secure the immense wealth and religious prestige of the Emesene priestly dynasty. In reality, the union between the North African general and the Syrian princess proved to be one of the most formidable intellectual, financial, and political partnerships in the entire history of classical antiquity, merging Western military grit with Eastern cultural refinement, philosophical wisdom, and sovereign diplomatic authority.",
    "Julia Domna, now in her early twenties, arrived in the Western provinces with an entourage of scholars, secretaries, and substantial financial backing from the temple treasury of Elagabal. Their wedding in one hundred eighty-seven was celebrated with traditional Roman solemnity combined with Eastern opulence, uniting two influential provincial families outside the traditional Italian aristocratic elite. Observing Roman aristocrats trying to maintain aristocratic snobbery while secretly marveling at Syrian gold is rather like watching old money traditionalists reluctantly adjusting to new tech entrepreneurs at an elite gala, trying to conceal their envy behind polite smiles.",
    "Within a year of their marriage, while residing in Lugdunum, Julia Domna gave birth to their first son, Lucius Septimius Bassianus, who would later be known to history and his soldiers by the nickname Caracalla. The child was named in honor of Domna's father, Julius Bassianus, cementing the profound bond between the imperial family and the sacred sun-cult of Syria. The infant's nursery was guarded day and night by loyal African and Syrian guards, their iron swords gleaming softly in the torchlight as rain pattered steadily against the tiled roof, keeping peaceful watch over the imperial heir in the quiet darkness.",
    "In the following year, one hundred eighty-nine, while Severus served as governor in the Mediterranean province of Sicily, Domna gave birth to their second son, Publius Septimius Geta. The imperial household was now blessed with two male heirs, seemingly guaranteeing dynastic continuity and stability in a Roman world increasingly shaken by political instability and imperial extravagance in Rome under Emperor Commodus. Yet beneath the joyful family celebrations, subtle rivalries between the two young brothers began to manifest almost from their earliest infancy, foreshadowing future tragedies that no parent could easily bear, despite all their wealth and power.",
    "You walk beside Domna through the colonnaded peristyle garden of their Sicilian villa as the twilight fades into a serene, indigo night. The air is scented with blooming orange blossoms, wild rosemary, and the salty breeze blowing off the Ionian Sea, creating an oasis of quiet domesticity amidst brewing political storms. Domna personally supervised the education of her two sons, ensuring they were instructed in Greek philosophy, Latin rhetoric, military strategy, and Syrian religious customs by the finest tutors of the Mediterranean world, instilling in them the knowledge and discipline required to govern an empire.",
    "Meanwhile, back in Rome, the erratic behavior of Emperor Commodus was pushing the empire toward a catastrophic political crisis that would soon engulf the entire Mediterranean basin. Severus received encrypted dispatches from trusted senatorial allies in the capital, detailing growing conspiracies, senate purges, and the restless mood of the Praetorian Guard. Preparing for a potential civil collapse while maintaining an outward appearance of dutiful provincial loyalty required a level of diplomatic multitasking that would test the nerves of any modern executive managing a corporate crisis under the watchful gaze of hostile competitors.",
    "As the lamps in the villa are extinguished one by one, leaving only the soft moonlight filtering through the marble columns, you feel the calm before the coming tempest. Domna stands by the window, listening to the gentle rhythm of the waves breaking against the rocky Sicilian shore, knowing that the prophecies of her youth are drawing inexorably closer. In the quiet darkness of the Mediterranean night, the family rests, gathered together before the storm of imperial power breaks across the Roman world in thunderous fury and sovereign glory, peaceful and undisturbed under the stars."
]

def build_act1():
    write_file("parts_p01_p02.py", "P01_PARAGRAPHS", P01_PARAS, "P02_PARAGRAPHS", P02_PARAS)

if __name__ == "__main__":
    build_act1()
