"""
HISTORYSNOOZE: CANONICAL TEXT DEFINITION & CALIBRATION SCRIPT
Module: create_canonical_text.py
SSOT-compliant with 01_STYLE_BIBLE_&_GOLDEN_EXAMPLES.md & 02_SCRIPT_SOP_&_GATEKEEPERS.md.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

# --- PART 01 ---
P01 = [
    "Hey guys, tonight we are going to drift back in time to the warm, star-dusted desert nights of ancient Roman Syria, where the scent of cedarwood, crushed frankincense, and desert jasmine lingers over the basalt terraces of Emesa... And let us be honest, given the cutthroat dynastic betrayals, ruthless civil wars, and poisonous palace intrigues of the Roman imperial world, you probably would not survive this with your peaceful assumptions intact. But that is the fun of it. So, before you get comfortable, take a moment to like the video and subscribe, but only if you genuinely enjoy what I do here. And for a bit of fun, post your location and local time in the comments below. It is always a quiet thrill to see where everyone is drifting off from. Now, dim the lights, maybe turn on a fan for that soft background hum, and let us ease into tonight's journey together.",
    "You stand on the high stone parapet of the royal palace of Emesa under a vast indigo sky studded with crystalline Syrian stars. The air is cool after the relentless heat of the desert sun, carrying the dry, resinous perfume of frankincense burning in bronze braziers across the lower city. Far below your feet, the dark waters of the Orontes River flow silently through olive groves and date palms, catching the silver shimmer of the rising crescent moon. It is the second century of the common era, in the year one hundred sixty, and you are breathing the sacred air of a city that blends the wealth of ancient desert trade routes with the monumental prestige of Rome, creating an atmosphere of timeless, nocturnal grandeur.",
    "Beside you, the young princess Julia Domna watches the silent constellations wheel above the desert horizon with quiet, contemplative grace. She is wrapped in a flowing palla of deep Tyrian purple silk, bordered with delicate gold embroidery that glints softly in the flickering lamplight. Her dark eyes reflect an intellect nurtured by the finest libraries of the Hellenistic East, studying mathematics, astronomy, rhetoric, and classical literature under the guidance of renowned scholars. Growing up in a royal household of hereditary priest-kings is remarkably similar to managing an inescapable royal family enterprise where every private conversation is subject to centuries of dynastic expectation, high-stakes diplomacy, and relentless strategic calculus.",
    "Her father, Julius Bassianus, is the supreme high priest of the temple of Elagabal, the supreme sun deity revered across the Syrian lands in the sacred form of a massive black conical meteorite. As high priest of this ancient cult, Julius Bassianus commands not only immense spiritual devotion but also vast agricultural estates, trade monopolies, and influential connections reaching directly to the Roman Senate. You can hear the distant chanting of temple priests drifting through the cool night air, rhythmic and hypnotic, accompanied by the gentle cadence of double pipes and bronze finger cymbals echoing across stone courtyards, filling the desert night with reverent music.",
    "In the quiet courtyards of the palace, scholars and astrologers gather nightly to chart the intricate movements of wandering planets against the velvet dome of the Syrian sky. In antiquity, consulting astrologers regarding the natal charts of highborn children was very much like obsessively checking your personal notifications and algorithmic forecasts before making any major life decision. The court astrologers cast the horoscope of the young Julia Domna, studying the alignments of Jupiter and Venus with mathematical precision, and they whisper a startling prophecy across the shadowed porticos: the young noblewoman possesses a royal horoscope, indicating that whoever marries her will one day sit upon the throne of an emperor.",
    "Historians still argue whether this famous royal horoscope was an authentic astrological reading recorded during her youth in Emesa, or a brilliant piece of post-accession Severan imperial propaganda crafted to justify her family's divine right to rule. Yet in the ancient Mediterranean world, where signs, omens, and celestial alignments dictated the decisions of generals and senators alike, such a reputation spread quietly along the merchant caravans and military highways of the empire, reaching ambitious men across the provinces who dreamed of supreme dominion and sovereign glory under the banner of the Roman legions.",
    "You feel the gentle desert breeze ruffle the silk draperies of the palace colonnade, bringing the faint aroma of roasting pistachios, dried figs, and sweet dates from the sleeping merchant quarters. The silence of the desert night settles deep into your bones, broken only by the rhythmic footsteps of guards patrolling the outer city gates with bronze-tipped spears. Emesa is a crossroads of the world, where camel trains arriving from the Silk Roads of Parthia exchange silks, spices, and precious gems for Roman glassware and Spanish olive oil, creating a cosmopolitan atmosphere of boundless wealth and cultural sophistication.",
    "Julia Domna was raised to command this complex tapestry of cultures, speaking fluent Greek, classical Latin, and her native Aramaic dialect with effortless grace and eloquence. She watched her father navigate delicate negotiations between local Arab tribal leaders and haughty Roman governors, learning that true authority is rarely exercised through overt force alone, but rather through quiet intelligence, persuasive charm, and supreme self-control. Navigating ancient imperial governance was not unlike trying to coordinate conflicting regional schedules across multiple time zones without the benefit of digital calendars or instant messaging, requiring exceptional patience and political foresight.",
    "As the hours of the second watch glide by, oil lamps flicker low in their terracotta saucers, casting long, dancing shadows across the polished limestone mosaics of the courtyard. You can sense the quiet determination gathering in the young princess, a conscious awareness that her destiny lies far beyond the palm groves of Syria and the sacred sanctuary of the Black Stone. The world beyond Emesa is vast, turbulent, and hungry for leadership, and she prepares herself to step onto the grandest stage the ancient world could offer, mastering statecraft with calm resolve.",
    "You take a slow, deep breath of the fragrant desert night air, feeling the peaceful stillness of ancient Syria surround you like a warm mantle. The stars overhead shine with steady, ancient brilliance, untroubled by the rise and fall of mortal empires, while the silent river continues its timeless journey toward the Mediterranean sea. The foundation of an empire is quietly being laid in this tranquil eastern sanctuary, where an ambitious young woman watches the night sky and awaits the turning of the wheel of fortune with serene and unshakable confidence."
]

print("P01 word count:", sum(len(p.split()) for p in P01))
