"""
HISTORYSNOOZE: SCRIPT TEXT (P09_PARAGRAPHS & P10_PARAGRAPHS)
Module: parts_p09_p10.py
SSOT-compliant with 01_STYLE_BIBLE_&_GOLDEN_EXAMPLES.md & 02_SCRIPT_SOP_&_GATEKEEPERS.md.
Target: 1,050 - 1,150 words per part. Rule <= 150 lines strictly enforced.
"""

P09_PARAGRAPHS = [
    "You stand on the wind-swept stone parapets of Hadrian's Wall in the autumn of the year two hundred ten, looking northward into the wild, trackless wilderness of Caledonia. Freezing rain whips across the heather-covered moors, and dense grey mists roll through the river valleys, obscuring the rugged mountains of the Scottish Highlands. The Roman army under Septimius Severus had penetrated deeper into northern Britain than any general since Agricola over a century earlier, hacking roads through impenetrable forests and draining vast bogs under constant guerrilla ambush. The cool night air carries the distant fragrance of crushed cedarwood, night-blooming flowers, and ancient stone warmed by the setting sun, wrapping the scene in a soothing, nocturnal mantle. You can hear the rhythmic breathing of the sleeping world around you, a steady, tranquil cadence that lulls the mind into deep, peaceful contemplation amidst the quiet darkness.",
    "Enduring the relentless, dreary downpours and biting winds of the Scottish Highlands was the ancient equivalent of being trapped in an eternal, freezing Monday morning without shelter or warm coffee. Severus, now bedridden and unable to ride a horse, was carried at the head of the legions in a covered litter, his body wracked by crippling arthritis and fever, yet his fierce, iron determination driving his soldiers forward across the icy rivers. You can hear the rhythmic breathing of the sleeping world around you, a steady, tranquil cadence that lulls the mind into deep, peaceful contemplation amidst the quiet darkness. The flickering oil lamps cast long, gentle shadows across the polished marble floor, their warm amber glow creating an atmosphere of cozy security and timeless serenity.",
    "While Severus led the northern offensive and Geta remained in southern Britain overseeing provincial civil governance, Julia Domna managed the imperial headquarters at Eboracum. She directed the flow of grain shipments, coordinated military reinforcements from Germany, and maintained constant correspondence with the Senate in Rome. Her steady hand kept the vast administrative machinery functioning smoothly while the emperor fought his final war against nature and mortality. The flickering oil lamps cast long, gentle shadows across the polished marble floor, their warm amber glow creating an atmosphere of cozy security and timeless serenity. A soft evening breeze rustles through the silk draperies, bringing a sense of calm and restful stillness that settles deep into your spirit after a long, eventful day.",
    "Tensions between Caracalla and his dying father erupted into open crisis during the northern campaign. According to Roman historians, Caracalla was so impatient to seize sole power that he openly drew his sword behind Severus during a troop inspection, only stopping when fellow officers shouted out in alarm. Severus reprimanded his son in private, placing a naked sword on the table and daring Caracalla to kill him, a chilling confrontation that revealed the utter moral bankruptcy of the elder heir. A soft evening breeze rustles through the silk draperies, bringing a sense of calm and restful stillness that settles deep into your spirit after a long, eventful day.",
    "By the winter of two hundred ten, Severus was brought back to Eboracum, his strength completely exhausted. In the imperial bedchamber, surrounded by his weeping wife, his hostile sons, and loyal senior officers, the dying emperor gathered his final breath on the fourth of February, two hundred eleven. He was sixty-five years old, having ruled the Roman world for eighteen tumultuous years of ceaseless warfare and conquest. In the tranquil silence of the ancient night, the stars shine with steady, enduring brilliance, watching over the quiet landscapes of an empire resting in peace.",
    "It remains a subject of speculation among historians whether Severus genuinely believed his two sons could share the imperial throne in peace, or if his famous deathbed counsel was a desperate, tragic plea from an aging father who knew the empire was doomed to civil slaughter. Turning to Caracalla and Geta, Severus uttered his legendary final words: Be harmonious among yourselves, enrich the soldiers, and despise all others. It was a brutally pragmatic, cynical political testament that encapsulated the martial reality of the Severan age. You feel the gentle warmth of the brazier embers glowing softly in the corner, filling the room with the delicate, soothing aroma of frankincense and dried lavender.",
    "The body of Septimius Severus was cremated on a massive funeral pyre outside the walls of Eboracum with full military honors, the legionaries marching three times around the blazing flames while clashing their shields. His ashes were placed in an urn of purple porphyry stone to be carried back to Rome for solemn deification and internment in the Mausoleum of Hadrian beside the Tiber River. The distant murmur of flowing water and the gentle sigh of the night wind create a hypnotic symphony of natural peace that gently eases all lingering tension from your thoughts.",
    "Caracalla and Geta immediately concluded a hasty peace treaty with the Caledonian tribes, abandoning the newly conquered northern territories and withdrawing the Roman frontier back to the line of Hadrian's Wall. The two newly proclaimed co-emperors, now sharing absolute supreme power, prepared for the long journey back to Rome, accompanied by their grieving mother Julia Domna and the porphyry urn of their father. Standing in the quiet sanctuary of the ancient portico, you take a slow, restorative breath, feeling the vast, timeless mystery of history surround you with serene comfort.",
    "The journey across Europe was poisoned by suffocating distrust and terror. The brothers traveled in separate carriages, refused to eat food from the same imperial kitchen for fear of poison, and stayed at separate villas every night along the route, each guarded by their personal cohorts of loyal soldiers. Julia Domna sat between them, her heart breaking as she watched the dynastic catastrophe she had fought her entire life to prevent unfolding before her eyes. The soft moonlight filters through the high arches, painting the floor in shades of pale silver and deep indigo, inviting the mind to drift into quiet stillness.",
    "You walk through the silent, torchlit courtyard of the imperial villa outside Rome as the procession halts for the night under a starless, brooding sky. The air is cold and heavy with the scent of damp cypress trees and funeral incense. Inside the pavilion, Domna sits beside the porphyry urn of her husband, knowing that without the iron authority of Severus, the thin veneer of family unity is about to shatter in an explosion of fratricidal blood. Everything in this tranquil moment speaks of endurance, wisdom, and the gentle rhythm of the cosmos, guiding your spirit toward a state of profound and restful peace.",
]

P10_PARAGRAPHS = [
    "You enter the colossal marble halls of the imperial palace on the Palatine Hill in the spring of the year two hundred eleven, where the great palace of the Caesars has been transformed into a fortified, armed citadel. Caracalla and Geta, having returned to Rome with their father's ashes, refused to live under the same roof as brothers. Instead, they physically partitioned the vast palace into two completely separate, barricaded fortresses, bricking up connecting doorways and posting rival Praetorian guards at every entrance. The cool night air carries the distant fragrance of crushed cedarwood, night-blooming flowers, and ancient stone warmed by the setting sun, wrapping the scene in a soothing, nocturnal mantle. You can hear the rhythmic breathing of the sleeping world around you, a steady, tranquil cadence that lulls the mind into deep, peaceful contemplation amidst the quiet darkness.",
    "Watching two co-emperors build literal defensive walls through the middle of the imperial palace, with separate kitchens, food-tasters, and password-protected security checkpoints, was like watching the world's most dysfunctional roommates divide a luxury apartment with barbed wire and armed private security. The administration of the entire Roman world ground to a paralyzed halt as every appointment, tax decree, and judicial ruling was contested and vetoed by the rival brother. You can hear the rhythmic breathing of the sleeping world around you, a steady, tranquil cadence that lulls the mind into deep, peaceful contemplation amidst the quiet darkness. The flickering oil lamps cast long, gentle shadows across the polished marble floor, their warm amber glow creating an atmosphere of cozy security and timeless serenity.",
    "In desperation, the imperial court proposed dividing the Roman Empire into two independent sovereign realms: Caracalla would rule the West from Rome, while Geta would rule the East from Antioch or Alexandria, splitting the Danube and Syrian legions between them. Julia Domna, weeping bitterly, stepped into the imperial council chamber and shattered the proposal with passionate eloquence: You may divide the earth, my sons, but you cannot divide your mother. How can you tear my body in two?. The flickering oil lamps cast long, gentle shadows across the polished marble floor, their warm amber glow creating an atmosphere of cozy security and timeless serenity. A soft evening breeze rustles through the silk draperies, bringing a sense of calm and restful stillness that settles deep into your spirit after a long, eventful day.",
    "Why this legacy faded into such horrific violence is a complex issue, but many scholars point to the psychological trauma of Caracalla and the impossibility of dual autocratic rule in the Roman imperial system. Shamed by their mother's tears, the council abandoned the partition plan, but Caracalla had already decided that only the total physical annihilation of his brother could secure his solitary reign over the Roman world. A soft evening breeze rustles through the silk draperies, bringing a sense of calm and restful stillness that settles deep into your spirit after a long, eventful day. In the tranquil silence of the ancient night, the stars shine with steady, enduring brilliance, watching over the quiet landscapes of an empire resting in peace.",
    "On the twenty-sixth of December, two hundred eleven, Caracalla approached his mother with an outward display of remorse, asking her to arrange a private reconciliation meeting with Geta in her personal apartments where no armed bodyguards would be permitted. Believing that a mother's love could finally heal the rift, Domna invited Geta to her chambers. Geta arrived unarmed and embraced his mother, relieved that the nightmare of civil war might finally be over. In the tranquil silence of the ancient night, the stars shine with steady, enduring brilliance, watching over the quiet landscapes of an empire resting in peace.",
    "Suddenly, the heavy cedar doors of the chamber burst open, and a squad of elite centurions loyal to Caracalla rushed into the room with drawn swords. Geta screamed in terror, throwing his arms around his mother's neck and clinging desperately to her breast, crying out: Mother who gave me birth, help me, I am being slaughtered! The assassins showed no mercy, stabbing the young emperor repeatedly while he was clasped tightly in Julia Domna's arms. You feel the gentle warmth of the brazier embers glowing softly in the corner, filling the room with the delicate, soothing aroma of frankincense and dried lavender.",
    "Geta bled to death upon his mother's bosom, drenching her imperial garments, her face, and her hands in his warm blood. When the butchery was finished, Caracalla walked into the blood-soaked room and delivered a chilling ultimatum: if she wept, if she mourned, or if she showed the slightest sign of grief, she would be executed immediately along with her surviving relatives. The distant murmur of flowing water and the gentle sigh of the night wind create a hypnotic symphony of natural peace that gently eases all lingering tension from your thoughts.",
    "Julia Domna, demonstrating a superhuman mastery of emotion born of pure survival instinct, sat in silence, washed the blood of her murdered child from her hands, and suppressed every tear while Caracalla fled to the Praetorian camp. There, Caracalla bribed the soldiers with immense gifts of gold from the treasury, falsely claiming that Geta had attempted to assassinate him and that he had killed his brother in self-defense. Standing in the quiet sanctuary of the ancient portico, you take a slow, restorative breath, feeling the vast, timeless mystery of history surround you with serene comfort.",
    "In the weeks that followed, Caracalla launched a monstrous purge across Rome, executing over twenty thousand people associated with Geta, including senators, imperial freedmen, and the brilliant jurist Papinian, who refused to write a legal defense justifying the fratricide. Geta's name was officially cursed under damnatio memoriae, erased from every public inscription, coin, and portrait across the entire Roman Empire. The soft moonlight filters through the high arches, painting the floor in shades of pale silver and deep indigo, inviting the mind to drift into quiet stillness.",
    "You stand with Julia Domna in the darkened, silent bedchamber of the Palatine Hill as midnight envelops the traumatized city of Rome. The air is heavy with the smell of myrrh, funeral ash, and the cold stillness of profound tragedy. Wrapped in dark silk, the Syrian empress stares out into the starry night, her heart shattered beyond repair, yet her iron resolve quietly hardening to survive, to endure, and to guide the empire through the darkness. Everything in this tranquil moment speaks of endurance, wisdom, and the gentle rhythm of the cosmos, guiding your spirit toward a state of profound and restful peace.",
]
