"""
HISTORYSNOOZE: ACT II RAW PARAGRAPHS (PARTS 07 TO 10)
Module: raw_text_act2.py
SSOT-compliant with 01_STYLE_BIBLE_&_GOLDEN_EXAMPLES.md.
Rule <= 150 lines strictly enforced.
"""

P07_RAW = [
    "You step into the tense, shadowed corridors of the imperial palace in Rome during the opening years of the third century, where every whisper carries the threat of betrayal. While Julia Domna cultivated philosophy, literature, and jurisprudence in her salon, a sinister shadow had grown over the Roman Empire in the person of Gaius Fulvius Plautianus. As the commander of the Praetorian Guard and a fellow countryman of Septimius Severus from Leptis Magna, Plautianus had accumulated terrifying, unchecked authority across the state.",
    "Plautianus controlled the secret police, the imperial finances, and the military garrison of Rome, effectively operating as the second emperor of the Roman world. Possessing the paranoid jealousy of an unchecked authoritarian, he viewed Julia Domna's profound intellectual influence over Severus as the single greatest obstacle to his supreme ambition. Experiencing the suffocating atmosphere of Plautianus's palace espionage was remarkably similar to working under a toxic, megalomaniac senior executive who monitors everyone's private messages and demands absolute subservience.",
    "Unable to attack the revered empress openly, Plautianus launched a vicious campaign of character assassination, bribing corrupt informers and torturing noblewomen to manufacture false allegations of adultery and treason against Julia Domna. Rather than engaging in a chaotic public brawl that could destabilize her husband's government, Domna demonstrated supreme political discipline, quietly retreating into her philosophical studies while methodically gathering evidence and biding her time. Withdrawing strategically while documenting your opponent's overreach is the ancient equivalent of quietly taking screenshots and saving receipts before a decisive showdown.",
    "Plautianus reached the zenith of his hubris in the year two hundred two when he compelled Septimius Severus to marry his young daughter, Fulvia Plautilla, to the imperial heir Caracalla. The lavish wedding was celebrated with obscene extravagance, but the teenage Caracalla loathed his bride from the moment of their union, refusing to share her bed or eat meals in her presence and openly vowing to execute both Plautilla and her father the instant he inherited the throne.",
    "Witnessing an arranged dynastic marriage characterized by open, venomous contempt between two spoiled teenagers was like watching an excruciating, high-stakes reality television disaster unfold in real time. Plautilla lived in constant terror inside the imperial palace, caught between her father's monstrous ambition and her young husband's psychopathic fury, while Julia Domna maintained a cold, dignified distance from the domestic chaos.",
    "There remains some academic debate over whether Plautianus actually plotted to assassinate Severus and Caracalla in a palace coup, or if the conspiracy was an elaborate entrapment operation orchestrated by Caracalla and Julia Domna to rid themselves of an unbearable tyrant. Ancient historians Cassius Dio and Herodian provide contrasting accounts, but both agree that Plautianus's insatiable hunger for power had made his continued survival impossible inside the Severan court.",
    "In January of the year two hundred five, a loyal Praetorian tribune approached Caracalla with written orders from Plautianus instructing him to assassinate the emperors during the night. Caracalla immediately informed his father, and an urgent summons was sent to Plautianus, instructing him to attend an emergency private conference in the imperial bedchamber on the Palatine Hill. Suspecting nothing, the arrogant prefect arrived without his usual heavy armed bodyguard, expecting to receive new honors.",
    "Upon entering the bedchamber, Plautianus was confronted directly by Severus and Caracalla in the flickering glow of bronze torches. When Plautianus attempted to protest his innocence, Caracalla drew his imperial dagger and struck the prefect, while imperial guards rushed forward to finish the execution on the spot. Plautianus's body was dragged down the palace steps and cast into the street, his statues across the empire pulled down by ecstatic crowds within hours.",
    "Plautilla was immediately stripped of her imperial titles and banished to the remote volcanic island of Lipari, ending the suffocating reign of terror that had gripped the Roman court for over a decade. Julia Domna emerged from the crisis entirely vindicated, her reputation untarnished and her political supremacy over the imperial administration fully restored. The dark shadow had been lifted, leaving the Syrian empress in undisputed control of palace diplomacy.",
    "As the winter night settles over the quiet Palatine Hill, you stand with Domna on the palace balcony overlooking the sleeping city of Rome. The distant Tiber River reflects the silver light of the stars, and the air is crisp, clean, and free of the poisonous tension that had lingered for years. Domna takes a deep, calm breath of the night air, knowing that she has survived another deadly storm through patience, wisdom, and unyielding resolve."
]

P08_RAW = [
    "Following the fall of Plautianus in two hundred five, Julia Domna assumed an unprecedented level of day-to-day administrative authority over the machinery of the Roman state. She took direct oversight of the imperial chancery, managing the complex flow of public petitions, judicial appeals, and imperial decrees known as libelli and epistulae that arrived daily from governors across Britannia, Africa, and the Euphrates. Managing the endless queue of official provincial petitions was remarkably similar to processing an overwhelming backlog of urgent customer support tickets for an entire global organization.",
    "Sitting beside Septimius Severus on the imperial tribunal in the Basilica Julia, Domna participated openly in major judicial hearings and foreign policy deliberations. Foreign ambassadors from the client kingdoms of Armenia, Osroene, and the Black Sea Greek cities presented their credentials directly to the empress, bowing low before her golden throne and marveling at her command of international diplomacy. Her official portraits on imperial bronze, silver, and gold coinage were minted in vast quantities across every provincial mint in the Roman world.",
    "Yet as external peace settled over the empire, a far more dangerous and intractable crisis was festering within the intimate confines of Julia Domna's own family. Her two sons, Caracalla and Geta, now entering their late adolescence, had developed a venomous, all-consuming mutual hatred that divided the imperial household into hostile armed camps. The brothers refused to speak to each other, dined in separate fortified wings of the palace, and surrounded themselves with rival entourages of gladiators, charioteers, and sycophantic young aristocrats.",
    "Their bitter rivalry played out openly in the public spectacles of Rome, where Caracalla passionately backed the Blue faction in the chariot races of the Circus Maximus while Geta fanatically supported the Greens. Watching the two imperial heirs turn sporting events and street brawls into proxy dynastic warfare was like watching celebrity siblings fuel endless tabloid scandals and rival social media fan bases. Domna spent countless agonizing hours attempting to mediate between her sons, pleading with them to put aside their petty jealousies for the sake of the empire.",
    "Psychologists and biographers have offered various interpretations of the toxic hatred between Caracalla and Geta, debating whether it was an inevitable clash of unyielding alpha personalities or the psychological byproduct of Severus's insistence on absolute co-equal inheritance. Severus, in his desire to protect both sons, had elevated Geta to the rank of Augustus in two hundred nine, meaning that Rome now had three co-equal Augusti—an administrative arrangement that guaranteed catastrophic conflict the moment the father died.",
    "Recognizing that the decadent, faction-ridden atmosphere of Rome was corrupting his sons and accelerating their moral decay, Severus made the sudden decision in two hundred eight to launch a massive military expedition to the distant, fog-shrouded island of Britannia. Northern barbarian tribes beyond Hadrian's Wall, known as the Caledonians and Maeatae, had broken through the frontier fortresses and were ravaging Roman Britain, providing Severus with the perfect pretext to remove his family from the toxic intrigues of the capital.",
    "Severus, now suffering severely from crippling gout and advanced age, believed that the harsh discipline of active frontier warfare would forge his sons into hardened leaders and force them to cooperate against a common enemy. Julia Domna packed her traveling library, gathered her secretaries and advisors, and prepared once again to march with the army to the absolute northern edge of the known Roman world.",
    "The imperial court traveled across Gaul in the spring of two hundred eight, crossing the stormy waters of the English Channel in a fleet of Roman warships to establish their northern administrative capital at the legionary fortress of Eboracum, modern-day York. Here, amidst the damp forests, rolling moors, and grey northern skies, Domna established the supreme seat of Roman government while Severus prepared forty thousand Roman legionaries for the invasion of Caledonia.",
    "The contrast between the warm, marble splendour of Rome and the rugged timber-and-stone fortress of Eboracum was striking, yet Domna adapted with her customary grace and tireless work ethic. She oversaw the complex logistical supply lines bringing grain from southern Britain and wine from Gaul, while receiving diplomatic delegations from local British tribal chieftains who came to swear fealty to the imperial family.",
    "You walk through the misty streets of Eboracum as a cold northern night descends over the Roman garrison, smelling the pungent smoke of burning peat and pine from legionary barracks. The rain falls steadily against the slate rooftops, and the distant call of sentries on the earthen ramparts echoes through the fog. Inside the imperial praetorium, Domna watches over her ailing husband by the warm hearth, steeling her spirit for the trials she knows are waiting in the northern mists."
]

P09_RAW = [
    "You stand on the wind-swept stone parapets of Hadrian's Wall in the autumn of the year two hundred ten, looking northward into the wild, trackless wilderness of Caledonia. Freezing rain whips across the heather-covered moors, and dense grey mists roll through the river valleys, obscuring the rugged mountains of the Scottish Highlands. The Roman army under Septimius Severus had penetrated deeper into northern Britain than any general since Agricola over a century earlier, hacking roads through impenetrable forests and draining vast bogs under constant guerrilla ambush.",
    "Enduring the relentless, dreary downpours and biting winds of the Scottish Highlands was the ancient equivalent of being trapped in an eternal, freezing Monday morning without shelter or warm coffee. Severus, now bedridden and unable to ride a horse, was carried at the head of the legions in a covered litter, his body wracked by crippling arthritis and fever, yet his fierce, iron determination driving his soldiers forward across the icy rivers.",
    "While Severus led the northern offensive and Geta remained in southern Britain overseeing provincial civil governance, Julia Domna managed the imperial headquarters at Eboracum. She directed the flow of grain shipments, coordinated military reinforcements from Germany, and maintained constant correspondence with the Senate in Rome. Her steady hand kept the vast administrative machinery functioning smoothly while the emperor fought his final war against nature and mortality.",
    "Tensions between Caracalla and his dying father erupted into open crisis during the northern campaign. According to Roman historians, Caracalla was so impatient to seize sole power that he openly drew his sword behind Severus during a troop inspection, only stopping when fellow officers shouted out in alarm. Severus reprimanded his son in private, placing a naked sword on the table and daring Caracalla to kill him, a chilling confrontation that revealed the utter moral bankruptcy of the elder heir.",
    "By the winter of two hundred ten, Severus was brought back to Eboracum, his strength completely exhausted. In the imperial bedchamber, surrounded by his weeping wife, his hostile sons, and loyal senior officers, the dying emperor gathered his final breath on the fourth of February, two hundred eleven. He was sixty-five years old, having ruled the Roman world for eighteen tumultuous years of ceaseless warfare and conquest.",
    "It remains a subject of speculation among historians whether Severus genuinely believed his two sons could share the imperial throne in peace, or if his famous deathbed counsel was a desperate, tragic plea from an aging father who knew the empire was doomed to civil slaughter. Turning to Caracalla and Geta, Severus uttered his legendary final words: Be harmonious among yourselves, enrich the soldiers, and despise all others. It was a brutally pragmatic, cynical political testament that encapsulated the martial reality of the Severan age.",
    "The body of Septimius Severus was cremated on a massive funeral pyre outside the walls of Eboracum with full military honors, the legionaries marching three times around the blazing flames while clashing their shields. His ashes were placed in an urn of purple porphyry stone to be carried back to Rome for solemn deification and internment in the Mausoleum of Hadrian beside the Tiber River.",
    "Caracalla and Geta immediately concluded a hasty peace treaty with the Caledonian tribes, abandoning the newly conquered northern territories and withdrawing the Roman frontier back to the line of Hadrian's Wall. The two newly proclaimed co-emperors, now sharing absolute supreme power, prepared for the long journey back to Rome, accompanied by their grieving mother Julia Domna and the porphyry urn of their father.",
    "The journey across Europe was poisoned by suffocating distrust and terror. The brothers traveled in separate carriages, refused to eat food from the same imperial kitchen for fear of poison, and stayed at separate villas every night along the route, each guarded by their personal cohorts of loyal soldiers. Julia Domna sat between them, her heart breaking as she watched the dynastic catastrophe she had fought her entire life to prevent unfolding before her eyes.",
    "You walk through the silent, torchlit courtyard of the imperial villa outside Rome as the procession halts for the night under a starless, brooding sky. The air is cold and heavy with the scent of damp cypress trees and funeral incense. Inside the pavilion, Domna sits beside the porphyry urn of her husband, knowing that without the iron authority of Severus, the thin veneer of family unity is about to shatter in an explosion of fratricidal blood."
]

P10_RAW = [
    "You enter the colossal marble halls of the imperial palace on the Palatine Hill in the spring of the year two hundred eleven, where the great palace of the Caesars has been transformed into a fortified, armed citadel. Caracalla and Geta, having returned to Rome with their father's ashes, refused to live under the same roof as brothers. Instead, they physically partitioned the vast palace into two completely separate, barricaded fortresses, bricking up connecting doorways and posting rival Praetorian guards at every entrance.",
    "Watching two co-emperors build literal defensive walls through the middle of the imperial palace, with separate kitchens, food-tasters, and password-protected security checkpoints, was like watching the world's most dysfunctional roommates divide a luxury apartment with barbed wire and armed private security. The administration of the entire Roman world ground to a paralyzed halt as every appointment, tax decree, and judicial ruling was contested and vetoed by the rival brother.",
    "In desperation, the imperial court proposed dividing the Roman Empire into two independent sovereign realms: Caracalla would rule the West from Rome, while Geta would rule the East from Antioch or Alexandria, splitting the Danube and Syrian legions between them. Julia Domna, weeping bitterly, stepped into the imperial council chamber and shattered the proposal with passionate eloquence: You may divide the earth, my sons, but you cannot divide your mother. How can you tear my body in two?",
    "Why this legacy faded into such horrific violence is a complex issue, but many scholars point to the psychological trauma of Caracalla and the impossibility of dual autocratic rule in the Roman imperial system. Shamed by their mother's tears, the council abandoned the partition plan, but Caracalla had already decided that only the total physical annihilation of his brother could secure his solitary reign over the Roman world.",
    "On the twenty-sixth of December, two hundred eleven, Caracalla approached his mother with an outward display of remorse, asking her to arrange a private reconciliation meeting with Geta in her personal apartments where no armed bodyguards would be permitted. Believing that a mother's love could finally heal the rift, Domna invited Geta to her chambers. Geta arrived unarmed and embraced his mother, relieved that the nightmare of civil war might finally be over.",
    "Suddenly, the heavy cedar doors of the chamber burst open, and a squad of elite centurions loyal to Caracalla rushed into the room with drawn swords. Geta screamed in terror, throwing his arms around his mother's neck and clinging desperately to her breast, crying out: Mother who gave me birth, help me, I am being slaughtered! The assassins showed no mercy, stabbing the young emperor repeatedly while he was clasped tightly in Julia Domna's arms.",
    "Geta bled to death upon his mother's bosom, drenching her imperial garments, her face, and her hands in his warm blood. When the butchery was finished, Caracalla walked into the blood-soaked room and delivered a chilling ultimatum: if she wept, if she mourned, or if she showed the slightest sign of grief, she would be executed immediately along with her surviving relatives.",
    "Julia Domna, demonstrating a superhuman mastery of emotion born of pure survival instinct, sat in silence, washed the blood of her murdered child from her hands, and suppressed every tear while Caracalla fled to the Praetorian camp. There, Caracalla bribed the soldiers with immense gifts of gold from the treasury, falsely claiming that Geta had attempted to assassinate him and that he had killed his brother in self-defense.",
    "In the weeks that followed, Caracalla launched a monstrous purge across Rome, executing over twenty thousand people associated with Geta, including senators, imperial freedmen, and the brilliant jurist Papinian, who refused to write a legal defense justifying the fratricide. Geta's name was officially cursed under damnatio memoriae, erased from every public inscription, coin, and portrait across the entire Roman Empire.",
    "You stand with Julia Domna in the darkened, silent bedchamber of the Palatine Hill as midnight envelops the traumatized city of Rome. The air is heavy with the smell of myrrh, funeral ash, and the cold stillness of profound tragedy. Wrapped in dark silk, the Syrian empress stares out into the starry night, her heart shattered beyond repair, yet her iron resolve quietly hardening to survive, to endure, and to guide the empire through the darkness."
]
