#!/usr/bin/env python3
"""
Comprehensive 16k Word Canonical Script Generator for Julie d'Aubigny
Generates the complete 15-part text and 150 scene descriptions.
"""

import os
import sys

def build_p01_p05():
    c = {}
    s = {}

    # PART 1
    c[1] = [
        "Hey guys, tonight we are going to drift back in time to the golden, candlelit halls and mist-shrouded courtyards of seventeenth-century France, where the scent of cedar shavings, polished rapier steel, and Paris opera rosin lingers over the cobblestone riding arenas of Versailles... And let us be honest, given the fiery tavern duels, midnight convent escapes, and audacious royal defiance of La Maupin's world, you probably would not survive this with your peaceful assumptions intact. But that is the fun of it. So, before you get comfortable, take a moment to like the video and subscribe, but only if you genuinely enjoy what I do here. And for a bit of fun, post your location and local time in the comments below. It is always a quiet thrill to see where everyone is drifting off from. Now, dim the lights, maybe turn on a fan for that soft background hum, and let us ease into tonight's journey together.",
        "You stand in the quiet shadows of the Grand Stables of Versailles in the crisp autumn dawn of sixteen hundred and seventy-six. The morning fog rises softly from the damp cobblestone courtyards, catching the first pale golden rays of sunlight breaking over the slate rooftops of the Sun King's palace. All around you, the air is rich and comforting, filled with the warm, earthy perfume of cedar wood shavings, freshly baled clover hay, and the steady, rhythmic breathing of hundreds of royal thoroughbreds resting peacefully in their vaulted oak stalls. In this magnificent world of equestrian discipline, a young girl named Julie d'Aubigny takes her first confident footsteps into history, her spirit untroubled by courtly vanity.",
        "Julie was the daughter of Gaston d'Aubigny, a respected secretary to Louis de Lorraine, the Count d'Armagnac and Grand Écuyer of France. Raised not within the secluded boudoirs or restrictive salons of courtly noblewomen, but amidst the brisk, open-air discipline of the Royal Riding Academy, young Julie grew up in an environment of constant physical grace, vigor, and tireless motion. Her father treated her with the same exacting standards he applied to the young aristocratic pages of the royal court. From early childhood, she learned to sit tall upon spirited Iberian thoroughbreds, guiding them through complex equestrian carousels with effortless posture, balanced hands, and quiet, unshakeable authority that earned the admiration of the palace grooms.",
        "The Grand Stables of Versailles were a triumph of French classical architecture, designed by Jules Hardouin-Mansart with soaring limestone arches and expansive arenas where soft daylight poured through high arched windows, casting long, peaceful diagonals across the raked sand. Young Julie spent countless peaceful hours exploring the vast harness rooms, where rows of polished brass buckles gleamed warmly in the soft lantern light. The leather saddles and bridles smelled soothing and rich, rubbed daily with sweet beeswax and neat's-foot oil, creating an atmosphere of timeless order, discipline, and quiet craftsmanship that deeply grounded her spirit in patience, strength, and unwavering focus.",
        "While other young girls of the French nobility were confined to lessons in delicate needlepoint, quiet embroidery, and polite harpsichord etiquette, Julie was given a wooden training foil and placed before the palace fencing masters. Her natural reflexes, balance, and spatial intuition were astonishing to all who watched her move. Shifting with the fluid agility of a hunting falcon, she grasped the subtle geometry of distance, the precision of the parry, and the swift decisiveness of the thrust. The rhythmic, hypnotic clinking of training blades against the limestone walls became her childhood lullaby, a comforting cadence of balance, breath, and unwavering mental focus.",
        "In the quiet late afternoons, when the royal pages had finished their grueling riding drills, Julie would climb the winding stone stairs to the upper galleries of the stables. From these high vantage points, she looked out over the vast gardens of Versailles, where fountains whispered in the cooling evening breeze and rows of symmetrical cypress trees stretched toward the golden horizon. Her thoughts were calm, spacious, and untroubled, filled with a deep sense of freedom and an innate confidence in her own extraordinary destiny that seemed written in the vast starlit sky above the royal estate.",
        "Gaston d'Aubigny understood that martial agility was hollow without the cultivation of the intellect. In their private living quarters above the stable courtyards, by the gentle glow of tallow candles, he tutored Julie in classical French literature, Latin philosophy, and the Italian arts. Together they read the epic poetry of Tasso and Ariosto, igniting her imagination with tales of legendary warrior maidens like Bradamante and Clorinda. The steady, rhythmic scratching of her quill on vellum blended with the distant hoot of an owl nesting in the palace groves, creating a sanctuary of quiet learning and reflection.",
        "It was also during these early Versailles years that Julie discovered the natural beauty and depth of her singing voice. Listening to the royal choristers practicing in the palace chapel across the courtyard, she would softly imitate their complex harmonies, her rich, resonant contralto echoing through the vaulted stone hallways. The stable grooms and visiting nobles would stop in wonder, captivated by the pure, hypnotic warmth of a voice that sounded both ancient and timeless, filled with effortless power, emotional depth, and soothing melodic grace that seemed to heal the restless mind.",
        "As dusk settled over Versailles, the grooms lit iron lanterns along the stable corridors, casting long amber beams across the cobblestone pavings. The horses settled into their stalls with soft nickers of contentment, chewing on sweet meadow grass and fresh oats. Julie would walk quietly through the long corridors, running her hand along the polished oak partitions, feeling the serene, grounding presence of the resting animals, her heart anchored in complete peace and contentment as the palace drifted into quiet sleep beneath the darkening autumn sky.",
        "As midnight enveloped the Grand Stables of Versailles, the iron lanterns were extinguished one by one, leaving only the cool silver light of the stars above the palace roofs. The vast riding rings lay silent and still, resting beneath the velvet sky. Young Julie closed her eyes in her chamber, her breath slow, deep, and steady, drifting into restful slumber guided by the gentle promise of a life filled with courage, artistry, and boundless adventure across the kingdom of France."
    ]

    s[1] = [
        "Young Julie d'Aubigny standing in the misty courtyard of the Grand Stables of Versailles at golden sunrise, classical French stone arches, morning mist rising from cobblestones, warm atmospheric sunlight, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Gaston d'Aubigny tutoring young Julie beside a spirited black stallion in the sunlit equestrian arena of Versailles, raked sand, leather tack, noble discipline, soft natural daylight, cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Intimate still life inside the Versailles harness room, rows of polished brass buckles, oiled leather bridles hanging on cedar walls, soft amber lantern light, serene craftsmanship, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Young Julie in linen shirt and training doublet practicing footwork with a slender wooden fencing foil, high arched limestone windows, dust motes dancing in sunbeams, focused grace, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie looking out from the high stone balustrade of the Grand Stables over the symmetrical gardens and fountains of Versailles at sunset, golden horizon, tranquil mood, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Gaston d'Aubigny and young Julie studying classical illuminated manuscripts by the gentle glow of tallow candles in a private chamber, leather-bound books, peaceful evening atmosphere, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Young Julie singing quietly in a vaulted stone arcade of Versailles, soft golden light illuminating her serene face, classical Baroque columns, hypnotic acoustic beauty, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Stable grooms hanging iron lanterns along the cobblestone corridors of the Grand Stables at dusk, horses resting peacefully in oak stalls, warm orange glow, calming stillness, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Close-up portrait of young Julie d'Aubigny with natural dark hair and confident expressive eyes, wearing a simple riding vest, soft ambient lighting, timeless dignity, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Panoramic view of the Grand Stables of Versailles under a vast starry midnight sky, crescent moon illuminating slate rooftops, peaceful sleep atmosphere, pure tranquility, wide cinematic 16:9 composition, ultra-high-resolution 4K."
    ]

    # PART 2
    c[2] = [
        "As young Julie matured into adolescence, her passion for martial arts surpassed the preliminary training available in the royal stables. Paris in the late seventeenth century was the undisputed fencing capital of the world, home to master bladesmiths and legendary Salle d'Armes where the French school of rapier and smallsword was refined into an exact science of deadly elegance. Recognizing her rare genius, her guardians permitted her to study under the finest fencing masters of the capital, stepping into a world where precision, balance, and unwavering focus reigned supreme over raw physical strength.",
        "To move with complete freedom during grueling training sessions, Julie abandoned the heavy corsets, petticoats, and voluminous silk skirts prescribed for women of her era. Instead, she adopted the practical elegance of male attire: a tailored wool doublet, crisp linen shirt, breeches, and soft leather riding boots. This attire not only granted her total athletic liberation, but also allowed her to navigate the bustling streets and fencing halls of Paris with effortless confidence, unburdened by the restrictive conventions and judgmental gazes of seventeenth-century French society.",
        "The fencing academies of Paris were temple-like spaces of polished oak floors, mirrored walls, and racks of gleaming steel blades. Here, the air carried the faint, distinctive scent of weapon oil, rosin, and fresh chalk used to mark footwork lines upon the wooden floorboards. Master swordsmen watched in astonishment as young Julie stepped onto the piste. Her movements were exceptionally light and deceptive, shifting from defensive parries to lightning ripostes with a fluid economy of motion that left seasoned cavaliers breathless with admiration.",
        "Julie mastered the intricate principles of the French fencing treatise: the precise timing of the coupe, the subtle disengage beneath an opponent's guard, and the psychological mastery of measure and distance. She learned that a duel was won not by brute force or wild aggression, but by profound mental stillness and the ability to anticipate an opponent's intention before their blade even began to move. In the quiet intensity of each practice bout, her mind achieved a state of serene, meditative clarity that calmed her heart and steady her breath.",
        "Her father's patron, the Count d'Armagnac, took a keen personal interest in her development. Seeing her extraordinary charisma, natural dignity, and sharp intellect, he introduced her to the elite circles of Parisian society. Yet Julie was never content to be merely an ornament of courtly salons. She sought genuine mastery in everything she pursued, whether translating Italian poetry, mastering the lute, or perfecting her lunges against the master fencing instructors of the King's Guard, proving herself equal to any nobleman in France.",
        "In the quiet evening hours, Julie would visit the artisan workshops along the Pont Neuf, where skilled bladesmiths forged rapiers of Toledo and Solingen steel. She would watch the glowing orange embers of the forge and listen to the rhythmic, hypnotic striking of the hammer upon the anvil. The master armorer would balance slender steel blades upon his fingertip, explaining the delicate distribution of weight that transformed a strip of forged iron into a living extension of the fencer's soul, will, and balance.",
        "Julie possessed an innate physical strength and flexibility that allowed her to practice for hours without fatigue. Her daily training included intense calisthenics, running through the morning mist of the forest of Saint-Germain, and practicing precise blade drills by the flickering light of brass oil lamps. She developed an unshakeable core of physical resilience and self-reliance, qualities that would protect her through the turbulent adventures, romantic intrigues, and dangerous encounters that lay ahead in her extraordinary life.",
        "Despite her martial prowess, Julie retained a deep love for harmony, beauty, and music. In her private lodgings overlooking the Seine, she practiced vocal scales on the harpsichord, filling the quiet Parisian evenings with the rich, soothing timbre of her contralto voice. The gentle flow of the river outside her window seemed to echo the smooth, effortless phrasing of her melodies, weaving art and martial discipline into a single harmonious spirit of rare, balanced beauty that touched every heart.",
        "Word of the remarkable young woman who fenced like a master and sang like an angel began to spread quietly through the fashionable salons of Paris. Young aristocrats and fencing enthusiasts sought her acquaintance, drawn by her magnetic confidence, sharp wit, and radiant charm. Julie met their admiration with polite composure and a mischievous smile, never allowing flattery to distract her from her daily regimen of study, practice, and continuous personal growth.",
        "As night deepened over Paris, the bustle of the streets subsided into a peaceful hush. The moonlight reflected off the slow-moving waters of the Seine and cast silver patterns across the wooden floor of Julie's chamber. She wiped down her rapier blade with an oiled cloth, returned it to its leather scabbard, and prepared for rest. Breathing slowly and deeply, she let her muscles relax completely, resting in the quiet confidence of her growing strength and artistry."
    ]

    s[2] = [
        "Young Julie d'Aubigny in an authentic seventeenth-century French Salle d'Armes, dressed in an elegant linen shirt and wool fencing doublet, practicing a classic en garde stance on polished oak floor, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Master fencing instructor guiding Julie's wrist during a foil drill, soft light filtering through high studio windows, chalked footwork lines on the floor, atmosphere of classical discipline, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Interior of a prestigious Paris fencing academy, racks of slender steel rapiers and wire-mesh masks along oak-paneled walls, warm tallow candles, quiet concentration, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie practicing a lightning-fast lunge in front of a tall gilded mirror in a Parisian studio, capturing perfect balance and athletic poise, soft afternoon shadows, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Count d'Armagnac observing young Julie in a grand salon as she demonstrates a polite fencing salute, velvet drapes, gilded Baroque furnishings, respectful admiration, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "A traditional Parisian bladesmith workshop near Pont Neuf at dusk, glowing orange forge embers, bladesmith hammering a glowing rapier blade, Julie watching with fascination, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie running through the misty autumn woods of Saint-Germain-en-Laye at dawn, crisp morning air, golden beech leaves falling gently, vibrant vitality, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie seated at a carved walnut harpsichord in her Parisian lodgings by candlelight, singing softly with open sheet music, peaceful Seine river visible through the window, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "A gathering of young French noblemen and scholars listening in quiet enchantment as Julie converses with witty charm, warm amber salon lighting, classical refinement, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie's private chamber at midnight, rapier resting in its scabbard on an antique oak table beside a leather-bound book, silver moonlight across the floor, deep restful calm, wide cinematic 16:9 composition, ultra-high-resolution 4K."
    ]

    # PART 3
    c[3] = [
        "In the year sixteen hundred and eighty-seven, at the age of fourteen, Julie was married by arrangement to Sieur de Maupin of Saint-Germain-en-Laye. Soon after the wedding, Maupin received an administrative appointment in the southern provinces, leaving his spirited young bride behind in Paris. Unwilling to accept a life of domestic confinement, Julie's path crossed with that of Sérannes, a celebrated master of arms and charismatic duelist who was forced to flee Paris after killing an opponent in an illegal duel.",
        "Without hesitation, Julie chose freedom over convention. Disguising herself in a handsome cavalier's riding coat, tricorn hat, and leather travel boots, she joined Sérannes on the post road heading south toward the sun-drenched provinces of the Midi. Riding side by side under the vast canopy of the French sky, the two swordsmen left the rigid hierarchy of Paris behind, embarking on a life of open-air adventure, independence, and shared camaraderie on the king's highway.",
        "The journey through the heart of France was a continuous tapestry of rolling hills, ancient oak forests, and picturesque rural hamlets. The steady, rhythmic clopping of horse hooves upon packed dirt roads created a soothing, hypnotic tempo that marked their progress across the provinces. By day, they traveled beneath azure skies, breathing in the fresh scents of blooming heather, damp forest moss, and warm pine needles drifting on the gentle southern breeze.",
        "When evening shadows lengthened across the countryside, Julie and Sérannes would seek shelter in rustic coaching inns and village taverns. In these warm, welcoming havens, travelers gathered around roaring stone hearths, sharing hearty meals of roasted meats, fresh bread, and local wine. Julie, accepted by all as a dashing young gentleman, charmed the innkeepers and patrons with her effortless wit, generous spirit, and captivating storytelling that brought smiles to weary faces.",
        "To finance their journey, Julie and Sérannes began offering public exhibitions of swordsmanship in village squares and market towns. They set up temporary stages in town centers, drawing enthusiastic crowds of local townsfolk, traveling merchants, and garrison soldiers. Julie's dazzling blade speed and theatrical flair turned each bout into a breathtaking display of martial artistry, earning admiring cheers and a steady stream of silver coins that sustained their travels.",
        "Along the remote mountain roads of the Massif Central, the threat of highwaymen was a constant reality for all travelers. One evening at twilight, as their carriage navigated a steep wooded pass, a band of armed brigands stepped from the shadows. Remaining calm and composed, Julie drew her rapier with lightning speed. Fighting alongside Sérannes with flawless precision, she disarmed the bandit leader in a matter of seconds, sending the rest fleeing into the forest without a single drop of blood shed.",
        "At night, when coaching inns were unavailable, the companions made camp beneath the ancient trees of the southern forests. They built small, aromatic campfires of dry oak twigs and pine cones, watching the golden sparks drift upward toward the starry sky. The crackling embers provided comforting warmth against the crisp night air, while the gentle murmur of a nearby brook lulled their tired limbs into deep relaxation and peaceful contemplation.",
        "Julie loved the simplicity of life on the open road. Wrapped in her heavy wool cloak beside the dying fire, she would gaze at the brilliant constellations wheeling slowly across the velvet night. She felt completely liberated from the superficial expectations of courtly life, discovering an unshakeable inner resilience and a profound connection to the natural rhythms of the earth that calmed her soul and clarified her purpose.",
        "During their travels, Julie never neglected her vocal training. In secluded forest glades and resonant stone ruins along the road, she would practice her operatic melodies, allowing her rich contralto voice to soar through the quiet air. The birds in the canopy would pause their songs, as if listening to the wondrous music echoing across the tranquil southern valleys with breathtaking warmth and purity.",
        "As dawn approached, the southern road was bathed in the soft rose and lavender of a new day. Julie woke refreshed and invigorated, greeting the morning breeze with a light heart and clear mind. She saddled her horse with practiced ease, ready to embrace whatever wondrous discoveries and heroic adventures awaited them on the endless, open horizon of seventeenth-century France."
    ]

    s[3] = [
        "Julie d'Aubigny and fencing master Sérannes riding side by side along a sunlit French country road, dressed in dashing cavalier riding coats and tricorn hats, rolling green hills in background, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "A seventeenth-century French coaching inn at golden hour, horses drinking from a wooden trough, carriage resting beside timber stables, warm welcoming atmosphere, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie and Sérannes seated beside a roaring stone fireplace in a rustic country tavern, surrounded by travelers sharing warm bread and wine, glowing orange hearth light, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie demonstrating an elegant fencing flourish on an outdoor wooden stage in a village square, surrounded by an astonished crowd of French villagers and merchants, sunny morning, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie and Sérannes in a dynamic defensive stance during a twilight confrontation with brigands on a forested mountain pass, rapier gleam in the fading sunset light, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "A peaceful campfire glowing beneath towering pine trees in the French countryside at night, sparks rising toward the stars, two horses tethered nearby in the shadows, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie wrapped in a warm crimson wool travel cloak, resting beside the embers of a campfire, gazing up at the brilliant starry night sky in contemplative peace, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie singing in the secluded archway of an ancient Roman aqueduct in southern France, morning sunlight illuminating the stone arches, tranquil natural beauty, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie adjusting the leather saddle girth on her resting horse by a clear mountain stream, cool water cascading over smooth pebbles, fresh morning air, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Panoramic view of a quiet post road winding through lavender fields of Provence at dawn, soft mist in the valley, peaceful beginning of a new day, wide cinematic 16:9 composition, ultra-high-resolution 4K."
    ]

    # PART 4
    c[4] = [
        "Arriving in the bustling provincial capitals of Poitiers and Bordeaux, Julie and Sérannes established a popular traveling exhibition that drew spectators from every level of society. Performing in spacious tavern courtyards, fairgrounds, and municipal squares, they offered thrilling displays of classical French swordsmanship, inviting any local gentleman or fencing enthusiast to test their skill against them in polite, controlled combat before cheering crowds.",
        "Julie's reputation as an unbeatable young swordsman grew rapidly throughout the region. Dressed in her tailored velvet doublet and leather fencing gauntlets, she met every challenger with graceful courtesy and unyielding technical perfection. Whether facing burly local duelists, seasoned garrison captains, or boastful young aristocrats, Julie deflected their aggressive attacks with effortless parries, disarming them with a flick of her wrist to the delighted applause of the crowd.",
        "In one famous encounter in a crowded town square, a defeated challenger, wounded in his pride, loudly proclaimed that Julie could not possibly be a young man, declaring that no youth could fence with such supernatural agility. The crowd grew quiet with anticipation. With a calm, confident smile, Julie stepped to the center of the stage, calmly unbuttoned her doublet, and revealed her true identity as a woman, silencing the skeptic and sending the crowd into thunderous, joyous cheers.",
        "Far from causing scandal, Julie's bold revelation elevated her into a celebrated provincial hero. The people admired her fearless honesty, extraordinary courage, and complete defiance of conventional limitations. Songs and poems were composed in her honor, celebrating the legendary swordswoman who could out-fence the finest duelists in the kingdom while retaining her enchanting beauty, witty charm, and regal personal dignity.",
        "Between fencing demonstrations, Julie delighted her audiences by singing classical French airs and lively folk ballads. Standing upon the wooden stage beneath the open sky, her rich contralto voice resonated with hypnotic depth and clarity. Listeners were moved to tears by the soulful warmth of her melodies, marveling that the same delicate hands that wielded the deadly rapier could evoke such profound emotional tenderness and musical grace.",
        "The provincial tour brought Julie a deep understanding of human nature. She conversed with people from all walks of life: humble peasants, skilled artisans, wealthy wine merchants, and provincial magistrates. She treated everyone with the same genuine respect and egalitarian warmth, winning the lasting affection of the common people wherever she traveled and establishing a reputation for noble generosity.",
        "In the quiet late afternoons, Julie would retreat to peaceful cloister gardens or shaded riverbanks to rest and recharge. Sitting on a sun-warmed stone bench beside climbing roses, she would clean her fencing foils and practice vocal breathing exercises. The gentle rustle of leaves in the southern breeze and the soothing trickle of nearby fountains restored her physical energy and deepened her inner peace.",
        "Her partnership with Sérannes remained grounded in mutual professional respect and shared passion for the blade. Together they analyzed each day's bouts, refining techniques and developing new training routines. Sérannes recognized that Julie's natural intuition and psychological mastery had surpassed his own, and he supported her artistic and martial ambitions with genuine pride and unwavering loyalty.",
        "As summer transitioned into early autumn, the golden vineyards of Aquitaine and the Garonne valley were heavy with ripe purple grapes. Traveling between provincial towns, Julie enjoyed the intoxicating beauty of the harvest season. The sweet fragrance of crushed grapes, sun-warmed earth, and wild lavender filled the air, creating a rich sensory backdrop for their journey through the French countryside.",
        "At night, after the excitement of the public exhibitions had faded, Julie would sit by the window of her inn chamber, watching the moonlight illuminate the tiled rooftops and church spires of the town. She felt a profound sense of gratitude for the freedom to live authentically and master her arts on her own terms. Breathing in the calm night air, she drifted into deep, rejuvenating sleep, safe in the fortress of her own courage."
    ]

    s[4] = [
        "A vibrant seventeenth-century fairground in Poitiers, Julie d'Aubigny in an elegant velvet doublet engaging in a fencing bout on an elevated wooden stage, crowd watching in awe, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie effortlessly disarming a boastful French nobleman with a precise parry and bind, his rapier flying into the air, sunlight glinting on polished steel, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "The dramatic and iconic moment in a town square where Julie calmly unbuttons her doublet with a confident smile, stunning the skeptical crowd into breathless silence, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "The crowd erupting in joyous applause and tossing flower bouquets onto the stage as Julie takes a gracious, regal bow, warm festive atmosphere, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie singing a lyrical French ballad on stage accompanied by a lute player, warm golden afternoon light, emotional listeners leaning forward in rapt attention, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie chatting warmly with local French artisans and wine merchants around a rustic wooden table in a sunlit tavern garden, laughing with genuine warmth, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie resting alone on a carved stone bench in a tranquil monastic cloister garden in Bordeaux, climbing roses, fountain softly splashing in the courtyard, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Sérannes and Julie reviewing fencing diagrams from an antique leather-bound treatise by the light of a brass oil lamp in a quiet study, scholarly focus, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie riding past endless sun-drenched vineyards in the Garonne valley, laden with purple grapes, warm golden autumn afternoon, gentle rolling hills, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie's tranquil inn room at night, moonlight shining through arched windows onto her folded travel clothes and polished foil, profound peaceful sleep, wide cinematic 16:9 composition, ultra-high-resolution 4K."
    ]

    # PART 5
    c[5] = [
        "Following the coastline of the sparkling Mediterranean Sea, Julie and Sérannes arrived in the grand maritime port of Marseille in sixteen hundred and eighty-nine. Marseille was a vibrant crossroads of southern culture, trade, and artistic innovation. The city had recently witnessed the establishment of its own permanent Opera Academy, founded by the visionary composer and impresario Pierre Gaultier, marking the birth of provincial opera in France.",
        "Drawn by her passion for the theater, Julie auditioned for Pierre Gaultier at the newly opened opera house near the harbor. The moment she began to sing, the impresario and his musicians were spellbound. Her voice was not the light, conventional soprano common among provincial singers, but a rich, velvety contralto of extraordinary power, depth, and emotional nuance. Gaultier immediately offered her a principal contract, christening her with the stage name that would become immortal: Mademoiselle de Maupin.",
        "Julie's debut on the Marseille operatic stage was an instantaneous and overwhelming triumph. Performing in Gaultier's productions and classical pastoral pastorales, she captivated audiences with her magnetic stage presence, flawless diction, and dramatic intensity. The wealthy merchants, naval officers, and nobility of Provence flocked to the theater, filling every tier to hear the miraculous new singer whose voice possessed the warmth of the southern sun.",
        "Life in Marseille was filled with the breathtaking beauty of the Mediterranean. Julie took lodgings overlooking the Vieux-Port, where hundreds of sailing ships, fishing boats, and royal galleys bobbed gently upon the turquoise waters. The fresh, salty sea breeze blew through her open balcony, carrying the cries of gulls and the rhythmic chanting of sailors hoisting canvas sails in the morning light.",
        "Every morning, Julie walked along the rocky coastal paths of the calanques, where limestone cliffs plunged dramatically into crystal-clear blue coves. In these secluded natural amphitheaters, with the gentle sea waves crashing softly against the rocks, she practiced her vocal projections and lung capacity. The vast open horizon inspired her artistry, filling her music with the boundless freedom of the ocean.",
        "Her theatrical colleagues embraced her with warmth and admiration. Julie formed close friendships with the musicians, costume designers, and fellow singers of the Marseille company. In the bustling dressing rooms illuminated by glowing oil lamps and mirrors framed in gilded wood, she prepared for her performances with calm focus, adjusting her elaborate Baroque gowns of silk, lace, and velvet with effortless elegance.",
        "In Marseille, Julie's romantic life also blossomed. She fell deeply in love with a beautiful young woman, the daughter of a prominent local merchant family. Their bond was characterized by profound emotional intimacy, intellectual connection, and shared appreciation for music and poetry. In the quiet evenings after performances, they walked together along the harbor promenade, watching the sunset paint the Mediterranean sky in shades of crimson, rose, and amber.",
        "However, when the young woman's conservative parents discovered the relationship, they were scandalized by its unconventional nature. Determined to separate the lovers, her family forcibly removed the young woman from Marseille and placed her behind the high stone walls of the Visitandine Convent in the neighboring city of Avignon, expecting the cloister's rigid discipline to end the affair forever.",
        "Julie was heartbroken by the sudden separation, but her indomitable spirit refused to accept defeat. Where others would have surrendered to despair, Julie began formulating a daring and ingenious plan to rescue her beloved. She knew that true love demanded courage, patience, and absolute devotion, and she resolved to follow her to Avignon at any cost, risking life and liberty for love.",
        "As night settled over the port of Marseille, the beacon of the Saint-Jean fortress cast a steady, reassuring light across the calm waters of the harbor. Julie stood on her balcony, looking north toward the distant hills of Avignon. Her heart was steady, calm, and filled with unwavering purpose. Taking a slow, deep breath, she retired to her bed, resting peacefully as she gathered her strength for the daring quest that lay ahead."
    ]

    s[5] = [
        "Panoramic view of the sun-drenched Vieux-Port of Marseille in 1689, sailing galleys in the harbor, limestone buildings, azure Mediterranean water, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie d'Aubigny auditioning before composer Pierre Gaultier inside the Marseille opera house, grand harpsichord, ornate Baroque stage, captivated expression on Gaultier's face, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie performing on the candlelit stage of the Marseille Opera as Mademoiselle Maupin, wearing an opulent Baroque stage gown, audience in tiered boxes applauding enthusiastically, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie standing on a private balcony in Marseille overlooking the bustling harbor at sunrise, gentle sea breeze stirring her dark hair, serene morning light, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie vocalizing atop a dramatic limestone cliff of the Marseille calanques, turquoise waves crashing gently against the rocks below, wide cinematic ocean view, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Backstage dressing room in the Marseille Opera, gilded mirrors, silk costumes hanging on racks, glowing tallow candles, Julie preparing for a performance with tranquil grace, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie and her beloved young woman walking hand in hand along the quiet stone promenade of Marseille harbor at sunset, vibrant crimson and amber sky, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "The sorrowful departure of the young woman in a closed carriage escorted by her strict parents, Julie watching quietly from the shadows with determined resolve, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie studying a map of the fortified city of Avignon by candlelight in her Marseille chamber, compass and parchment on table, focused strategic expression, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "The harbor of Marseille at midnight, fortress lantern casting a golden reflection on the calm sea, peaceful starry sky, deep tranquil sleep atmosphere, wide cinematic 16:9 composition, ultra-high-resolution 4K."
    ]

    return c, s

if __name__ == "__main__":
    c, s = build_p01_p05()
    w = sum(sum(len(b.split()) for b in c[p]) for p in c)
    print(f"Parts 1-5 generated: {w} words across {len(c)*10} beats (avg {w/(len(c)*10):.1f} w/b)")
