#!/usr/bin/env python3
"""
Full ~16,000-word Canonical Narrative Generator for Julie d'Aubigny (La Maupin)
15 Parts, 150 Beats (~107-112 words per beat = ~16,200 words total)
In true Milo ASMR Sleep Documentary Style.
"""

from pathlib import Path
import json

def generate_canonical_corpus():
    corpus = {}

    # --------------------------------------------------------------------------
    # PART 1: The Grand Stables of Versailles - The Riding Master's Daughter
    # --------------------------------------------------------------------------
    corpus[1] = [
        "As we begin our journey tonight, let the weight of the day gently fall away. Take a slow, deep breath, and allow your mind to wander back through the centuries to the sunlit realm of seventeenth-century France. Here, on the outskirts of Paris, the golden palace of Versailles rises like a magnificent dream of stone, glass, and gilded wrought iron. In the quiet shadow of the Grand Stables, where the morning mist still clings to the cobblestones, a young girl named Julie d'Aubigny takes her first steps into history, surrounded by the warm aroma of cedar shavings, polished leather saddles, and the steady, rhythmic breathing of royal thoroughbreds resting in their oak stalls.",
        "Julie was the daughter of Gaston d'Aubigny, a respected secretary to Louis de Lorraine, the Count d'Armagnac and Grand Écuyer of France. Raised not within the secluded boudoirs of courtly ladies, but amidst the brisk, open-air discipline of the Royal Riding Academy, Julie lived in a world of physical grace and tireless motion. Her father treated her with the same exacting standards he applied to the young aristocratic pages. From dawn until dusk, she learned to sit tall upon spirited stallions, guiding them through complex equestrian figures with effortless poise, balanced posture, and quiet, unshakeable authority.",
        "The Grand Stables of Versailles were a marvel of classical French architecture. Soaring limestone arches opened onto wide riding arenas where sunlight filtered softly through high arched windows, casting long, peaceful diagonals across the raked sand. Young Julie spent hours exploring the vast harness rooms, where rows of polished brass buckles gleamed warmly in the soft lantern light. The leather smelled rich and soothing, rubbed daily with beeswax and neat's-foot oil, creating an atmosphere of timeless order, discipline, and quiet craftsmanship that grounded her spirit in patience and focus.",
        "While other noble girls were taught the quiet arts of needlepoint and court etiquette, Julie was given a wooden training foil and placed before the palace fencing masters. Her natural speed and instincts were astonishing. Moving with the fluid agility of a hunting falcon, she learned the subtle geometry of distance, the precision of the parry, and the swift decisiveness of the thrust. The rhythmic clinking of training blades against stone walls became her childhood lullaby, a comforting cadence of balance, breath, and unwavering mental focus.",
        "In the quiet late afternoons, when the royal pages had finished their drills, Julie would climb the winding stone stairs to the upper galleries of the stables. From these high vantage points, she looked out over the vast gardens of Versailles, where fountains whispered in the cooling breeze and rows of symmetrical cypress trees stretched toward the golden horizon. Her thoughts were calm and untroubled, filled with a deep sense of freedom and an innate confidence in her own extraordinary destiny that seemed written in the stars.",
        "Gaston d'Aubigny recognized that physical strength was hollow without the cultivation of the intellect. In their private quarters above the stable courtyards, by the gentle glow of tallow candles, he tutored Julie in classical literature, Latin philosophy, and the Italian arts. Together they read the epic poetry of Tasso and Ariosto, igniting her imagination with tales of warrior maidens like Bradamante and Clorinda. The steady scratching of her quill on vellum blended with the distant hoot of an owl in the palace groves.",
        "It was also during these early Versailles years that Julie discovered the natural beauty of her singing voice. Listening to the royal choristers practicing in the palace chapel, she would softly imitate their harmonies, her rich, resonant contralto echoing through the vaulted stone hallways. The stable grooms and visiting nobles would stop in wonder, captivated by the pure, hypnotic warmth of a voice that sounded both ancient and timeless, filled with effortless power, emotional depth, and soothing melodic grace.",
        "As dusk settled over Versailles, the grooms lit iron lanterns along the stables, casting long amber beams across the courtyard pavings. The horses settled into their stalls with soft nickers of contentment, chewing on fresh mountain hay. Julie would walk quietly through the long corridors, running her hand along the polished oak partitions, feeling the serene, grounding presence of the resting animals, her heart anchored in complete peace and contentment as the palace drifted into sleep.",
        "The court of the Sun King was beginning to glitter with unprecedented splendor, yet Julie remained remarkably free from courtly vanity. She possessed a fierce, natural authenticity, preferring the crisp morning breeze and the honest steel of a training blade to the powdered wigs and whisperings of palace corridors. She walked with a natural dignity, her dark eyes reflecting an independent spirit that would soon captivate the imagination of all of France.",
        "As midnight enveloped the Grand Stables, the lanterns were extinguished one by one, leaving only the cool silver light of the stars above the palace roofs. The vast riding rings lay silent and still, resting beneath the velvet sky. Young Julie closed her eyes in her chamber, her breath slow and steady, drifting into restful slumber guided by the gentle promise of a life filled with courage, artistry, and boundless adventure."
    ]

    # --------------------------------------------------------------------------
    # PART 2: The Art of the Blade - A Maiden in Men's Doublet
    # --------------------------------------------------------------------------
    corpus[2] = [
        "As young Julie matured into adolescence, her passion for the martial arts surpassed the preliminary training available in the royal stables. Paris in the late seventeenth century was the undisputed fencing capital of the world, home to master bladesmiths and legendary Salle d'Armes where the French school of rapier and smallsword was refined into a science of deadly elegance. Recognizing her rare genius, her guardians allowed her to study under the finest fencing masters of the capital, stepping into a world where precision, balance, and unwavering focus reigned supreme.",
        "To move with complete freedom during grueling training sessions, Julie abandoned the heavy corsets and voluminous silk skirts prescribed for women of her era. Instead, she adopted the practical elegance of male attire: a tailored wool doublet, linen breeches, and soft leather riding boots. This attire not only granted her total athletic liberation, but also allowed her to navigate the bustling streets and fencing halls of Paris with effortless confidence, unburdened by the restrictive conventions of seventeenth-century society.",
        "The fencing academies of Paris were temple-like spaces of polished oak floors, mirrored walls, and racks of gleaming steel blades. Here, the air carried the faint scent of weapon oil, rosin, and fresh chalk used to mark footwork lines upon the wooden floor. Master swordsmen watched in astonishment as young Julie stepped onto the piste. Her movements were exceptionally light and deceptive, shifting from defensive parries to lightning ripostes with a fluid economy of motion that left seasoned cavaliers breathless.",
        "Julie mastered the intricate principles of the French fencing treatise: the timing of the coupe, the precision of the disengage, and the psychological mastery of distance. She learned that a duel was won not by brute force, but by profound mental stillness and the ability to anticipate an opponent's intention before their blade even began to move. In the quiet intensity of each practice bout, her mind achieved a state of serene, meditative clarity that calmed her heart and centered her breathing.",
        "Her father's patron, the Count d'Armagnac, took a keen personal interest in her development. Seeing her extraordinary charisma and intelligence, he introduced her to the elite circles of Parisian society. Yet Julie was never content to be merely an ornament of courtly salons. She sought genuine mastery in everything she pursued, whether translating Italian poetry, mastering the lute, or perfecting her lunges against the master fencing instructors of the King's Guard, proving herself equal to any nobleman.",
        "In the quiet evening hours, Julie would visit the artisan workshops along the Pont Neuf, where skilled bladesmiths forged rapiers of Toledo and Solingen steel. She would watch the glowing orange embers of the forge and listen to the rhythmic, hypnotic striking of the hammer upon the anvil. The master armorer would balance slender steel blades upon his fingertip, explaining the delicate distribution of weight that transformed a strip of forged iron into an extension of the fencer's soul and will.",
        "Julie possessed an innate physical strength and flexibility that allowed her to practice for hours without fatigue. Her training included intense calisthenics, running through the forest of Saint-Germain, and practicing precise blade drills by the flickering light of oil lamps. She developed an unshakeable core of physical resilience and self-reliance, qualities that would protect her through the turbulent adventures and dangerous encounters that lay ahead in her extraordinary life.",
        "Despite her martial prowess, Julie retained a deep love for harmony, beauty, and music. In her private lodgings overlooking the Seine, she practiced vocal scales on the harpsichord, filling the quiet Parisian evenings with the rich, soothing timbre of her contralto voice. The gentle flow of the river outside her window seemed to echo the smooth, effortless phrasing of her melodies, weaving art and martial discipline into a single harmonious spirit of rare, balanced beauty.",
        "Word of the remarkable young woman who fenced like a master and sang like an angel began to spread quietly through the salons of Paris. Young aristocrats and fencing enthusiasts sought her acquaintance, drawn by her magnetic confidence and radiant charm. Julie met their admiration with polite composure and a mischievous smile, never allowing flattery to distract her from her daily regimen of study, practice, and continuous personal growth.",
        "As night deepened over Paris, the bustle of the streets subsided into a peaceful hush. The moonlight reflected off the slow-moving waters of the Seine and cast silver patterns across the wooden floor of Julie's chamber. She wiped down her rapier blade with an oiled cloth, returned it to its leather scabbard, and prepared for rest. Breathing slowly and deeply, she let her muscles relax completely, resting in the quiet confidence of her growing strength and artistry."
    ]

    # --------------------------------------------------------------------------
    # PART 3: The Flight with Sérannes - Highwaymen and the Road South
    # --------------------------------------------------------------------------
    corpus[3] = [
        "In the year sixteen hundred and eighty-seven, at the age of fourteen, Julie was married by arrangement to Sieur de Maupin of Saint-Germain-en-Laye. Soon after the wedding, Maupin received an administrative appointment in the southern provinces, leaving his spirited young bride behind in Paris. Unwilling to accept a life of domestic confinement, Julie's path crossed with that of Sérannes, a celebrated master of arms and charismatic duelist who was forced to flee Paris after killing an opponent in an illegal duel.",
        "Without hesitation, Julie chose freedom over convention. Disguising herself in a handsome cavalier's riding coat, tricorn hat, and leather travel boots, she joined Sérannes on the post road heading south toward the sun-drenched provinces of the Midi. Riding side by side under the vast canopy of the French sky, the two swordsmen left the rigid hierarchy of Paris behind, embarking on a life of open-air adventure, independence, and shared camaraderie on the king's highway.",
        "The journey through the heart of France was a continuous tapestry of rolling hills, ancient oak forests, and picturesque rural hamlets. The steady, rhythmic clopping of horse hooves upon packed dirt roads created a soothing, hypnotic tempo that marked their progress across the provinces. By day, they traveled beneath azure skies, breathing in the fresh scents of blooming heather, damp forest moss, and warm pine needles drifting on the gentle southern breeze.",
        "When evening shadows lengthened across the countryside, Julie and Sérannes would seek shelter in rustic coaching inns and village taverns. In these warm, welcoming havens, travelers gathered around roaring stone hearths, sharing hearty meals of roasted meats, fresh bread, and local wine. Julie, accepted by all as a dashing young gentleman, charmed the innkeepers and patrons with her effortless wit, generous spirit, and captivating storytelling that brought smiles to weary faces.",
        "To finance their journey, Julie and Sérannes began offering public exhibitions of swordsmanship in village squares and market towns. They set up temporary stages in town centers, drawing enthusiastic crowds of local townsfolk, traveling merchants, and garrison soldiers. Julie's dazzling blade speed and theatrical flair turned each bout into a breathtaking display of martial artistry, earning admiring cheers and a steady stream of silver coins that sustained their travels.",
        "Along the remote mountain roads of the Massif Central, the threat of highwaymen was a constant reality for all travelers. One evening at twilight, as their carriage navigated a steep wooded pass, a band of armed brigands stepped from the shadows. Remaining calm and composed, Julie drew her rapier with lightning speed. Fighting alongside Sérannes with flawless precision, she disarmed the bandit leader in a matter of seconds, sending the rest fleeing into the forest without a single drop of blood shed.",
        "At night, when coaching inns were unavailable, the companions made camp beneath the ancient trees of the southern forests. They built small, aromatic campfires of dry oak twigs and pine cones, watching the golden sparks drift upward toward the starry sky. The crackling embers provided comforting warmth against the crisp night air, while the gentle murmur of a nearby brook lulled their tired limbs into deep relaxation and peaceful contemplation.",
        "Julie loved the simplicity of life on the open road. Wrapped in her heavy wool cloak beside the dying fire, she would gaze at the brilliant constellations wheeling slowly across the velvet night. She felt completely liberated from the superficial expectations of courtly life, discovering an unshakeable inner resilience and a profound connection to the natural rhythms of the earth that calmed her soul and clarified her purpose.",
        "During their travels, Julie never neglected her vocal training. In secluded forest glades and resonant stone ruins along the road, she would practice her operatic melodies, allowing her rich contralto voice to soar through the quiet air. The birds in the canopy would pause their songs, as if listening to the wondrous music echoing across the tranquil southern valleys with breathtaking warmth and purity.",
        "As dawn approached, the southern road was bathed in the soft rose and lavender of a new day. Julie woke refreshed and invigorated, greeting the morning breeze with a light heart and clear mind. She saddled her horse with practiced ease, ready to embrace whatever wondrous discoveries and heroic adventures awaited them on the endless, open horizon of seventeenth-century France."
    ]

    # --------------------------------------------------------------------------
    # PART 4: Duelists on the Traveling Stage - Defeating Men Across the Provinces
    # --------------------------------------------------------------------------
    corpus[4] = [
        "Arriving in the bustling provincial capitals of Poitiers and Bordeaux, Julie and Sérannes established a popular traveling exhibition that drew spectators from every level of society. Performing in spacious tavern courtyards, fairgrounds, and municipal squares, they offered thrilling displays of classical French swordsmanship, inviting any local gentleman or fencing enthusiast to test their skill against them in polite, controlled combat before cheering crowds.",
        "Julie's reputation as an unbeatable young swordsman grew rapidly throughout the region. Dressed in her tailored velvet doublet and leather fencing gauntlets, she met every challenger with graceful courtesy and unyielding technical perfection. Whether facing burly local duelists, seasoned garrison captains, or boastful young aristocrats, Julie deflected their aggressive attacks with effortless parries, disarming them with a flick of her wrist to the delighted applause of the crowd.",
        "In one famous encounter in a crowded town square, a defeated challenger, wounded in his pride, loudly proclaimed that Julie could not possibly be a young man, declaring that no youth could fence with such supernatural agility. The crowd grew quiet with anticipation. With a calm, confident smile, Julie stepped to the center of the stage, calmly unbuttoned her doublet, and revealed her true identity as a woman, silencing the skeptic and sending the crowd into thunderous, joyous cheers.",
        "Far from causing scandal, Julie's bold revelation elevated her into a celebrated provincial hero. The people admired her fearless honesty, extraordinary courage, and complete defiance of conventional limitations. Songs and poems were composed in her honor, celebrating the legendary swordswoman who could out-fence the finest duelists in the kingdom while retaining her enchanting beauty, witty charm, and regal personal dignity.",
        "Between fencing demonstrations, Julie delighted her audiences by singing classical French airs and lively folk ballads. Standing upon the wooden stage beneath the open sky, her rich contralto voice resonated with hypnotic depth and clarity. Listeners were moved to tears by the soulful warmth of her melodies, marveling that the same delicate hands that wielded the deadly rapier could evoke such profound emotional tenderness and musical grace.",
        "The provincial tour brought Julie a deep understanding of human nature. She conversed with people from all walks of life: humble peasants, skilled artisans, wealthy wine merchants, and provincial magistrates. She treated everyone with the same genuine respect and egalitarian warmth, winning the lasting affection of the common people wherever she traveled and establishing a reputation for noble generosity.",
        "In the quiet late afternoons, Julie would retreat to peaceful cloister gardens or shaded riverbanks to rest and recharge. Sitting on a sun-warmed stone bench beside climbing roses, she would clean her fencing foils and practice vocal breathing exercises. The gentle rustle of leaves in the southern breeze and the soothing trickle of nearby fountains restored her physical energy and deepened her inner peace.",
        "Her partnership with Sérannes remained grounded in mutual professional respect and shared passion for the blade. Together they analyzed each day's bouts, refining techniques and developing new training routines. Sérannes recognized that Julie's natural intuition and psychological mastery had surpassed his own, and he supported her artistic and martial ambitions with genuine pride and unwavering loyalty.",
        "As summer transitioned into early autumn, the golden vineyards of Aquitaine and the Garonne valley were heavy with ripe purple grapes. Traveling between provincial towns, Julie enjoyed the intoxicating beauty of the harvest season. The sweet fragrance of crushed grapes, sun-warmed earth, and wild lavender filled the air, creating a rich sensory backdrop for their journey through the French countryside.",
        "At night, after the excitement of the public exhibitions had faded, Julie would sit by the window of her inn chamber, watching the moonlight illuminate the tiled rooftops and church spires of the town. She felt a profound sense of gratitude for the freedom to live authentically and master her arts on her own terms. Breathing in the calm night air, she drifted into deep, rejuvenating sleep, safe in the fortress of her own courage."
    ]

    # --------------------------------------------------------------------------
    # PART 5: The Songbird of Marseille - Triumph in the Southern Sun
    # --------------------------------------------------------------------------
    corpus[5] = [
        "Following the coastline of the sparkling Mediterranean Sea, Julie and Sérannes arrived in the grand maritime port of Marseille in sixteen hundred and eighty-nine. Marseille was a vibrant crossroads of southern culture, trade, and artistic innovation. The city had recently witnessed the establishment of its own permanent Opera Academy, founded by the visionary composer and impresario Pierre Gaultier, marking the birth of provincial opera in France.",
        "Drawn by her passion for the theater, Julie auditioned for Pierre Gaultier at the newly opened opera house near the harbor. The moment she began to sing, the impresario and his musicians were spellbound. Her voice was not the light, conventional soprano common among provincial singers, but a rich, velvety contralto of extraordinary power, depth, and emotional nuance. Gaultier immediately offered her a principal contract, christening her with the stage name that would become immortal: Mademoiselle de Maupin.",
        "Julie's debut on the Marseille operatic stage was an instantaneous and overwhelming triumph. Performing in Gaultier's productions and classical pastoral pastorales, she captivated audiences with her magnetic stage presence, flawless diction, and dramatic intensity. The wealthy merchants, naval officers, and nobility of Provence flocked to the theater, filling every tier to hear the miraculous new singer whose voice possessed the warmth of the southern sun.",
        "Life in Marseille was filled with the breathtaking beauty of the Mediterranean. Julie took lodgings overlooking the Vieux-Port, where hundreds of sailing ships, fishing boats, and royal galleys bobbed gently upon the turquoise waters. The fresh, salty sea breeze blew through her open balcony, carrying the cries of gulls and the rhythmic chanting of sailors hoisting canvas sails in the morning light.",
        "Every morning, Julie walked along the rocky coastal paths of the calanques, where limestone cliffs plunged dramatically into crystal-clear blue coves. In these secluded natural amphitheaters, with the gentle sea waves crashing softly against the rocks, she practiced her vocal projections and lung capacity. The vast open horizon inspired her artistry, filling her music with the boundless freedom of the ocean.",
        "Her theatrical colleagues embraced her with warmth and admiration. Julie formed close friendships with the musicians, costume designers, and fellow singers of the Marseille company. In the bustling dressing rooms illuminated by glowing oil lamps and mirrors framed in gilded wood, she prepared for her performances with calm focus, adjusting her elaborate Baroque gowns of silk, lace, and velvet with effortless elegance.",
        "In Marseille, Julie's romantic life also blossomed. She fell deeply in love with a beautiful young woman, the daughter of a prominent local merchant family. Their bond was characterized by profound emotional intimacy, intellectual connection, and shared appreciation for music and poetry. In the quiet evenings after performances, they walked together along the harbor promenade, watching the sunset paint the Mediterranean sky in shades of crimson, rose, and amber.",
        "However, when the young woman's conservative parents discovered the relationship, they were scandalized by its unconventional nature. Determined to separate the lovers, her family forcibly removed the young woman from Marseille and placed her behind the high stone walls of the Visitandine Convent in the neighboring city of Avignon, expecting the cloister's rigid discipline to end the affair forever.",
        "Julie was heartbroken by the sudden separation, but her indomitable spirit refused to accept defeat. Where others would have surrendered to despair, Julie began formulating a daring and ingenious plan to rescue her beloved. She knew that true love demanded courage, patience, and absolute devotion, and she resolved to follow her to Avignon at any cost, risking life and liberty for love.",
        "As night settled over the port of Marseille, the beacon of the Saint-Jean fortress cast a steady, reassuring light across the calm waters of the harbor. Julie stood on her balcony, looking north toward the distant hills of Avignon. Her heart was steady, calm, and filled with unwavering purpose. Taking a slow, deep breath, she retired to her bed, resting peacefully as she gathered her strength for the daring quest that lay ahead."
    ]

    # --------------------------------------------------------------------------
    # PART 6: The Cloister of Avignon - The Midnight Fire and the Daring Escape
    # --------------------------------------------------------------------------
    corpus[6] = [
        "Traveling northwest along the winding Rhône valley, Julie arrived in the ancient, walled city of Avignon, crowned by the colossal stone arches of the Palais des Papes. Her destination was the secluded Convent of the Order of the Visitation of Holy Mary, where her beloved was confined. Recognizing that brute force could never breach the fortified convent, Julie devised a brilliant and audacious strategy that relied on wit, acting skill, and absolute nerve.",
        "Presenting herself at the heavy oak doors of the convent dressed in modest garments of sober wool and casting her eyes downward with humble reverence, Julie petitioned the Mother Superior for admission as a postulant, claiming a sudden and profound desire to renounce the worldly vanities of the stage. The abbess, impressed by the young woman's apparent piety and gentle manners, welcomed her into the community and bestowed upon her the novice's veil.",
        "Inside the cloister, Julie navigated the quiet stone corridors and shadowed cloisters with silent stealth. During daily prayers in the chapel, amidst the low chanting of Latin psalms and the sweet scent of burning frankincense, she located her beloved among the veiled novices. With a brief, reassuring glance and a whispered message during the evening procession, she let the young woman know that rescue was at hand, reigniting hope in her companion's heart.",
        "The opportunity for escape arrived unexpectedly when an elderly nun of the convent passed away from natural causes. In accordance with convent tradition, the deceased sister's body was laid out in a quiet chapel awaiting burial. Julie waited until the midnight hour, when the entire monastery was asleep. Moving silently through the darkened hallways, she respectfully carried the deceased nun's body into her lover's cell and placed it carefully upon the bed.",
        "To cover their tracks and ensure that the young woman's family would believe she had perished, Julie placed a tallow candle against the straw mattress, igniting a controlled fire in the cell. As the flames caught and smoke began to drift through the upper corridor, Julie triggered the alarm bell, creating immense confusion and panic among the waking nuns and convent guards who rushed to put out the blaze.",
        "In the chaotic commotion that ensued as sisters rushed to fetch water buckets from the courtyard well, Julie and her lover slipped through the garden cloisters unnoticed. Julie unlocked the heavy iron postern gate leading to the outer orchards with a key she had procured days earlier. Stepping out into the cool night air of Avignon, the two lovers sprinted through the dark olive groves toward the riverbank where two swift horses stood waiting.",
        "Mounting their steeds, Julie and her companion rode furiously into the night, putting miles of dark countryside between themselves and the burning convent. The rhythmic thunder of hooves against packed earth matched the exhilarating beat of their racing hearts. Behind them, the glow of the fire faded into the distance, swallowed by the vast, tranquil darkness of the Provençal countryside beneath the watchful stars.",
        "For several months, the two lovers traveled together through the countryside, disguised as young aristocratic youths. They lived in complete freedom, sharing joyful days exploring rustic mountain villages, picnicking in sunlit meadows of wild thyme, and singing together beneath the shade of ancient plane trees. It was a romantic idyll of pure happiness, forged in the fires of daring rebellion and fearless devotion.",
        "Eventually, when the young woman's homesickness grew and she chose to return safely to her family, Julie accepted her decision with characteristic grace, generosity, and loving understanding. There were no bitter recriminations, only heartfelt gratitude for the wondrous adventure they had shared and a tender farewell beneath the morning sun as their paths gently diverged.",
        "Meanwhile, the Parliament of Provence, discovering the deception at Avignon, tried Julie in absentia under her legal name, Sieur de Maupin's wife, sentencing her to death by burning for the crimes of arson, grave robbery, and kidnapping. Unfazed by the terrifying royal warrant, Julie adjusted her tricorn hat, drew her crimson cloak around her shoulders, and turned her horse north toward the ultimate destination of all French ambitions: Paris."
    ]

    # --------------------------------------------------------------------------
    # PART 7: The Road to Paris and the Duel of Count d'Albert - From Steel to Devotion
    # --------------------------------------------------------------------------
    corpus[7] = [
        "Traveling north toward the capital along the grand post roads of central France, Julie maintained her male disguise as a handsome, independent young cavalier. Carrying her beloved rapiers and a saddlebag of sheet music and classical scrolls, she navigated the kingdom with total self-assurance. Her path was one of continuous adventure, where her quick wit and master swordsmanship repeatedly proved her finest defense against the hazards of the seventeenth-century road.",
        "In a crowded coaching tavern in the historic city of Villeperdue, near Tours, Julie was taking her evening meal in the common room when a group of young aristocratic officers entered. Among them was the young, hot-tempered Count d'Albert, son of the Duke de Luynes. Misinterpreting Julie's quiet, composed demeanor for insolence, d'Albert made a provocative, insulting remark across the tavern room, demanding satisfaction in the courtyard outside.",
        "Without losing her serene composure, Julie calmly finished her wine, stood up, and followed the young nobleman into the secluded garden behind the tavern. The autumn night was clear and cool, illuminated by the bright, silvery light of a full moon. Stripping off their coats, the two duelists saluted with their rapiers, the slender steel blades whispering through the quiet night air as they crossed en garde.",
        "Count d'Albert was considered one of the finest young swordsmen in his regiment, attacking with aggressive vigor and textbook precision. Yet Julie anticipated his every movement with effortless ease. Parrying his rapid thrusts with minimal wrist movements, she executed a flawless circular bind, stepped inside his guard, and cleanly ran her blade through his right shoulder, ending the duel in seconds before any fatal harm was done.",
        "As the wounded count sank to one knee, clutching his shoulder in shock and pain, Julie immediately dropped her weapon and rushed forward to assist him. Tearing her own clean linen shirt into bandages, she expertly dressed his wound and helped his companions carry him upstairs to a private bedchamber. It was at this moment, as she leaned over him to tend his injury, that Count d'Albert realized his vanquisher was an extraordinarily beautiful young woman.",
        "Astonished and deeply humbled by her supreme martial mastery and compassionate care, Count d'Albert was entirely captivated. Over the following days, Julie remained at the inn, nursing the young officer back to health with herbal teas, clean dressings, and lively, witty conversation. What began as a duel of honor rapidly blossomed into a profound, passionate romance and an enduring bond of mutual devotion that would last their entire lives.",
        "When d'Albert was sufficiently recovered to rejoin his military regiment, the two parted with heartfelt affection and mutual promises of lifelong loyalty. Count d'Albert vowed to champion Julie's cause wherever his travels took him, declaring that she possessed the bravest heart and the noblest soul in all of France. Their friendship would remain a constant, comforting pillar throughout Julie's life in Paris.",
        "Continuing her northward journey, Julie met another celebrated traveler along the Loire valley: the charismatic actor, singer, and theater director Gabriel-Vincent Thévenard. Recognizing each other as kindred artistic spirits, they traveled together toward Paris, practicing operatic duets and theatrical scenes in their carriage as the picturesque châteaux of the Loire glided past like fairy-tale fortresses in the afternoon light.",
        "Thévenard, who possessed a magnificent baritone voice and was destined to become one of the premier stars of the Paris Opera, was awe-struck by the depth and flexibility of Julie's contralto. He encouraged her to seek an immediate audition with the Royal Academy of Music, assuring her that the Parisian public would embrace her as a sensation unlike anything the stage had ever witnessed in France.",
        "As the silhouette of Paris appeared on the horizon, bathed in the soft golden haze of late afternoon, Julie felt a surge of joyful anticipation. She was returning to the city of her youth not as a frightened fugitive, but as an accomplished artist and master of the blade, ready to conquer the grandest stage in Europe. Taking a slow, deep breath, she rode through the city gates into the dawn of her greatest triumph."
    ]

    # --------------------------------------------------------------------------
    # PART 8: The Golden Gates of the Palais-Royal - Debut as Pallas Athena
    # --------------------------------------------------------------------------
    corpus[8] = [
        "Upon her arrival in Paris in sixteen hundred and ninety, Julie faced an immediate and perilous obstacle: the death sentence issued by the Parliament of Provence for the convent fire in Avignon was still legally active. Showing her characteristic intelligence and resourcefulness, she sought out her father's former patron, Louis de Lorraine, the Count d'Armagnac. The Grand Écuyer was overjoyed to see his spirited protégée and immediately used his influence at the royal court of Versailles.",
        "Count d'Armagnac approached King Louis XIV in person, presenting Julie's extraordinary talent and recounting her adventures with sympathetic eloquence. The Sun King, who loved music, theater, and bold individuality above all else, was thoroughly amused by the tale of the swordswoman who could out-fence his officers and out-sing his choristers. With a stroke of his royal quill upon vellum, Louis XIV granted Julie a full and unconditional royal pardon, wiping away all legal charges.",
        "With her freedom secured, Julie presented herself for an audition at the Académie Royale de Musique, commonly known as the Paris Opera, located in the grand theater of the Palais-Royal. The directors, Jean-Nicolas de Francine and the resident conductors, were astonished by the power, resonance, and emotional warmth of her contralto voice. Julie was immediately engaged as a premier soloist, stepping into the royal spotlight of France's premier cultural institution.",
        "Her official Paris Opera debut took place in late sixteen hundred and ninety in the role of Pallas Athena, the Greek goddess of wisdom and war, in Jean-Baptiste Lully's celebrated lyric tragedy Cadmus et Hermione. It was a role tailor-made for Julie's unique combination of physical nobility and musical genius, allowing her to step onto the stage as both a divine warrior and a master artist before the King's court.",
        "The stage of the Palais-Royal was an architectural wonder of the Baroque era. Lit by thousands of beeswax candles in crystal chandeliers and gilded sconces, the theater featured intricate wooden machinery that allowed celestial chariots and mythological clouds to descend from the ceiling. When the heavy velvet curtain rose, revealing Julie standing in gleaming gilded armor, crested helmet, and holding a warrior's spear, the entire theater gasped in breathless awe.",
        "The moment Julie began to sing, her voice filled the grand auditorium with hypnotic majesty. Her rich, expressive lower register resonated like a warm golden bell, effortlessly soaring over the orchestra of violins, flutes, and theorboes. Her diction was crystal clear, her phrasing filled with emotional depth, and her dramatic presence radiated supreme, divine authority that captivated every listener from the royal box to the parterre.",
        "The audience—composed of the King's brother Philippe of Orléans, royal princes, foreign ambassadors, and the intellectual elite of Paris—erupted into thunderous, standing ovations at the conclusion of her performance. Flowers and laurel wreaths rained down upon the stage as the court celebrated the arrival of a supreme new theatrical star: Mademoiselle de Maupin, the toast of Paris.",
        "Critics and chroniclers of the day were unanimous in their praise. The Mercure Galant, the premier cultural journal of the realm, praised her voice as one of the most beautiful and expressive instruments in Europe, marveling at her ability to embody both fierce warrior heroism and tender feminine grace with effortless natural brilliance that set a new benchmark for French lyric theater.",
        "Despite her sudden ascension to the pinnacle of artistic fame, Julie remained completely grounded and dedicated to her craft. She spent long, peaceful mornings in the Palais-Royal rehearsal halls, working with master accompanists, refining her ornamentation, and studying new operatic scores. She viewed music as a sacred discipline of harmony and soul, an art that demanded continuous devotion and humility.",
        "As midnight fell over Paris and the great chandeliers of the Palais-Royal were slowly lowered and extinguished, Julie stood alone on the empty stage for a quiet moment of reflection. The sweet scent of snuffed beeswax candles hung in the cool air, and the auditorium rested in peaceful silence. She felt deeply grateful for the journey that had brought her to this sacred temple of art. Breathing slowly and deeply, she stepped into the night, resting in the tranquil glow of her glorious triumph."
    ]

    # --------------------------------------------------------------------------
    # PART 9: Masterpieces of Lully and Campra - Clorinda the Warrior Maiden
    # --------------------------------------------------------------------------
    corpus[9] = [
        "Throughout the sixteen hundred and nineties, Julie d'Aubigny reigned as the premier contralto of the Académie Royale de Musique, inspiring the greatest composers of the French Baroque to create groundbreaking operatic roles specifically tailored to her unique voice and dramatic genius. She performed in the classic masterpieces of Jean-Baptiste Lully and became the primary muse for the rising generation of composers led by André Campra and André Cardinal Destouches.",
        "In sixteen hundred and ninety-nine, André Campra composed his landmark opera-ballet Le Carnaval de Venise, creating a dazzling showcase for Julie's vocal agility and comedic charm. Performing in elaborate Venetian carnivalesque attire, Julie demonstrated that her artistic range spanned from profound tragic gravitas to sparkling, joyous wit, delighting audiences with her effortless charm, sparkling ornamentation, and captivating stage charisma.",
        "Her greatest and most legendary artistic triumph occurred in seventeen hundred and two, when André Campra composed the revolutionary lyric tragedy Tancrède, with a libretto by Antoine Danchet based on Tasso's Gerusalemme Liberata. Campra wrote the central starring role of Clorinda—the Saracen warrior maiden who fights in heavy armor on the battlefield while harboring a tender, tragic love for the Christian knight Tancred—specifically for Julie.",
        "Before Tancrède, French operatic tradition strictly reserved heroic leading roles for high sopranos. Campra was so inspired by the rich, velvety warmth and formidable dramatic power of Julie's contralto that he broke with decades of convention, making Clorinda the first major heroic contralto leading role in French opera history. It was a revolutionary artistic breakthrough that redefined the landscape of European vocal music forever.",
        "Julie's portrayal of Clorinda was mesmerizing. Appearing on stage in polished steel armor, flowing silk surcoats, and a silver-feathered helmet, she moved with the authentic grace and balance of a true swordswoman. During the dramatic battle scenes, her stage combat was executed with real steel blades and genuine martial precision, electrifying the audience with an intensity never before seen on the operatic stage of Paris.",
        "The climax of the opera—the famous death scene of Clorinda in Tancred's arms—moved entire audiences to tears night after night. Julie's voice softened into an exquisite, heartbreaking pianissimo, conveying the peaceful transition of the warrior soul from the fury of battle into eternal, tranquil rest. The pure, hypnotic tenderness of her singing hushed the entire auditorium into reverent, tearful silence and deep emotional release.",
        "Beyond her work with Campra, Julie created principal roles in major operas by Destouches, including Omphale in seventeen hundred and one, and performed in revivals of Lully's Armide, Isis, and Thésée. Her vocal technique was celebrated for its seamless legato, rich emotional coloring, and impeccable pitch, setting a new gold standard for vocal performance across the Continent.",
        "Offstage, Julie established a peaceful, cultured lifestyle in her Parisian apartments near the Palais-Royal. She filled her home with classical sculptures, rare books, exotic flowers, and fine instruments. In the quiet afternoons, she would host intimate musical salons for fellow artists, poets, and philosophers, creating a sanctuary of artistic fellowship and enlightened conversation that nurtured the Parisian soul.",
        "Her daily routine was characterized by rigorous vocal hygiene and physical discipline. She practiced gentle breathing exercises, drank herbal infusions of chamomile and honey, and took long, meditative walks in the Tuileries gardens. Her inner calm and professional dedication allowed her to maintain her extraordinary vocal quality through hundreds of demanding performances without vocal strain.",
        "As the evening performance drew to a close and the applause echoed into the night, Julie would sit quietly in her dressing room, letting the adrenaline of the performance softly dissolve. She breathed slowly and deeply, letting go of the characters she portrayed and returning to the serene center of her own soul. Wrapped in soft silk linens in her quiet bedchamber, she rested deeply, cradled by the timeless beauty of the music she helped create."
    ]

    # --------------------------------------------------------------------------
    # PART 10: The Masked Ball of Monsieur - A Kiss, A Challenge, and Three Rapiers
    # --------------------------------------------------------------------------
    corpus[10] = [
        "In the winter of sixteen hundred and ninety-five, one of the most glamorous and talked-about social events of the Grand Siècle took place: the Grand Royal Masked Ball hosted by Monsieur, Philippe I, Duke of Orléans, the King's brother, at the Palais-Royal. The grand ballrooms were transformed into an enchanted wonderland of mirrored galleries, thousands of glittering wax candles, and cascading garlands of winter greenery and silver ribbons that shimmered in the ambient light.",
        "Julie arrived at the masquerade dressed in the height of male aristocratic fashion: an exquisite coat of midnight-blue velvet embroidered with silver thread, silk breeches, lace cravat, and a stylish black velvet carnival mask. Moving through the glittering assembly of masked courtiers, princes, and duchesses with effortless swagger and noble poise, she was widely admired as one of the most handsome and charming young cavaliers at the ball.",
        "During the festivities, Julie became enchanted by a beautiful young noblewoman who was dancing in the central gallery. Approaching the lady with gallant charm and witty conversation, Julie danced with her through several graceful minuets. As the dance concluded near a flower-draped alcove, Julie boldly and tenderly kissed the young marquise on the lips, creating a sensational moment of delightful audacity that was witnessed by several watching courtiers.",
        "Three young aristocratic suitors, who had each been competing for the lady's favors, were deeply offended by what they perceived as an intolerable insult from an unknown young cavalier. Confronting Julie as she stepped out into the palace courtyard, the three noblemen demanded immediate satisfaction, challenging the mysterious youth to an instant duel of honor outside the palace walls.",
        "With cool, amused serenity, Julie accepted their challenge without hesitation. Rather than retreating or revealing her female identity to avoid combat, she invited all three gentlemen to follow her into the secluded gardens behind the Palais-Royal, where the snowy lawns and trimmed hedges lay quiet beneath the crisp, starlit winter sky of Paris.",
        "In the moonlit garden clearing, with the distant music of the palace violins drifting softly through the frozen air, Julie faced the first challenger. Saluting politely with her rapier, she engaged him with lightning speed. Within minutes, her flawless technique disarmed the nobleman, leaving him nursing a minor puncture wound in his sword arm as he looked on in disbelief.",
        "Without pausing to rest, Julie turned to the second challenger. Her footwork on the packed snow was immaculate, maintaining perfect balance as she parried his aggressive lunges and swiftly ran her blade through his sleeve, disarming him with effortless precision. The third nobleman, stepping forward with grim determination, met the same swift fate, his sword sent spinning into the snowy bushes by Julie's masterly circular bind.",
        "Having defeated all three noblemen in consecutive duels in less than a quarter of an hour without suffering a single scratch, Julie politely wiped her blade with her lace handkerchief, sheathed her rapier, and bowed with immaculate courtly courtesy. Leaving the three astonished and humbled gentlemen in the garden, she casually strolled back into the warm ballroom to finish her champagne and resume dancing.",
        "The news of the extraordinary triple duel spread like wildfire through the ballroom. When the court discovered that the dashing cavalier who had defeated three of the best swordsmen in the royal guard was none other than the prima donna Mademoiselle de Maupin, the ball erupted into a mix of shock, laughter, and immense admiration. Julie's legendary feat became the sensation of Paris overnight.",
        "However, dueling was strictly forbidden throughout France by the severe edicts of King Louis XIV, carrying the penalty of imprisonment or death. Recognizing that the three wounded noblemen would be forced to report the incident to the King's marshals, Julie quietly slipped away from the palace into the snowy night, seeking temporary refuge outside the capital while her friends petitioned the King for royal mercy."
    ]

    # --------------------------------------------------------------------------
    # PART 11: The Decree of the Sun King - Sovereign Grace and Dueling Laws
    # --------------------------------------------------------------------------
    corpus[11] = [
        "When report of the triple duel at the Palais-Royal reached the royal cabinet of King Louis XIV at Versailles, the King's ministers and the Grand Inquisitors demanded the immediate enforcement of the royal edicts against dueling. Dueling between noblemen was considered a direct challenge to the sovereign authority of the Crown, punishable by severe exile or execution. Yet when the King heard the full details of the encounter, his reaction was entirely unexpected.",
        "Louis XIV listened with keen amusement as his marshals described how three armed officers had been cleanly disarmed by a single young woman in velvet breeches who had then casually returned to finish her dance. With a famous display of royal wit that would echo through French legal history, the Sun King smiled and declared that his royal edict against dueling applied strictly to men, remarking that the law said nothing about duels between a woman and men. With this sovereign quip, the King dismissed all charges, granting Julie her second royal pardon.",
        "The King's clemency solidified Julie's legendary status as an icon of individual liberty and fearless independence. Throughout the salons and coffee houses of Paris, she was celebrated as a living hero who had outsmarted both the finest swordsmen of the realm and the rigid legal structures of the absolute monarchy. Her portrait was painted by court artists, depicting her with a rapier in one hand and an operatic music score in the other, celebrated as the pride of France.",
        "Despite the King's pardon, the wounded pride of the three defeated noblemen made a temporary absence from the capital prudent. Julie decided to embark on an international artistic tour, setting out northward toward the wealthy and cultured city of Brussels, the capital of the Spanish Netherlands, where grand opera was flourishing under princely patronage and enthusiastic audiences.",
        "The journey north through the flat, picturesque landscapes of Flanders was peaceful and reflective. Traveling in a comfortable private coach along canals lined with swaying poplars and historic windmills, Julie enjoyed the quiet beauty of the Low Countries. The crisp northern air and the gentle clatter of carriage wheels against brick-paved roads provided a restful interlude after the intense drama of Paris.",
        "In every Flemish town along her route—from Lille to Tournai and Mons—Julie was greeted with honors by local theater enthusiasts and municipal dignitaries who had heard of her Parisian triumphs. She attended private musical receptions, conversing in fluent French and Italian, captivating her hosts with her refined intellect, gracious manners, and captivating singing that warmed the northern halls.",
        "During the quiet evenings at roadside coaching inns, Julie spent hours reading philosophy and writing letters to her devoted friends in Paris, including Count d'Armagnac and Count d'Albert. Their letters, filled with warm affection and updates on Parisian artistic life, reassured her that her place in the hearts of the French public remained secure and beloved across the realm.",
        "Julie found deep tranquility in the simple routines of travel. She would wake early to watch the sunrise over the misty Flemish meadows, listening to the distant chimes of carillon bells from medieval belfries. The slow, harmonious rhythm of the northern countryside brought a soothing sense of renewal to her spirit, washing away all stress and fatigue.",
        "She used the travel time to study new musical styles, listening to northern vocalists and Flemish organists in ancient Gothic cathedrals. She marveled at the rich polyphony and solemn acoustic majesty of the northern churches, incorporating these sacred harmonies into her own vocal artistry and broadening her musical horizons with profound artistic depth.",
        "As the grand spires and guildhalls of Brussels appeared on the horizon, glowing softly in the late afternoon sun, Julie looked forward to conquering a new royal court. Taking a slow, deep breath, she entered the gates of Brussels with calm assurance, ready to dazzle the international aristocracy with the peerless magic of her voice and the indomitable spirit of her soul."
    ]

    # --------------------------------------------------------------------------
    # PART 12: The Grand Stage of Brussels - Defying the Prince of Bavaria
    # --------------------------------------------------------------------------
    corpus[12] = [
        "Arriving in Brussels in sixteen hundred and ninety-seven, Julie was immediately engaged as the prima donna of the Opéra du Quai au Foin, the premier theater of the Spanish Netherlands. Her arrival created an artistic sensation in the city, drawing the entire international court, including diplomats from Spain, Austria, Germany, and the Netherlands, all eager to experience the legendary voice of Paris's greatest star.",
        "Her performances in Brussels were a string of brilliant triumphs. Singing the dramatic leading roles in French and Italian operatic productions, Julie's voice resonated with unprecedented power and emotional maturity. The Brussels public was captivated by her ability to convey the deepest human passions with effortless vocal control and magnificent theatrical presence that dominated the stage.",
        "Among her most passionate admirers was Maximilian II Emanuel, the Elector of Bavaria and Governor-General of the Spanish Netherlands. A wealthy, cultured, and ambitious prince of the Holy Roman Empire, Maximilian was instantly enchanted by Julie's extraordinary beauty, wit, and musical genius. He invited her to his lavish court at the Coudenberg Palace, bestowing upon her lavish honors and royal favor.",
        "For several months, Julie and the Elector shared a whirlwind romance characterized by grand palace balls, private concerts in candlelit salons, and romantic carriage rides through the ancient Sonian Forest. Maximilian was fascinated by Julie's fierce independence and intellect, finding in her a companion unlike any conventional courtier he had ever known in European aristocracy.",
        "However, Julie was never one to submit to the possessive demands of courtly patronage. When the Elector, seeking to assert control over her artistic and personal freedom, grew jealous and temperamental, Julie promptly decided to end the relationship, valuing her personal autonomy and artistic integrity far above royal wealth and imperial luxury.",
        "In an attempt to appease her and settle their parting with aristocratic condescension, Maximilian sent his chamberlain to Julie's apartments with a magnificent velvet purse containing forty thousand French francs—a fortune equivalent to several years of an opera director's salary. The prince expected the generous gift to ensure her quiet gratitude, compliance, and silent departure.",
        "Julie's response was magnificent and unforgettable. In full view of the court chamberlain, she took the heavy purse of forty thousand francs, walked to the open door, and hurled the money onto the floor, declaring with proud defiance that she was an artist and a free woman whose heart could never be bought or sold for any sum of gold. The coins scattered across the parquet floor with a resounding, metallic clatter that stunned the courier into absolute silence.",
        "Without looking back, Julie packed her travel trunk, took her rapiers and music scores, and departed Brussels the very next morning. Her fearless rejection of the Bavarian prince's fortune became legendary throughout the courts of Europe, celebrated as a supreme declaration of female dignity, self-respect, and unyielding independence that inspired generations of artists.",
        "Traveling southward back toward France, Julie felt a profound sense of lightness and inner liberation. She had proven to herself and the world that her spirit was completely sovereign, beholden to no prince, king, or fortune. The open road welcomed her back like an old, trusted friend, its winding paths filled with the promise of true creative freedom and self-determination.",
        "As night descended over the border forests of northern France, Julie rested at a quiet village inn. The cool night air blew through the open window, carrying the sweet fragrance of apple orchards and damp forest earth. Breathing slowly and deeply, she smiled at the memory of her Brussels triumph, drifting into deep, peaceful sleep, proud of her unbroken spirit and completely at peace with her soul."
    ]

    # --------------------------------------------------------------------------
    # PART 13: Reign at the Académie Royale - The Unrivaled Star of Paris
    # --------------------------------------------------------------------------
    corpus[13] = [
        "In sixteen hundred and ninety-eight, Julie d'Aubigny returned to Paris, welcomed back by the Académie Royale de Musique and the Parisian public with ecstatic celebration. Her reputation had only grown during her absence, surrounded by the glamorous aura of her European triumphs and heroic deeds. For the next seven years, she entered the golden zenith of her artistic career, reigning as the undisputed queen of the French operatic stage.",
        "During this magnificent period, Julie formed an extraordinary artistic and personal partnership with the celebrated soprano Fanchon Moreau, one of the most beautiful and accomplished singers in France. Together, they formed the most famous vocal duo of the Baroque era, performing alongside each other in dozens of landmark operas. The contrast between Julie's deep, velvety contralto and Fanchon's luminous, soaring soprano created musical harmonies of breathtaking perfection.",
        "Their onstage chemistry in productions like Campra's Hésione, Destouches' Omphale, and Collasse's Canente was electric. Audiences marveled at the seamless blending of their voices, which sounded like two golden instruments woven together in divine harmony. Offstage, the two prima donnas shared a deep, intimate friendship, supporting each other through the grueling demands of theatrical life and celebrating their mutual triumphs with joyful sisterhood.",
        "Julie's vocal artistry reached new heights of technical refinement and expressive depth. Contemporary accounts noted that her voice possessed a rich, dark resonance that could express profound tragic sorrow, fierce warrior fury, or heartbreaking tenderness with equal ease. Composers wrote increasingly complex and virtuosic vocal lines specifically to showcase her extraordinary three-octave range and seamless coloratura.",
        "Her stage presence was regal, commanding, and mesmerizing. When Julie walked onto the stage of the Palais-Royal, she commanded the entire theater with a single glance. Her physical movements—trained in the rigorous discipline of fencing and classical horsemanship—possessed an organic grace, noble balance, and dramatic conviction that made every character she portrayed completely unforgettable to all who witnessed her.",
        "The royal court at Versailles frequently commanded private performances of Julie's operas in the royal apartments. King Louis XIV, now in the mature, dignified phase of his reign, took great delight in her singing, frequently complimenting her artistry and presenting her with generous royal pensions and personal gifts of jewelry, fine silks, and tokens of sovereign esteem.",
        "Despite her packed schedule of rehearsals and performances, Julie cultivated a serene, balanced private life in her spacious Parisian residence on the Rue de Richelieu. She created a tranquil indoor garden filled with fragrant jasmine, orange blossoms, and singing canaries, where she would spend quiet mornings reading Greek poetry, meditating, and enjoying the company of her beloved circle of artists and scholars.",
        "She was a generous and compassionate mentor to younger singers joining the Paris Opera company. Remembering her own early struggles on the provincial circuit, Julie offered encouragement, vocal guidance, and practical support to aspiring artists, earning the deep love and lifelong gratitude of an entire generation of French theatrical performers who viewed her as a protective maternal figure.",
        "In the quiet late evenings, after the final curtain had fallen and the applause of thousands had subsided, Julie loved to walk along the quays of the Seine. The cool night breeze coming off the river, the soft lapping of the dark waters against stone embankments, and the starry sky above Notre-Dame brought a profound sense of grounding, peace, and spiritual fulfillment to her heart.",
        "Returning to her home, she would sip warm milk infused with honey and cinnamon, letting the fatigue of the day melt away into pure relaxation. The city of Paris slept peacefully around her, sheltered under the quiet mantle of the night. Julie closed her eyes, breathing deeply and slowly, resting in the golden contentment of an artistic career that had fulfilled its grandest destiny."
    ]

    # --------------------------------------------------------------------------
    # PART 14: The Shadow of Grief - The Passing of Florensac and Farewell to the Stage
    # --------------------------------------------------------------------------
    corpus[14] = [
        "In the early years of the eighteenth century, amidst the ongoing triumphs of her artistic career, Julie d'Aubigny experienced the deepest, most transformative emotional chapter of her life. She met and fell profoundly in love with the Marquise de Florensac, a woman renowned throughout Paris for her extraordinary beauty, gentle wisdom, and cultured refinement. Their bond transcended all previous relationships, becoming the central anchor of Julie's emotional world.",
        "For several joyous and peaceful years, Julie and the Marquise lived together in harmonious domestic tranquility. They divided their time between an elegant Parisian residence and a picturesque country estate near the forest of Fontainebleau. Far from the demanding glare of the theatrical spotlight, Julie found in Florensac's gentle companionship a sanctuary of pure love, emotional security, and profound intellectual harmony that healed all past wounds.",
        "Their days in the country were filled with the simple, restorative pleasures of nature. Together they took long, peaceful walks through the ancient oak glades of Fontainebleau, collected wildflowers in sunlit meadows, and spent quiet evenings reading philosophy by the warmth of a stone hearth. For the first time in her turbulent, adventure-filled life, Julie felt completely settled, content, and at peace with the world.",
        "However, this idyllic happiness was tragically brief. In seventeen hundred and five, the Marquise de Florensac was struck by a sudden, fatal illness. Despite Julie's desperate vigils at her bedside and the tireless efforts of the finest royal physicians, the Marquise passed away peacefully in Julie's arms, leaving the great singer devastated by an overwhelming, inconsolable grief that shook her to the core.",
        "The loss of her beloved Florensac shattered Julie's desire for worldly fame, theatrical acclaim, and public glory. The applause of the Paris Opera, once so thrilling, now sounded empty and hollow to her grieving heart. She realized that the true wealth of life lay in the love and connection of the soul, and that with Florensac gone, her time on the mortal stage had reached its natural, dignified conclusion.",
        "In late seventeen hundred and five, at the young age of thirty-two, Julie d'Aubigny gave her final, farewell performance at the Académie Royale de Musique. The theater was packed to overflowing with courtiers, artists, and citizens who had gathered to bid farewell to their beloved prima donna. Julie sang with a transcendent, heartbreaking beauty that brought tears to the eyes of every person present in the hall.",
        "Her final aria was a masterclass in emotional vulnerability and technical perfection. Her voice, rich with the profound sorrow of real loss and the noble grace of a warrior soul, soared through the auditorium like a prayer of love and farewell. When the final note gently faded into silence, the entire theater stood in a prolonged, reverent ovation, honoring the incomparable legacy of Mademoiselle de Maupin.",
        "Following the performance, Julie quietly packed her personal belongings, distributed her theatrical costumes and jewelry to her fellow artists, and officially resigned her position at the Paris Opera. She bid a tender, affectionate farewell to her lifelong friends, including Count d'Armagnac, Count d'Albert, and Fanchon Moreau, who respected her decision with deep love and understanding.",
        "Turning her back on the wealth, glamour, and intrigue of Paris, Julie set out on a final journey southward toward the peaceful, sunlit landscapes of Provence, where she had spent the passionate days of her youth. She traveled quietly, without fanfare or disguise, seeking a tranquil sanctuary where she could mourn her beloved and find ultimate spiritual peace and healing.",
        "As the carriage rolled through the quiet autumn countryside, Julie looked back on the vast tapestry of her life with calm, philosophical acceptance. She had lived with absolute authenticity, loved without fear, and mastered both the sword and the song. Taking a slow, deep breath, she surrendered to the gentle rhythm of the road, her heart resting in the quiet sanctuary of eternal love."
    ]

    # --------------------------------------------------------------------------
    # PART 15: Midnight over Provence - Eternal Rest and the Legend of La Maupin
    # --------------------------------------------------------------------------
    corpus[15] = [
        "In the final chapter of her extraordinary journey, Julie d'Aubigny sought sanctuary in a peaceful, secluded convent nestled among the sun-drenched hills of Provence. Far from the noise and ambition of royal courts, she embraced a life of quiet contemplation, prayer, and deep spiritual rest, dedicating her remaining days to the memory of her beloved Florensac and the pursuit of inner serenity and divine grace.",
        "The Provençal convent was an oasis of ancient limestone, fragrant lavender fields, and olive groves that had stood for centuries. Here, the days passed with the gentle, unhurried rhythm of the sun and stars. Julie spent her mornings tending the monastery's medicinal herb gardens, planting rosemary, thyme, and sage by the warm morning sun, finding deep physical and mental healing in the simple touch of the earth.",
        "In the quiet afternoons, she would sit in the sun-warmed stone cloister, listening to the soothing trickle of the central courtyard fountain and the soft cooing of doves nesting in the tiled eaves. She read the mystical writings of Saint Teresa of Ávila and the philosophical treatises of the ancient Stoics, discovering that true peace lay in releasing all worldly attachments and surrendering to divine love.",
        "Her magnificent contralto voice, which had once captivated the Sun King and the aristocracy of Europe, was now raised only in the quiet chapel during morning and evening prayers. The sisters of the convent listened in breathless wonder as her voice echoed softly through the vaulted stone sanctuary, pure, gentle, and unburdened by worldly pride—a heartfelt hymn of gratitude, surrender, and eternal peace.",
        "In seventeen hundred and seven, at the age of thirty-three, Julie d'Aubigny passed away peacefully in her sleep, her spirit slipping quietly into the eternal realm. She met the end of her mortal voyage as she had lived every day of her life: with fearless courage, unshakeable dignity, and an open, loving heart, reuniting with her beloved Florensac in the boundless light of eternity.",
        "Though she was laid to rest in an unmarked grave beneath the cypress trees of Provence in accordance with monastic humility, her memory became an immortal legend that would inspire generations of artists, poets, and free spirits across the world. Théophile Gautier would immortalize her spirit in his famous nineteenth-century novel Mademoiselle de Maupin, celebrating her as the timeless symbol of absolute freedom, passion, and artistic perfection.",
        "Julie d'Aubigny lived a life of breathtaking originality, shattering every limitation of gender, class, and convention. She was a master swordswoman who never lost a duel, a supreme operatic diva who created immortal art, and a fearless lover who lived and loved with uncompromising truth. Her legacy remains a radiant beacon of courage, reminding humanity of the limitless power of the authentic soul.",
        "As midnight settles softly over the hills of Provence, the quiet landscape rests beneath a vast, protective canopy of brilliant stars. The ancient limestone cloisters, the silver olive trees, and the fragrant purple lavender fields are all bathed in the gentle, soothing glow of the moonlight. The cool night breeze whispers through the cypress boughs, carrying a message of timeless peace and eternal rest.",
        "Take a slow, deep breath, and feel the soothing tranquility of this ancient land filling your body and mind. Let go of every remaining tension, every lingering worry, and every thought of the waking world. You are completely safe, protected, and anchored in the boundless peace of the night as the earth sleeps around you.",
        "As we conclude our journey through the wondrous life of Julie d'Aubigny, allow your eyes to close gently, surrender to the warm, comforting embrace of sleep, and rest deeply in eternal peace, stillness, and sweet, restorative dreams."
    ]

    return corpus

if __name__ == "__main__":
    corpus = generate_canonical_corpus()
    total_words = 0
    for p in range(1, 16):
        part_words = sum(len(b.split()) for b in corpus[p])
        total_words += part_words
        print(f"Part {p:02d}: {len(corpus[p])} beats, {part_words} words (avg {part_words/len(corpus[p]):.1f} w/b)")
    print(f"Total Beats: {sum(len(corpus[p]) for p in range(1, 16))}")
    print(f"Total Words: {total_words}")
