"""
Canonical Narrative Script for Julie d'Aubigny (Parts 11 to 15)
50 Beats, ~5,500 Words in Milo ASMR Sleep Documentary Style
"""

PARTS_11_TO_15 = {}
SCENES_11_TO_15 = {}

# ==============================================================================
# PART 11: The Decree of the Sun King - Sovereign Grace and Dueling Laws
# ==============================================================================
PARTS_11_TO_15[11] = [
    "When report of the triple duel at the Palais-Royal reached the royal cabinet of King Louis XIV at Versailles, the King's ministers and the Grand Inquisitors demanded the immediate enforcement of the royal edicts against dueling. Dueling between noblemen was considered a direct challenge to the sovereign authority of the Crown, punishable by severe exile or execution. Yet when the King heard the full details of the encounter, his reaction was entirely unexpected, characterized by royal amusement rather than monarchical wrath.",
    "Louis XIV listened with keen amusement as his marshals described how three armed officers had been cleanly disarmed by a single young woman in velvet breeches who had then casually returned to finish her dance. With a famous display of royal wit that would echo through French legal history, the Sun King smiled and declared that his royal edict against dueling applied strictly to men, remarking that the law said nothing about duels between a woman and men. With this sovereign quip, the King dismissed all charges, granting Julie her second royal pardon.",
    "The King's clemency solidified Julie's legendary status as an icon of individual liberty and fearless independence. Throughout the salons and coffee houses of Paris, she was celebrated as a living hero who had outsmarted both the finest swordsmen of the realm and the rigid legal structures of the absolute monarchy. Her portrait was painted by court artists, depicting her with a rapier in one hand and an operatic music score in the other, celebrated as the pride of France and a living wonder of the age.",
    "Despite the King's pardon, the wounded pride of the three defeated noblemen made a temporary absence from the capital prudent. Julie decided to embark on an international artistic tour, setting out northward toward the wealthy and cultured city of Brussels, the capital of the Spanish Netherlands, where grand opera was flourishing under princely patronage and enthusiastic audiences eager for French culture.",
    "The journey north through the flat, picturesque landscapes of Flanders was peaceful and reflective. Traveling in a comfortable private coach along canals lined with swaying poplars and historic windmills, Julie enjoyed the quiet beauty of the Low Countries. The crisp northern air and the gentle clatter of carriage wheels against brick-paved roads provided a restful interlude after the intense drama and social whirl of Paris.",
    "In every Flemish town along her route—from Lille to Tournai and Mons—Julie was greeted with honors by local theater enthusiasts and municipal dignitaries who had heard of her Parisian triumphs. She attended private musical receptions, conversing in fluent French and Italian, captivating her hosts with her refined intellect, gracious manners, and captivating singing that warmed the northern halls with southern passion.",
    "During the quiet evenings at roadside coaching inns, Julie spent hours reading philosophy and writing letters to her devoted friends in Paris, including Count d'Armagnac and Count d'Albert. Their letters, filled with warm affection and updates on Parisian artistic life, reassured her that her place in the hearts of the French public remained secure and beloved across the realm, awaiting her return.",
    "Julie found deep tranquility in the simple routines of travel. She would wake early to watch the sunrise over the misty Flemish meadows, listening to the distant chimes of carillon bells from medieval belfries. The slow, harmonious rhythm of the northern countryside brought a soothing sense of renewal to her spirit, washing away all stress, fatigue, and restlessness from her mind.",
    "She used the travel time to study new musical styles, listening to northern vocalists and Flemish organists in ancient Gothic cathedrals. She marveled at the rich polyphony and solemn acoustic majesty of the northern churches, incorporating these sacred harmonies into her own vocal artistry and broadening her musical horizons with profound artistic depth and spiritual resonance.",
    "As the grand spires and guildhalls of Brussels appeared on the horizon, glowing softly in the late afternoon sun, Julie looked forward to conquering a new royal court. Taking a slow, deep breath, she entered the gates of Brussels with calm assurance, ready to dazzle the international aristocracy with the peerless magic of her voice and the indomitable spirit of her soul."
]

SCENES_11_TO_15[11] = [
    "King Louis XIV seated at his ornate writing desk in the Grand Cabinet of Versailles, smiling with regal amusement as ministers present the report of the triple duel, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Court marshals and noblemen looking on in surprise as King Louis XIV waves his hand in dismissive amusement, pardoning Mademoiselle de Maupin, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A Parisian salon buzzing with excitement as nobles and artists discuss the King's famous quip about the dueling laws, warm chandelier light, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A court painter in an airy studio finishing an elegant portrait of Julie d'Aubigny holding a rapier and an opera score, soft natural lighting, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie's private travel coach journeying along a brick-paved road in Flanders, lined with tall poplar trees and historic windmills against a vast sky, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie being welcomed with floral bouquets and respectful bows by Flemish dignitaries outside a handsome brick town hall in Tournai, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie writing letters by candlelight in a cozy Flemish inn chamber, a steaming cup of herbal tea and quill on table, tranquil domestic warmth, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A misty morning sunrise over the canals and green pastures of Flanders, cows grazing peacefully, distant Gothic church tower silhouetted against soft light, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie sitting quietly in a high-arched Gothic cathedral in Ghent, listening with reverence to the soaring harmonies of a pipe organ in the choir loft, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "The grand panorama of Brussels approaching at sunset, illuminated guildhalls of the Grand Place and towers glowing under an amber and violet sky, wide cinematic 16:9 composition, ultra-high-resolution 4K."
]

# ==============================================================================
# PART 12: The Grand Stage of Brussels - Defying the Prince of Bavaria
# ==============================================================================
PARTS_11_TO_15[12] = [
    "Arriving in Brussels in sixteen hundred and ninety-seven, Julie was immediately engaged as the prima donna of the Opéra du Quai au Foin, the premier theater of the Spanish Netherlands. Her arrival created an artistic sensation in the city, drawing the entire international court, including diplomats from Spain, Austria, Germany, and the Netherlands, all eager to experience the legendary voice of Paris's greatest star.",
    "Her performances in Brussels were a string of brilliant triumphs. Singing the dramatic leading roles in French and Italian operatic productions, Julie's voice resonated with unprecedented power and emotional maturity. The Brussels public was captivated by her ability to convey the deepest human passions with effortless vocal control and magnificent theatrical presence that dominated the stage from opening aria to final curtain.",
    "Among her most passionate admirers was Maximilian II Emanuel, the Elector of Bavaria and Governor-General of the Spanish Netherlands. A wealthy, cultured, and ambitious prince of the Holy Roman Empire, Maximilian was instantly enchanted by Julie's extraordinary beauty, wit, and musical genius. He invited her to his lavish court at the Coudenberg Palace, bestowing upon her lavish honors and royal favor.",
    "For several months, Julie and the Elector shared a whirlwind romance characterized by grand palace balls, private concerts in candlelit salons, and romantic carriage rides through the ancient Sonian Forest. Maximilian was fascinated by Julie's fierce independence and intellect, finding in her a companion unlike any conventional courtier he had ever known in European aristocracy.",
    "However, Julie was never one to submit to the possessive demands of courtly patronage. When the Elector, seeking to assert control over her artistic and personal freedom, grew jealous and temperamental, Julie promptly decided to end the relationship, valuing her personal autonomy and artistic integrity far above royal wealth and imperial luxury.",
    "In an attempt to appease her and settle their parting with aristocratic condescension, Maximilian sent his chamberlain to Julie's apartments with a magnificent velvet purse containing forty thousand French francs—a fortune equivalent to several years of an opera director's salary. The prince expected the generous gift to ensure her quiet gratitude, compliance, and silent departure from Brussels.",
    "Julie's response was magnificent and unforgettable. In full view of the court chamberlain, she took the heavy purse of forty thousand francs, walked to the open door, and hurled the money onto the floor, declaring with proud defiance that she was an artist and a free woman whose heart could never be bought or sold for any sum of gold. The coins scattered across the parquet floor with a resounding, metallic clatter that stunned the courier into absolute silence.",
    "Without looking back, Julie packed her travel trunk, took her rapiers and music scores, and departed Brussels the very next morning. Her fearless rejection of the Bavarian prince's fortune became legendary throughout the courts of Europe, celebrated as a supreme declaration of female dignity, self-respect, and unyielding independence that inspired generations of artists.",
    "Traveling southward back toward France, Julie felt a profound sense of lightness and inner liberation. She had proven to herself and the world that her spirit was completely sovereign, beholden to no prince, king, or fortune. The open road welcomed her back like an old, trusted friend, its winding paths filled with the promise of true creative freedom and self-determination.",
    "As night descended over the border forests of northern France, Julie rested at a quiet village inn. The cool night air blew through the open window, carrying the sweet fragrance of apple orchards and damp forest earth. Breathing slowly and deeply, she smiled at the memory of her Brussels triumph, drifting into deep, peaceful sleep, proud of her unbroken spirit and completely at peace with her soul."
]

SCENES_11_TO_15[12] = [
    "The opulent Baroque auditorium of the Opéra du Quai au Foin in Brussels, Julie performing on a lavish candlelit stage before the international nobility, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Maximilian II Emanuel, Elector of Bavaria, watching Julie from the gilded royal box with an expression of intense admiration and enchantment, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A grand reception in the mirrored salon of the Coudenberg Palace in Brussels, Julie conversing with European diplomats with sparkling intelligence, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie and the Elector Maximilian riding in an open royal carriage through the majestic, sun-dappled Sonian Forest, ancient beech trees towering above, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie in her Brussels salon, standing with dignified resolve as she announces her decision to end the relationship with the Elector, quiet strength, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "The court chamberlain offering a velvet purse filled with gold coins to Julie in her luxurious Brussels apartment, tense aristocratic encounter, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "The legendary moment of defiance: Julie boldly hurling the heavy purse of 40,000 francs onto the floor, gold coins scattering across the polished parquet floor, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie packing her leather travel trunk with music scores and sheathing her rapiers in the early morning light, composed and unbothered, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie's travel coach crossing the misty border into France at sunrise, dew sparkling on green pastures, the open road stretching forward in freedom, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A peaceful village coaching inn in northern France at midnight, warm candlelight illuminating Julie's sleeping chamber, profound tranquil rest, wide cinematic 16:9 composition, ultra-high-resolution 4K."
]

# ==============================================================================
# PART 13: Reign at the Académie Royale - The Unrivaled Star of Paris
# ==============================================================================
PARTS_11_TO_15[13] = [
    "In sixteen hundred and ninety-eight, Julie d'Aubigny returned to Paris, welcomed back by the Académie Royale de Musique and the Parisian public with ecstatic celebration. Her reputation had only grown during her absence, surrounded by the glamorous aura of her European triumphs and heroic deeds. For the next seven years, she entered the golden zenith of her artistic career, reigning as the undisputed queen of the French operatic stage.",
    "During this magnificent period, Julie formed an extraordinary artistic and personal partnership with the celebrated soprano Fanchon Moreau, one of the most beautiful and accomplished singers in France. Together, they formed the most famous vocal duo of the Baroque era, performing alongside each other in dozens of landmark operas. The contrast between Julie's deep, velvety contralto and Fanchon's luminous, soaring soprano created musical harmonies of breathtaking perfection.",
    "Their onstage chemistry in productions like Campra's Hésione, Destouches' Omphale, and Collasse's Canente was electric. Audiences marveled at the seamless blending of their voices, which sounded like two golden instruments woven together in divine harmony. Offstage, the two prima donnas shared a deep, intimate friendship, supporting each other through the grueling demands of theatrical life and celebrating their mutual triumphs with joyful sisterhood.",
    "Julie's vocal artistry reached new heights of technical refinement and expressive depth. Contemporary accounts noted that her voice possessed a rich, dark resonance that could express profound tragic sorrow, fierce warrior fury, or heartbreaking tenderness with equal ease. Composers wrote increasingly complex and virtuosic vocal lines specifically to showcase her extraordinary three-octave range and seamless coloratura.",
    "Her stage presence was regal, commanding, and mesmerizing. When Julie walked onto the stage of the Palais-Royal, she commanded the entire theater with a single glance. Her physical movements—trained in the rigorous discipline of fencing and classical horsemanship—possessed an organic grace, noble balance, and dramatic conviction that made every character she portrayed completely unforgettable to all who witnessed her.",
    "The royal court at Versailles frequently commanded private performances of Julie's operas in the royal apartments. King Louis XIV, now in the mature, dignified phase of his reign, took great delight in her singing, frequently complimenting her artistry and presenting her with generous royal pensions and personal gifts of jewelry, fine silks, and tokens of sovereign esteem.",
    "Despite her packed schedule of rehearsals and performances, Julie cultivated a serene, balanced private life in her spacious Parisian residence on the Rue de Richelieu. She created a tranquil indoor garden filled with fragrant jasmine, orange blossoms, and singing canaries, where she would spend quiet mornings reading Greek poetry, meditating, and enjoying the company of her beloved circle of artists and scholars.",
    "She was a generous and compassionate mentor to younger singers joining the Paris Opera company. Remembering her own early struggles on the provincial circuit, Julie offered encouragement, vocal guidance, and practical support to aspiring artists, earning the deep love and lifelong gratitude of an entire generation of French theatrical performers who viewed her as a protective maternal figure.",
    "In the quiet late evenings, after the final curtain had fallen and the applause of thousands had subsided, Julie loved to walk along the quays of the Seine. The cool night breeze coming off the river, the soft lapping of the dark waters against stone embankments, and the starry sky above Notre-Dame brought a profound sense of grounding, peace, and spiritual fulfillment to her heart.",
    "Returning to her home, she would sip warm milk infused with honey and cinnamon, letting the fatigue of the day melt away into pure relaxation. The city of Paris slept peacefully around her, sheltered under the quiet mantle of the night. Julie closed her eyes, breathing deeply and slowly, resting in the golden contentment of an artistic career that had fulfilled its grandest destiny."
]

SCENES_11_TO_15[13] = [
    "The grand entrance of the Palais-Royal opera house illuminated by hundreds of lanterns, carriage arrivals and crowds eager to welcome back Mademoiselle de Maupin, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie d'Aubigny and soprano Fanchon Moreau singing an exquisite operatic duet on the Baroque stage, their contrasting voices blending in sublime harmony, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Backstage green room of the Paris Opera, Julie and Fanchon Moreau laughing together in lavish costumes while sipping fruit cordial, sisterly bond, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie performing a dramatic solo aria in Campra's Hésione, her dark eyes flashing with emotional intensity, stage bathed in warm candlelight and amber glow, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A private command performance in the King's Grand Chamber at Versailles, Louis XIV and courtiers listening in rapt silence to Julie's velvety contralto, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie in her serene Parisian indoor conservatory on the Rue de Richelieu, surrounded by blooming orange trees and jasmine, reading poetry by morning sunlight, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie gently coaching a nervous young soprano in a sunny rehearsal room, demonstrating a vocal ornamentation with patient warmth and generosity, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie walking along the stone quays of the Seine at night, the silhouette of Notre-Dame Cathedral rising against a star-filled velvet sky, peaceful river breeze, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Close-up of a royal jewelry box presented by Louis XIV, containing an emerald brooch and gold pendant resting on white silk, soft ambient glow, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie resting in her peaceful bedchamber, surrounded by bouquets of roses from admirers, drifting into deep, restorative sleep in complete artistic fulfillment, wide cinematic 16:9 composition, ultra-high-resolution 4K."
]

# ==============================================================================
# PART 14: The Shadow of Grief - The Passing of Florensac and Farewell to the Stage
# ==============================================================================
PARTS_11_TO_15[14] = [
    "In the early years of the eighteenth century, amidst the ongoing triumphs of her artistic career, Julie d'Aubigny experienced the deepest, most transformative emotional chapter of her life. She met and fell profoundly in love with the Marquise de Florensac, a woman renowned throughout Paris for her extraordinary beauty, gentle wisdom, and cultured refinement. Their bond transcended all previous relationships, becoming the central anchor of Julie's emotional world.",
    "For several joyous and peaceful years, Julie and the Marquise lived together in harmonious domestic tranquility. They divided their time between an elegant Parisian residence and a picturesque country estate near the forest of Fontainebleau. Far from the demanding glare of the theatrical spotlight, Julie found in Florensac's gentle companionship a sanctuary of pure love, emotional security, and profound intellectual harmony that healed all past wounds.",
    "Their days in the country were filled with the simple, restorative pleasures of nature. Together they took long, peaceful walks through the ancient oak glades of Fontainebleau, collected wildflowers in sunlit meadows, and spent quiet evenings reading philosophy by the warmth of a stone hearth. For the first time in her turbulent, adventure-filled life, Julie felt completely settled, content, and at peace with the world.",
    "However, this idyllic happiness was tragically brief. In seventeen hundred and five, the Marquise de Florensac was struck by a sudden, fatal illness. Despite Julie's desperate vigils at her bedside and the tireless efforts of the finest royal physicians, the Marquise passed away peacefully in Julie's arms, leaving the great singer devastated by an overwhelming, inconsolable grief that shook her to the core.",
    "The loss of her beloved Florensac shattered Julie's desire for worldly fame, theatrical acclaim, and public glory. The applause of the Paris Opera, once so thrilling, now sounded empty and hollow to her grieving heart. She realized that the true wealth of life lay in the love and connection of the soul, and that with Florensac gone, her time on the mortal stage had reached its natural, dignified conclusion.",
    "In late seventeen hundred and five, at the young age of thirty-two, Julie d'Aubigny gave her final, farewell performance at the Académie Royale de Musique. The theater was packed to overflowing with courtiers, artists, and citizens who had gathered to bid farewell to their beloved prima donna. Julie sang with a transcendent, heartbreaking beauty that brought tears to the eyes of every person present in the hall.",
    "Her final aria was a masterclass in emotional vulnerability and technical perfection. Her voice, rich with the profound sorrow of real loss and the noble grace of a warrior soul, soared through the auditorium like a prayer of love and farewell. When the final note gently faded into silence, the entire theater stood in a prolonged, reverent ovation, honoring the incomparable legacy of Mademoiselle de Maupin.",
    "Following the performance, Julie quietly packed her personal belongings, distributed her theatrical costumes and jewelry to her fellow artists, and officially resigned her position at the Paris Opera. She bid a tender, affectionate farewell to her lifelong friends, including Count d'Armagnac, Count d'Albert, and Fanchon Moreau, who respected her decision with deep love and understanding.",
    "Turning her back on the wealth, glamour, and intrigue of Paris, Julie set out on a final journey southward toward the peaceful, sunlit landscapes of Provence, where she had spent the passionate days of her youth. She traveled quietly, without fanfare or disguise, seeking a tranquil sanctuary where she could mourn her beloved and find ultimate spiritual peace and healing.",
    "As the carriage rolled through the quiet autumn countryside, Julie looked back on the vast tapestry of her life with calm, philosophical acceptance. She had lived with absolute authenticity, loved without fear, and mastered both the sword and the song. Taking a slow, deep breath, she surrendered to the gentle rhythm of the road, her heart resting in the quiet sanctuary of eternal love."
]

SCENES_11_TO_15[14] = [
    "Julie d'Aubigny and the gentle Marquise de Florensac sitting together in a sunlit garden near Fontainebleau, surrounded by white roses and climbing ivy, serene affection, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie and Florensac walking peacefully beneath the towering canopy of the ancient forest of Fontainebleau at golden hour, autumn leaves falling softly around them, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie keeping a sorrowful, loving vigil by the bedside of the ill Marquise de Florensac in a quiet country manor, soft candlelight illuminating her grieving face, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie standing alone at twilight beside a stone memorial in a quiet garden, holding a single white rose, deep contemplative sorrow, mist rising from grass, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie standing on the stage of the Palais-Royal for her historic final farewell performance in 1705, looking out at the packed, tearful audience with serene dignity, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "The emotional final bow of Mademoiselle de Maupin, arms crossed over her heart in gratitude as bouquets of flowers cover the stage, grand theatrical farewell, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie in her dressing room for the last time, gifting her elaborate stage gowns and jewelry to younger singers who embrace her in heartfelt gratitude, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie embracing her lifelong friends Count d'Albert and Count d'Armagnac in a tender courtyard farewell before her departure from Paris, warm morning sun, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie's lone carriage traveling along a peaceful southern road through the rolling hills of Provence, bathed in the warm, golden light of early autumn, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie resting in the carriage as the sun sets over the lavender fields of the south, a soft, peaceful smile of acceptance on her face, tranquil sleep, wide cinematic 16:9 composition, ultra-high-resolution 4K."
]

# ==============================================================================
# PART 15: Midnight over Provence - Eternal Rest and the Legend of La Maupin
# ==============================================================================
PARTS_11_TO_15[15] = [
    "In the final chapter of her extraordinary journey, Julie d'Aubigny sought sanctuary in a peaceful, secluded convent nestled among the sun-drenched hills of Provence. Far from the noise and ambition of royal courts, she embraced a life of quiet contemplation, prayer, and deep spiritual rest, dedicating her remaining days to the memory of her beloved Florensac and the pursuit of inner serenity and divine grace.",
    "The Provençal convent was an oasis of ancient limestone, fragrant lavender fields, and olive groves that had stood for centuries. Here, the days passed with the gentle, unhurried rhythm of the sun and stars. Julie spent her mornings tending the monastery's medicinal herb gardens, planting rosemary, thyme, and sage by the warm morning sun, finding deep physical and mental healing in the simple touch of the earth.",
    "In the quiet afternoons, she would sit in the sun-warmed stone cloister, listening to the soothing trickle of the central courtyard fountain and the soft cooing of doves nesting in the tiled eaves. She read the mystical writings of Saint Teresa of Ávila and the philosophical treatises of the ancient Stoics, discovering that true peace lay in releasing all worldly attachments and surrendering to divine love.",
    "Her magnificent contralto voice, which had once captivated the Sun King and the aristocracy of Europe, was now raised only in the quiet chapel during morning and evening prayers. The sisters of the convent listened in breathless wonder as her voice echoed softly through the vaulted stone sanctuary, pure, gentle, and unburdened by worldly pride—a heartfelt hymn of gratitude, surrender, and eternal peace.",
    "In seventeen hundred and seven, at the age of thirty-three, Julie d'Aubigny passed away peacefully in her sleep, her spirit slipping quietly into the eternal realm. She met the end of her mortal voyage as she had lived every day of her life: with fearless courage, unshakeable dignity, and an open, loving heart, reuniting with her beloved Florensac in the boundless light of eternity.",
    "Though she was laid to rest in an unmarked grave beneath the cypress trees of Provence in accordance with monastic humility, her memory became an immortal legend that would inspire generations of artists, poets, and free spirits across the world. Théophile Gautier would immortalize her spirit in his famous nineteenth-century novel Mademoiselle de Maupin, celebrating her as the timeless symbol of absolute freedom, passion, and artistic perfection.",
    "Julie d'Aubigny lived a life of breathtaking originality, shattering every limitation of gender, class, and convention. She was a master swordswoman who never lost a duel, a supreme operatic diva who created immortal art, and a fearless lover who lived and loved with uncompromising truth. Her legacy remains a radiant beacon of courage, reminding humanity of the limitless power of the authentic soul.",
    "As midnight settles softly over the hills of Provence, the quiet landscape rests beneath a vast, protective canopy of brilliant stars. The ancient limestone cloisters, the silver olive trees, and the fragrant purple lavender fields are all bathed in the gentle, soothing glow of the moonlight. The cool night breeze whispers through the cypress boughs, carrying a message of timeless peace and eternal rest.",
    "The roar of Parisian theaters and royal palaces softens to a distant murmur, like the sound of a seashell held to your ear. The bright, analytical parts of your mind can rest now. The dates, the names, the duels... you can let them all drift away like wisps of evening smoke. There are no more challenges to meet, no more stages to conquer. There is only the stillness of this moment, here in the soft, protective darkness. Her work is done, but the melody continues, echoing in the quiet spaces of eternity.",
    "Your own dreams are waiting for you now, in that gentle space just beyond wakefulness. So let your breathing slow... let your thoughts soften... and just... drift. End of script. Sweet dreams. Everything in this tranquil moment speaks of endurance, courage, and the gentle rhythm of the cosmos, guiding your spirit toward a state of profound, restorative, and eternal peace."
]

SCENES_11_TO_15[15] = [
    "A peaceful seventeenth-century stone convent nestled among the sunny rolling hills and lavender fields of Provence, ancient cypress trees, warm natural light, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie d'Aubigny in simple linen garments tending a fragrant herb garden in the convent courtyard, morning sunlight illuminating rosemary and lavender blossoms, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie sitting on a weathered stone bench in the shaded monastery cloister, reading a small vellum book as water trickles gently from a central fountain, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie singing softly in the sunlit convent chapel during quiet afternoon prayers, dust motes floating in sunbeams through high stained glass, ethereal peace, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Julie reclining peacefully in her simple, clean convent cell at sunset, a serene, radiant smile on her face as she drifts into eternal restful slumber, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A quiet stone cloister garden at dawn, cypress trees silhouetted against a soft pastel sky, morning dew on olive leaves, atmosphere of sacred peace, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "A nineteenth-century vintage leather-bound book titled Mademoiselle de Maupin by Théophile Gautier, illuminated by warm library candlelight, timeless literary legacy, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Panoramic view of the Provence countryside at midnight under a vast, brilliant blanket of twinkling stars, rolling hills resting in pure silence, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "Close-up of fragrant purple lavender blowing gently in the cool midnight breeze beneath silver moonlight, hypnotic soothing motion, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
    "The starry night sky over the quiet hills of Provence, crescent moon shining softly, profound tranquility, deep restorative sleep and sweet dreams, wide cinematic 16:9 composition, ultra-high-resolution 4K."
]
