"""
Parts 06 to 10 of the Canonical Julie d'Aubigny Documentary Script
50 Paragraphs / Beats in Milo ASMR Sleep Documentary Style (~5,400 words)
"""

PARTS_06_TO_10 = {}
SCENES_06_TO_10 = {}

# ==============================================================================
# PART 06: The Cloister of Avignon - The Midnight Fire and the Daring Escape
# ==============================================================================
PARTS_06_TO_10[6] = [
    "Traveling northwest along the winding Rhône valley, Julie arrived in the ancient, walled city of Avignon, crowned by the colossal stone arches of the Palais des Papes. Her destination was the secluded Convent of the Order of the Visitation of Holy Mary, where her beloved was confined behind heavy oak gates. Recognizing that brute force could never breach the fortified convent walls without causing fatal harm, Julie devised a brilliant, audacious strategy that relied entirely on psychological insight, theatrical acting skill, and absolute nerve.",
    "Presenting herself at the heavy oak doors of the convent dressed in modest garments of sober wool and casting her dark eyes downward with humble reverence, Julie petitioned the Mother Superior for admission as a postulant. She claimed a sudden, profound desire to renounce the worldly vanities of the stage and dedicate her soul to quiet monastic prayer. The abbess, deeply impressed by the young woman's apparent piety, modest demeanor, and gentle manners, welcomed her into the sisterhood and bestowed upon her the novice's white veil.",
    "Inside the cloister, Julie navigated the quiet stone corridors and shadowed arcades with silent stealth. During daily prayers in the chapel, amidst the low, hypnotic chanting of Latin psalms and the sweet scent of burning frankincense drifting from bronze censers, she located her beloved among the veiled novices. With a brief, reassuring glance and a whispered message during the evening procession, she let the young woman know that rescue was at hand, reigniting hope in her companion's heart.",
    "The opportunity for a flawless escape arrived unexpectedly when an elderly nun of the convent passed away from natural causes. In accordance with convent tradition, the deceased sister's body was laid out in a quiet side chapel awaiting formal burial. Julie waited patiently until the midnight hour, when the entire monastery was deep in peaceful slumber. Moving silently through the darkened stone hallways, she respectfully carried the deceased nun's body into her lover's cell and placed it carefully upon the bed.",
    "To cover their tracks and ensure that the young woman's family and the authorities would believe she had tragically perished in an accidental blaze, Julie placed a tallow candle against the straw mattress, igniting a controlled fire in the cell. As the flames caught and pungent woodsmoke began to drift through the upper corridor, Julie triggered the bronze alarm bell, creating immense confusion and panic among the waking nuns and convent guards who rushed to put out the blaze.",
    "In the chaotic commotion that ensued as sisters rushed to fetch wooden water buckets from the courtyard well, Julie and her lover slipped through the garden cloisters completely unnoticed. Julie unlocked the heavy iron postern gate leading to the outer orchards with a key she had secretly procured days earlier. Stepping out into the cool night air of Avignon, the two lovers sprinted through the dark olive groves toward the riverbank where two swift horses stood waiting in the shadows.",
    "Mounting their steeds, Julie and her companion rode furiously into the night, putting miles of dark countryside between themselves and the burning convent. The rhythmic, powerful thunder of hooves against packed earth matched the exhilarating beat of their racing hearts. Behind them, the orange glow of the fire faded into the distance, swallowed by the vast, tranquil darkness of the Provençal countryside beneath the watchful canopy of stars.",
    "For several months, the two lovers traveled together through the countryside, disguised as young aristocratic youths. They lived in complete freedom, sharing joyful days exploring rustic mountain villages, picnicking in sunlit meadows of wild thyme, and singing together beneath the shade of ancient plane trees. It was a romantic idyll of pure happiness, forged in the fires of daring rebellion and fearless devotion that neither would ever forget.",
    "Eventually, when the young woman's homesickness grew and she chose to return safely to her family, Julie accepted her decision with characteristic grace, generosity, and loving understanding. There were no bitter recriminations, only heartfelt gratitude for the wondrous adventure they had shared and a tender farewell beneath the morning sun as their paths gently and peacefully diverged across the French landscape.",
    "Meanwhile, the Parliament of Provence, discovering the daring deception at Avignon, tried Julie in absentia under her legal name, Sieur de Maupin's wife, sentencing her to death by burning for the crimes of arson, grave robbery, and kidnapping. Unfazed by the terrifying royal warrant, Julie adjusted her tricorn hat, drew her crimson cloak around her shoulders, and turned her horse north toward the ultimate destination of all French ambitions: Paris."
]

SCENES_06_TO_10[6] = [
    "The imposing fortified walls and towers of Avignon at twilight, the Rhône river flowing beneath the famous broken stone bridge of Pont Saint-Bénézet.",
    "Julie d'Aubigny in humble novice robes kneeling before the Mother Superior at the heavy oak entrance of the Visitandine Convent, soft daylight filtering through iron grates.",
    "Julie and her veiled lover exchanging a discreet, meaningful glance inside the candlelit stone chapel during evening vespers, nuns singing in choir stalls.",
    "Julie silently carrying the draped deceased nun through the dark stone cloister arcade at midnight, shadows and moonlight dancing on stone pillars.",
    "A small flame catching on straw in the convent cell by the light of a single tallow candle, casting dramatic orange shadows against whitewashed stone walls.",
    "Nuns in panic ringing the bronze convent bell and rushing with wooden water buckets as smoke billows from an upper window into the night sky.",
    "Julie and her lover slipping through the iron postern gate of the convent garden into the moonlit olive orchard, adrenaline and relief.",
    "Two cloaked riders galloping on horseback across the starlit landscape of Provence at full speed, wind whipping through their cloaks, dark mountains in background.",
    "Julie and her companion resting peacefully in a sun-drenched meadow of flowering lavender and wild thyme, smiling together in warm afternoon sunlight.",
    "A parchment royal death warrant with official red wax seals posted on a stone wall, Julie riding past on horseback in the distance with fearless poise."
]

# ==============================================================================
# PART 07: The Road to Paris and the Duel of Count d'Albert - From Steel to Devotion
# ==============================================================================
PARTS_06_TO_10[7] = [
    "Traveling north toward the capital along the grand post roads of central France, Julie maintained her male disguise as a handsome, independent young cavalier. Carrying her beloved rapiers and a saddlebag of sheet music and classical scrolls, she navigated the kingdom with total self-assurance. Her path was one of continuous adventure, where her quick wit and master swordsmanship repeatedly proved her finest defense against the hazards of the seventeenth-century road.",
    "In a crowded coaching tavern in the historic city of Villeperdue, near Tours, Julie was taking her evening meal in the common room when a group of young aristocratic officers entered. Among them was the young, hot-tempered Count d'Albert, son of the Duke de Luynes. Misinterpreting Julie's quiet, composed demeanor for insolence, d'Albert made a provocative, insulting remark across the tavern room, demanding immediate satisfaction in the courtyard outside.",
    "Without losing her serene composure, Julie calmly finished her wine, stood up, and followed the young nobleman into the secluded garden behind the tavern. The autumn night was clear and cool, illuminated by the bright, silvery light of a full moon. Stripping off their heavy coats, the two duelists saluted with their rapiers, the slender steel blades whispering through the quiet night air as they crossed en garde on the grass.",
    "Count d'Albert was considered one of the finest young swordsmen in his regiment, attacking with aggressive vigor and textbook precision. Yet Julie anticipated his every movement with effortless ease. Parrying his rapid thrusts with minimal wrist movements, she executed a flawless circular bind, stepped inside his guard, and cleanly ran her blade through his right shoulder, ending the duel in seconds before any fatal harm was done.",
    "As the wounded count sank to one knee, clutching his shoulder in shock and pain, Julie immediately dropped her weapon and rushed forward to assist him. Tearing her own clean linen shirt into bandages, she expertly dressed his wound and helped his companions carry him upstairs to a private bedchamber. It was at this moment, as she leaned over him to tend his injury, that Count d'Albert realized his vanquisher was an extraordinarily beautiful young woman.",
    "Astonished and deeply humbled by her supreme martial mastery and compassionate care, Count d'Albert was entirely captivated. Over the following days, Julie remained at the inn, nursing the young officer back to health with herbal teas, clean dressings, and lively, witty conversation. What began as a duel of honor rapidly blossomed into a profound, passionate romance and an enduring bond of mutual devotion that would last their entire lives.",
    "When d'Albert was sufficiently recovered to rejoin his military regiment, the two parted with heartfelt affection and mutual promises of lifelong loyalty. Count d'Albert vowed to champion Julie's cause wherever his travels took him, declaring that she possessed the bravest heart and the noblest soul in all of France. Their friendship would remain a constant, comforting pillar throughout Julie's life in Paris.",
    "Continuing her northward journey, Julie met another celebrated traveler along the Loire valley: the charismatic actor, singer, and theater director Gabriel-Vincent Thévenard. Recognizing each other as kindred artistic spirits, they traveled together toward Paris, practicing operatic duets and theatrical scenes in their carriage as the picturesque châteaux of the Loire glided past like fairy-tale fortresses in the afternoon light.",
    "Thévenard, who possessed a magnificent baritone voice and was destined to become one of the premier stars of the Paris Opera, was awe-struck by the depth and flexibility of Julie's contralto. He encouraged her to seek an immediate audition with the Royal Academy of Music, assuring her that the Parisian public would embrace her as a sensation unlike anything the stage had ever witnessed in France.",
    "As the silhouette of Paris appeared on the horizon, bathed in the soft golden haze of late afternoon, Julie felt a surge of joyful anticipation. She was returning to the city of her youth not as a frightened fugitive, but as an accomplished artist and master of the blade, ready to conquer the grandest stage in Europe. Taking a slow, deep breath, she rode through the city gates into the dawn of her greatest triumph."
]

SCENES_06_TO_10[7] = [
    "Julie d'Aubigny in an elegant cavalier riding coat dining peacefully at a candlelit wooden table in a busy seventeenth-century French coaching tavern.",
    "The heated confrontation inside the tavern as the young Count d'Albert loudly challenges Julie, patrons looking on with tense curiosity, warm lantern light.",
    "Julie and Count d'Albert crossing rapiers in the moonlit garden behind the tavern, silver blades clashing in the cool night air, tall stone walls in background.",
    "Julie executing a brilliant parry and thrust, wounding d'Albert's shoulder with precision, rapier glinting in the moonlight, dramatic athletic composition.",
    "Julie kneeling beside the wounded Count d'Albert, bandaging his shoulder with a torn linen sash, compassionate tenderness in her eyes, d'Albert looking at her in amazement.",
    "Julie reading a poetry book beside d'Albert's bedside in a sunlit inn chamber as he rests and recovers, warm domestic tranquility.",
    "Julie and Count d'Albert exchanging a tender farewell at the inn courtyard as he mounts his horse, mutual devotion, morning sunlight on stone archway.",
    "Julie and singer Gabriel-Vincent Thévenard rehearsing an operatic duet inside a moving horse-drawn carriage, picturesque Loire valley châteaux visible through window.",
    "A roadside stop along the Loire River at sunset, Julie and Thévenard reviewing musical scores spread on a carriage trunk by the water's edge.",
    "The grand stone gates of Paris at golden hour, carriages and travelers entering the capital, Julie riding proudly through the portal, hopeful new dawn."
]

# ==============================================================================
# PART 08: The Golden Gates of the Palais-Royal - Debut as Pallas Athena
# ==============================================================================
PARTS_06_TO_10[8] = [
    "Upon her arrival in Paris in sixteen hundred and ninety, Julie faced an immediate and perilous obstacle: the death sentence issued by the Parliament of Provence for the convent fire in Avignon was still legally active. Showing her characteristic intelligence and resourcefulness, she sought out her father's former patron, Louis de Lorraine, the Count d'Armagnac. The Grand Écuyer was overjoyed to see his spirited protégée and immediately used his influence at the royal court of Versailles.",
    "Count d'Armagnac approached King Louis XIV in person, presenting Julie's extraordinary talent and recounting her adventures with sympathetic eloquence. The Sun King, who loved music, theater, and bold individuality above all else, was thoroughly amused by the tale of the swordswoman who could out-fence his officers and out-sing his choristers. With a stroke of his royal quill upon vellum, Louis XIV granted Julie a full and unconditional royal pardon, wiping away all legal charges.",
    "With her freedom secured, Julie presented herself for an audition at the Académie Royale de Musique, commonly known as the Paris Opera, located in the grand theater of the Palais-Royal. The directors, Jean-Nicolas de Francine and the resident conductors, were astonished by the power, resonance, and emotional warmth of her contralto voice. Julie was immediately engaged as a premier soloist, stepping into the royal spotlight of France's premier cultural institution.",
    "Her official Paris Opera debut took place in late sixteen hundred and ninety in the role of Pallas Athena, the Greek goddess of wisdom and war, in Jean-Baptiste Lully's celebrated lyric tragedy Cadmus et Hermione. It was a role tailor-made for Julie's unique combination of physical nobility and musical genius, allowing her to step onto the stage as both a divine warrior and a master artist before the King's court.",
    "The stage of the Palais-Royal was an architectural wonder of the Baroque era. Lit by thousands of beeswax candles in crystal chandeliers and gilded sconces, the theater featured intricate wooden machinery that allowed celestial chariots and mythological clouds to descend from the ceiling. When the heavy velvet curtain rose, revealing Julie standing in gleaming gilded armor, crested helmet, and holding a warrior's spear, the entire theater gasped in breathless awe.",
    "The moment Julie began to sing, her voice filled the grand auditorium with hypnotic majesty. Her rich, expressive lower register resonated like a warm golden bell, effortlessly soaring over the orchestra of violins, flutes, and theorboes. Her diction was crystal clear, her phrasing filled with emotional depth, and her dramatic presence radiated supreme, divine authority that captivated every listener from the royal box to the parterre.",
    "The audience—composed of the King's brother Philippe of Orléans, royal princes, foreign ambassadors, and the intellectual elite of Paris—erupted into thunderous, standing ovations at the conclusion of her performance. Flowers and laurel wreaths rained down upon the stage as the court celebrated the arrival of a supreme new theatrical star: Mademoiselle de Maupin, the toast of Paris.",
    "Critics and chroniclers of the day were unanimous in their praise. The Mercure Galant, the premier cultural journal of the realm, praised her voice as one of the most beautiful and expressive instruments in Europe, marveling at her ability to embody both fierce warrior heroism and tender feminine grace with effortless natural brilliance that set a new benchmark for French lyric theater.",
    "Despite her sudden ascension to the pinnacle of artistic fame, Julie remained completely grounded and dedicated to her craft. She spent long, peaceful mornings in the Palais-Royal rehearsal halls, working with master accompanists, refining her ornamentation, and studying new operatic scores. She viewed music as a sacred discipline of harmony and soul, an art that demanded continuous devotion and humility.",
    "As midnight fell over Paris and the great chandeliers of the Palais-Royal were slowly lowered and extinguished, Julie stood alone on the empty stage for a quiet moment of reflection. The sweet scent of snuffed beeswax candles hung in the cool air, and the auditorium rested in peaceful silence. She felt deeply grateful for the journey that had brought her to this sacred temple of art. Breathing slowly and deeply, she stepped into the night, resting in the tranquil glow of her glorious triumph."
]

SCENES_06_TO_10[8] = [
    "Count d'Armagnac presenting a velvet-bound petition on behalf of Julie d'Aubigny to King Louis XIV in the glittering Hall of Mirrors at Versailles, warm golden afternoon sun.",
    "King Louis XIV with an amused, benevolent smile signing the royal pardon scroll with a feathered quill, royal wax seal on desk, opulent Baroque interior.",
    "Julie auditioning in the rehearsal hall of the Palais-Royal opera house, grand harpsichord, ornate plasterwork, opera directors listening with astonished admiration.",
    "Julie in her dressing room at the Palais-Royal, putting on the magnificent gilded breastplate and crested helmet of Pallas Athena, glowing mirrors and beeswax candles.",
    "The spectacular rise of the Palais-Royal curtain, revealing Julie as Pallas Athena on a celestial cloud machine surrounded by golden light, breathtaking Baroque stage design.",
    "Julie singing heroically as Pallas Athena with spear in hand, crystal chandeliers above, orchestra of violins and theorboes playing in the candlelit pit.",
    "The glittering Parisian audience in tiered balconies, including princes and ambassadors, rising in a thunderous standing ovation, tossing rose petals onto the stage.",
    "A seventeenth-century French printing press producing copies of the Mercure Galant praising Mademoiselle Maupin, fresh ink, sheets hanging to dry.",
    "Julie seated beside a harpsichord in a quiet morning rehearsal room of the Palais-Royal, studying a new musical manuscript by natural morning window light.",
    "The empty, darkened auditorium of the Palais-Royal at midnight, a single candle illuminating the vast stage, tranquil silence, deep restful peace."
]

# ==============================================================================
# PART 09: Masterpieces of Lully and Campra - Clorinda the Warrior Maiden
# ==============================================================================
PARTS_06_TO_10[9] = [
    "Throughout the sixteen hundred and nineties, Julie d'Aubigny reigned as the premier contralto of the Académie Royale de Musique, inspiring the greatest composers of the French Baroque to create groundbreaking operatic roles specifically tailored to her unique voice and dramatic genius. She performed in the classic masterpieces of Jean-Baptiste Lully and became the primary muse for the rising generation of composers led by André Campra and André Cardinal Destouches.",
    "In sixteen hundred and ninety-nine, André Campra composed his landmark opera-ballet Le Carnaval de Venise, creating a dazzling showcase for Julie's vocal agility and comedic charm. Performing in elaborate Venetian carnivalesque attire, Julie demonstrated that her artistic range spanned from profound tragic gravitas to sparkling, joyous wit, delighting audiences with her effortless charm, sparkling ornamentation, and captivating stage charisma.",
    "Her greatest and most legendary artistic triumph occurred in seventeen hundred and two, when André Campra composed the revolutionary lyric tragedy Tancrède, with a libretto by Antoine Danchet based on Tasso's Gerusalemme Liberata. Campra wrote the central starring role of Clorinda—the Saracen warrior maiden who fights in heavy armor on the battlefield while harboring a tender, tragic love for the Christian knight Tancred—specifically for Julie.",
    "Before Tancrède, French operatic tradition strictly reserved heroic leading roles for high sopranos. Campra was so inspired by the rich, velvety warmth and formidable dramatic power of Julie's contralto that he broke with decades of convention, making Clorinda the first major heroic contralto leading role in French opera history. It was a revolutionary artistic breakthrough that redefined the landscape of European vocal music forever.",
    "Julie's portrayal of Clorinda was mesmerizing. Appearing on stage in polished steel armor, flowing silk surcoats, and a silver-feathered helmet, she moved with the authentic grace and balance of a true swordswoman. During the dramatic battle scenes, her stage combat was executed with real steel blades and genuine martial precision, electrifying the audience with an intensity never before seen on the operatic stage of Paris.",
    "The climax of the opera—the famous death scene of Clorinda in Tancred's arms—moved entire audiences to tears night after night. Julie's voice softened into an exquisite, heartbreaking pianissimo, conveying the peaceful transition of the warrior soul from the fury of battle into eternal, tranquil rest. The pure, hypnotic tenderness of her singing hushed the entire auditorium into reverent, tearful silence and deep emotional release.",
    "Beyond her work with Campra, Julie created principal roles in major operas by Destouches, including Omphale in seventeen hundred and one, and performed in revivals of Lully's Armide, Isis, and Thésée. Her vocal technique was celebrated for its seamless legato, rich emotional coloring, and impeccable pitch, setting a new gold standard for vocal performance across the Continent.",
    "Offstage, Julie established a peaceful, cultured lifestyle in her Parisian apartments near the Palais-Royal. She filled her home with classical sculptures, rare books, exotic flowers, and fine instruments. In the quiet afternoons, she would host intimate musical salons for fellow artists, poets, and philosophers, creating a sanctuary of artistic fellowship and enlightened conversation that nurtured the Parisian soul.",
    "Her daily routine was characterized by rigorous vocal hygiene and physical discipline. She practiced gentle breathing exercises, drank herbal infusions of chamomile and honey, and took long, meditative walks in the Tuileries gardens. Her inner calm and professional dedication allowed her to maintain her extraordinary vocal quality through hundreds of demanding performances without vocal strain.",
    "As the evening performance drew to a close and the applause echoed into the night, Julie would sit quietly in her dressing room, letting the adrenaline of the performance softly dissolve. She breathed slowly and deeply, letting go of the characters she portrayed and returning to the serene center of her own soul. Wrapped in soft silk linens in her quiet bedchamber, she rested deeply, cradled by the timeless beauty of the music she helped create."
]

SCENES_06_TO_10[9] = [
    "Composer André Campra seated at a harpsichord with quill in hand, composing the score of Tancrède while Julie d'Aubigny sings a melody beside him, warm studio candlelight.",
    "Julie performing in the Venetian masquerade scenes of Le Carnaval de Venise, wearing a feathered carnival mask and lavish silk gown, festive stage lighting.",
    "The iconic entrance of Julie as Clorinda in Tancrède, wearing polished steel armor, a silver-crested helmet, and a crimson silk cape, holding a gleaming rapier on stage.",
    "A dramatic stage combat scene in Tancrède, Julie executing authentic fencing parries against actor Thévenard with real steel blades, spark of steel, breathless audience.",
    "The poignant death scene of Clorinda, Julie singing in Tancred's arms on a moonlit stage set, soft blue and lavender theatrical lighting, tearful spectators in boxes.",
    "Close-up of an original 1702 musical score of Tancrède by André Campra, showing the lower contralto vocal stave written expressly for Mademoiselle de Maupin.",
    "Julie on stage in Destouches' opera Omphale, draped in opulent royal fabrics and holding a golden sceptre, surrounded by Baroque choir and dancers.",
    "An intimate evening musical salon in Julie's Parisian home, musicians playing violas da gamba and lutes by soft candlelight, friends listening in peaceful harmony.",
    "Julie strolling peacefully along the gravel pathways of the Tuileries Garden at golden hour, marble statues and trimmed hedges, tranquil contemplation.",
    "Julie resting in her Parisian bedchamber at night, moonlight illuminating the score of Tancrède on her nightstand, profound sense of artistic fulfillment and restful sleep."
]

# ==============================================================================
# PART 10: The Masked Ball of Monsieur - A Kiss, A Challenge, and Three Rapiers
# ==============================================================================
PARTS_06_TO_10[10] = [
    "In the winter of sixteen hundred and ninety-five, one of the most glamorous and talked-about social events of the Grand Siècle took place: the Grand Royal Masked Ball hosted by Monsieur, Philippe I, Duke of Orléans, the King's brother, at the Palais-Royal. The grand ballrooms were transformed into an enchanted wonderland of mirrored galleries, thousands of glittering wax candles, and cascading garlands of winter greenery and silver ribbons that shimmered in the ambient light.",
    "Julie arrived at the masquerade dressed in the height of male aristocratic fashion: an exquisite coat of midnight-blue velvet embroidered with silver thread, silk breeches, lace cravat, and a stylish black velvet carnival mask. Moving through the glittering assembly of masked courtiers, princes, and duchesses with effortless swagger and noble poise, she was widely admired as one of the most handsome and charming young cavaliers at the ball.",
    "During the festivities, Julie became enchanted by a beautiful young noblewoman who was dancing in the central gallery. Approaching the lady with gallant charm and witty conversation, Julie danced with her through several graceful minuets. As the dance concluded near a flower-draped alcove, Julie boldly and tenderly kissed the young marquise on the lips, creating a sensational moment of delightful audacity that was witnessed by several watching courtiers.",
    "Three young aristocratic suitors, who had each been competing for the lady's favors, were deeply offended by what they perceived as an intolerable insult from an unknown young cavalier. Confronting Julie as she stepped out into the palace courtyard, the three noblemen demanded immediate satisfaction, challenging the mysterious youth to an instant duel of honor outside the palace walls.",
    "With cool, amused serenity, Julie accepted their challenge without hesitation. Rather than retreating or revealing her female identity to avoid combat, she invited all three gentlemen to follow her into the secluded gardens behind the Palais-Royal, where the snowy lawns and trimmed hedges lay quiet beneath the crisp, starlit winter sky of Paris.",
    "In the moonlit garden clearing, with the distant music of the palace violins drifting softly through the frozen air, Julie faced the first challenger. Saluting politely with her rapier, she engaged him with lightning speed. Within minutes, her flawless technique disarmed the nobleman, leaving him nursing a minor puncture wound in his sword arm as he looked on in disbelief.",
    "Without pausing to rest, Julie turned to the second challenger. Her footwork on the packed snow was immaculate, maintaining perfect balance as she parried his aggressive lunges and swiftly ran her blade through his sleeve, disarming him with effortless precision. The third nobleman, stepping forward with grim determination, met the same swift fate, his sword sent spinning into the snowy bushes by Julie's masterly circular bind.",
    "Having defeated all three noblemen in consecutive duels in less than a quarter of an hour without suffering a single scratch, Julie politely wiped her blade with her lace handkerchief, sheathed her rapier, and bowed with immaculate courtly courtesy. Leaving the three astonished and humbled gentlemen in the garden, she casually strolled back into the warm ballroom to finish her champagne and resume dancing.",
    "The news of the extraordinary triple duel spread like wildfire through the ballroom. When the court discovered that the dashing cavalier who had defeated three of the best swordsmen in the royal guard was none other than the prima donna Mademoiselle de Maupin, the ball erupted into a mix of shock, laughter, and immense admiration. Julie's legendary feat became the sensation of Paris overnight.",
    "However, dueling was strictly forbidden throughout France by the severe edicts of King Louis XIV, carrying the penalty of imprisonment or death. Recognizing that the three wounded noblemen would be forced to report the incident to the King's marshals, Julie quietly slipped away from the palace into the snowy night, seeking temporary refuge outside the capital while her friends petitioned the King for royal mercy."
]

SCENES_06_TO_10[10] = [
    "The magnificent grand ballroom of the Palais-Royal during the 1695 Royal Masked Ball, crystal chandeliers reflecting in towering mirrors, masked nobility in opulent Baroque gowns and coats.",
    "Julie d'Aubigny dressed in a dashing midnight-blue velvet cavalier suit and black mask, walking through the masquerade crowd with captivating poise and charm.",
    "Julie dancing a graceful minuet with a beautiful young marquise in a candlelit alcove draped in silk ribbons, romantic ambiance.",
    "The dramatic and bold moment where Julie kisses the young noblewoman near the ballroom terrace, three jealous noblemen watching angrily from the shadows.",
    "The confrontation in the palace courtyard, three aristocratic suitors with hands on their sword hilts demanding satisfaction from Julie.",
    "Julie standing en garde in the snowy, moonlit gardens of the Palais-Royal, rapier drawn, breath misting in the crisp winter air, palace lights glowing in background.",
    "Julie engaging the first nobleman in a dynamic fencing duel on the snow-covered lawn, steel blades flashing in the bright moonlight.",
    "Julie effortlessly disarming the third challenger, his rapier flying into a snowbank as she holds her blade at his chest with serene mastery.",
    "Julie sheathing her rapier with a polite, gracious bow to the three defeated noblemen, wiping her blade on a lace handkerchief.",
    "Julie riding a horse through the quiet, snow-covered gates of Paris at midnight, snowflakes falling gently through the moonlight, peaceful winter escape."
]
