#!/usr/bin/env python3
"""
Populate complete 150 paragraphs (~16k words) and 150 visual scene prompts
for Julie d'Aubigny into julie_canonical_data.py
"""

from pathlib import Path
import json

TARGET_FILE = Path("/media/vpsg16gb/Media/historysnooze/scripts/julie_canonical_data.py")

def main():
    parts = {}
    scenes = {}

    # =========================================================================
    # PART 1: The Grand Stables of Versailles - The Riding Master's Daughter
    # =========================================================================
    parts[1] = [
        "Hey guys, tonight we are going to drift back in time to the golden, candlelit halls and mist-shrouded courtyards of seventeenth-century France, where the scent of cedar shavings, polished rapier steel, and Paris opera rosin lingers over the cobblestone riding arenas of Versailles... And let us be honest, given the fiery tavern duels, midnight convent escapes, and audacious royal defiance of La Maupin's world, you probably would not survive this with your peaceful assumptions intact. But that is the fun of it. So, before you get comfortable, take a moment to like the video and subscribe, but only if you genuinely enjoy what I do here. And for a bit of fun, post your location and local time in the comments below. It is always a quiet thrill to see where everyone is drifting off from. Now, dim the lights, maybe turn on a fan for that soft background hum, and let us ease into tonight's journey together.",
        "You stand in the quiet shadows of the Grand Stables of Versailles in the crisp autumn dawn of sixteen hundred and seventy-six. The morning fog rises softly from the damp cobblestone courtyards, catching the first pale golden rays of sunlight breaking over the slate rooftops of the Sun King's palace. All around you, the air is rich, grounding, and comforting, filled with the warm, earthy perfume of cedar wood shavings, freshly baled clover hay, and the steady, rhythmic breathing of hundreds of royal thoroughbreds resting peacefully in their vaulted oak stalls. In this magnificent world of equestrian discipline, a young girl named Julie d'Aubigny takes her first confident footsteps into history, her posture tall, her dark eyes observant, and her spirit completely untroubled by courtly vanity.",
        "Julie was the daughter of Gaston d'Aubigny, a respected secretary and equerry to Louis de Lorraine, the Count d'Armagnac and Grand Écuyer of France. Raised not within the secluded boudoirs or restrictive salons of courtly noblewomen, but amidst the brisk, open-air discipline of the Royal Riding Academy, young Julie grew up in an environment of constant physical grace, athletic vigor, and tireless motion. Her father treated her with the same exacting standards he applied to the young aristocratic pages of the royal court. From early childhood, she learned to sit tall upon spirited Iberian thoroughbreds, guiding them through complex equestrian carousels with effortless posture, balanced hands, and quiet, unshakeable authority that earned the admiration of the palace grooms and veteran riding masters.",
        "The Grand Stables of Versailles were a triumph of French classical architecture, designed by Jules Hardouin-Mansart with soaring limestone arches and expansive arenas where soft daylight poured through high arched windows, casting long, peaceful diagonals across the raked sand. Young Julie spent countless peaceful hours exploring the vast harness rooms, where rows of polished brass buckles gleamed warmly in the soft lantern light. The leather saddles and bridles smelled soothing and rich, rubbed daily with sweet beeswax and neat's-foot oil, creating an atmosphere of timeless order, discipline, and quiet craftsmanship that deeply grounded her spirit in patience, strength, and unwavering focus amidst the daily bustle of the palace.",
        "While other young girls of the French nobility were confined to lessons in delicate needlepoint, quiet embroidery, and polite harpsichord etiquette, Julie was given a wooden training foil and placed before the palace fencing masters. Her natural reflexes, balance, and spatial intuition were astonishing to all who watched her move. Shifting with the fluid agility of a hunting falcon, she grasped the subtle geometry of distance, the precision of the parry, and the swift decisiveness of the thrust. The rhythmic, hypnotic clinking of training blades against the limestone walls became her childhood lullaby, a comforting cadence of balance, breath, and unwavering mental focus that prepared her for a lifetime of daring independence.",
        "In the quiet late afternoons, when the royal pages had finished their grueling riding drills, Julie would climb the winding stone stairs to the upper galleries of the stables. From these high vantage points, she looked out over the vast gardens of Versailles, where fountains whispered in the cooling evening breeze and rows of symmetrical cypress trees stretched toward the golden horizon. Her thoughts were calm, spacious, and untroubled, filled with a deep sense of freedom and an innate confidence in her own extraordinary destiny that seemed written in the vast starlit sky above the royal estate, waiting to unfold in its own perfect time.",
        "Gaston d'Aubigny understood that martial agility was hollow without the cultivation of the intellect. In their private living quarters above the stable courtyards, by the gentle glow of tallow candles, he tutored Julie in classical French literature, Latin philosophy, and the Italian arts. Together they read the epic poetry of Tasso and Ariosto, igniting her imagination with tales of legendary warrior maidens like Bradamante and Clorinda. The steady, rhythmic scratching of her quill on vellum blended with the distant hoot of an owl nesting in the palace groves, creating a sanctuary of quiet learning, philosophical contemplation, and warm domestic peace.",
        "It was also during these early Versailles years that Julie discovered the natural beauty and depth of her singing voice. Listening to the royal choristers practicing in the palace chapel across the courtyard, she would softly imitate their complex harmonies, her rich, resonant contralto echoing through the vaulted stone hallways. The stable grooms and visiting nobles would stop in wonder, captivated by the pure, hypnotic warmth of a voice that sounded both ancient and timeless, filled with effortless power, emotional depth, and soothing melodic grace that seemed to heal the restless mind and bring tranquility to all who listened.",
        "As dusk settled over Versailles, the grooms lit iron lanterns along the stable corridors, casting long amber beams across the cobblestone pavings. The horses settled into their stalls with soft nickers of contentment, chewing on sweet meadow grass and fresh oats. Julie would walk quietly through the long corridors, running her hand along the polished oak partitions, feeling the serene, grounding presence of the resting animals, her heart anchored in complete peace and contentment as the palace drifted into quiet sleep beneath the darkening autumn sky, safe and sheltered from the cold.",
        "As midnight enveloped the Grand Stables of Versailles, the iron lanterns were extinguished one by one, leaving only the cool silver light of the stars above the palace roofs. The vast riding rings lay silent and still, resting beneath the velvet sky. Young Julie closed her eyes in her chamber, her breath slow, deep, and steady, drifting into restful slumber guided by the gentle promise of a life filled with courage, artistry, and boundless adventure across the kingdom of France, where no obstacle would ever dim her radiant spirit."
    ]

    scenes[1] = [
        "Young Julie d'Aubigny standing in the misty courtyard of the Grand Stables of Versailles at golden sunrise, classical French stone arches, morning mist rising from cobblestones, warm atmospheric sunlight, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Gaston d'Aubigny tutoring young Julie beside a spirited black stallion in the sunlit equestrian arena of Versailles, raked sand, leather tack, noble discipline, soft natural daylight, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Intimate still life inside the Versailles harness room, rows of polished brass buckles, oiled leather bridles hanging on cedar walls, soft amber lantern light, serene craftsmanship, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Young Julie in linen shirt and training doublet practicing footwork with a slender wooden fencing foil, high arched limestone windows, dust motes dancing in sunbeams, focused grace, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Julie looking out from the high stone balustrade of the Grand Stables over the symmetrical gardens and fountains of Versailles at sunset, golden horizon, tranquil mood, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Gaston d'Aubigny and young Julie studying classical illuminated manuscripts by the gentle glow of tallow candles in a private chamber, leather-bound books, peaceful evening atmosphere, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Young Julie singing quietly in a vaulted stone arcade of Versailles, soft golden light illuminating her serene face, classical Baroque columns, hypnotic acoustic beauty, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Stable grooms hanging iron lanterns along the cobblestone corridors of the Grand Stables at dusk, horses resting peacefully in oak stalls, warm orange glow, calming stillness, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Close-up portrait of young Julie d'Aubigny with natural dark hair and confident expressive eyes, wearing a simple riding vest, soft ambient lighting, timeless dignity, wide cinematic 16:9 composition, ultra-high-resolution 4K.",
        "Panoramic view of the Grand Stables of Versailles under a vast starry midnight sky, crescent moon illuminating slate rooftops, peaceful sleep atmosphere, pure tranquility, wide cinematic 16:9 composition, ultra-high-resolution 4K."
    ]

    # Let's verify Part 1 word count
    print("Part 1 word count:", sum(len(b.split()) for b in parts[1]))

    return parts, scenes

if __name__ == "__main__":
    p, s = main()
