"""
HistorySnooze Script Producer - Canonical Beats (Parts 04 to 06)
Module: canonical_beats_p04_p06.py
Rule <= 150 lines compliant.
"""

from typing import Any, List, Tuple

RAW_BEATS_P04_P06: List[Tuple[Any, ...]] = [
    # Part 04: The Great Fire of Tenna and the Ashes of Edo
    (4, 1, "Fiery Night Sky over Edo",
     "sudden reddish glow appears on distant horizon... Great Fire of Tenna engulfs city",
     "Winter night sky glowing fiery orange in distance across Sumida River, temple alarm gongs ringing over Edo rooftops",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),
    (4, 2, "Embers Swirling Across River",
     "northwesterly gale drives embers and flaming thatch across river like storm of falling stars",
     "Bashō standing on veranda gazing at swirling sparks and billowing smoke carried across the river by roaring winter winds",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),
    (4, 3, "Escape into Cold River Mud",
     "wades out into cold tidal shallows of river, wrapping himself in damp straw mat",
     "Bashō escaping into cold shallow tidal river waters wrapped in wet straw mat as embers shower around the burning hut",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),
    (4, 4, "Flames Consuming the Hut",
     "watching hermitage and banana plant consumed by roaring wall of flame... impermanence of shelter",
     "Solitary figure resting safely in river reeds beneath cold night sky, smoke rising as flames consume thatched roof",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", "ref_props_basho_leaves"),
    (4, 5, "Dawn over Smoldering Ruins",
     "dawn breaks over smoldering ruins... cold white mist mingling with lingering grey smoke",
     "Dawn light breaking over smoldering ashes and blackened timber posts of Fukagawa, white morning mist mingling with smoke",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),
    (4, 6, "Seated on Charred Beams",
     "sit with him upon fallen, blackened beam as morning sun casts pale smoky light across ruins",
     "Bashō sitting calmly on charred cedar beam amidst pale morning ruins, gazing at empty clearing where his hut stood",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),
    (4, 7, "Serene Spiritual Acceptance",
     "extraordinary, luminous tranquility shone in his eyes... unburdened by material possessions",
     "Close portrait of Bashō's calm face reflecting serene acceptance and spiritual detachment amidst morning mist",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),
    (4, 8, "Burnt Tea Kettle Shard",
     "uncovers small shard of burnt clay from old tea kettle, holding humble fragment with affectionate smile",
     "Still life close-up of a weathered hand holding a cracked, smoke-darkened ceramic shard from a tea kettle amid grey ashes",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", "ref_props_tea_hearth_irori"),
    (4, 9, "Riverbank Dawn Contemplation",
     "standing at riverbank watching sun rise above bay... true home is boundless open universe",
     "Bashō standing at riverbank at sunrise, hands resting gently together, gazing serenely across calm glistening waters",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),
    (4, 10, "Winter Refuge in Kai",
     "disciples shelter master, taking him to rural retreat in Kai Province... snowy mountain silence",
     "Mountain farmhouse shelter in Kai province, warm hearth fire glowing softly inside as evening snow blankets pines",
     "ref_character_basho_elder", "ref_setting_fukagawa_exterior", None),

    # Part 05: The First Wandering: The Weather-Exposed Skeleton
    (5, 1, "Misty Fuji River Trail",
     "chill autumn mist hangs low over gravel banks of Fuji River, veiling towering peak of Mount Fuji",
     "Winding gravel trail along Fuji River in autumn mist, distant snow-tipped Mount Fuji, Bashō beginning walking pilgrimage",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", "ref_props_travel_gear"),
    (5, 2, "Sturdy Bamboo Staff & Hat",
     "carries polished wooden walking staff... conical woven straw hat inscribed with traveler's motto",
     "Medium shot of Bashō in dark hemp robe, wide woven straw hat on back, sturdy bamboo walking staff striking dusty trail",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", "ref_props_travel_gear"),
    (5, 3, "Autumn Tallgrass Meadow",
     "walking into boundless horizon... resolved to accept dying by roadside if nature wills",
     "Solitary traveler walking through golden autumn tallgrass meadow, mountain ridges fading into soft afternoon haze",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", None),
    (5, 4, "Roadside Teahouse Rest",
     "rustic roadside teahouses where travelers rest aching feet on woven straw benches",
     "Rustic thatched roadside teahouse along highway, travelers resting on wooden benches under maples, steam from teacups",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", None),
    (5, 5, "Satta Pass Suruga Bay Vista",
     "ascend steep switchbacks of Satta Pass... sweeping panoramic vista of breaking ocean waves",
     "Panoramic vista from Satta Pass: winding coastal mountain ledge, breaking white waves of Suruga Bay, pines on cliff",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", None),
    (5, 6, "Compassion for Abandoned Child",
     "encounter near bank of Fuji River... giving food from woven sleeve with tearful compassion",
     "Bashō kneeling by riverbank in gentle compassion, offering food from his woven sleeve to an abandoned traveler child",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", None),
    (5, 7, "Return to Iga Ancestral Home",
     "arrive at childhood home in Iga-Ueno... elder brother greets him at wooden threshold",
     "Arriving at old family home in Iga-Ueno, stepping over worn wooden threshold into warm entryway as brother greets him",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", None),
    (5, 8, "Sunken Hearth Gathering",
     "family gathers around sunken hearth... brother brings out small lacquered amulet box",
     "Family gathered around glowing sunken hearth in rustic ancestral home, elder brother presenting small lacquered box",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", "ref_props_tea_hearth_irori"),
    (5, 9, "Mother's Silver Lock of Hair",
     "inside rests a lock of mother's white hair... would melt in hot tears like autumn frost",
     "Close-up macro of aged hands gently cradling an open black lacquer box holding a delicate silver lock of mother's hair",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", "ref_props_inkstone_brush"),
    (5, 10, "Quiet Moonlit Ancestral Room",
     "sitting peacefully in tatami room, hands resting in lap... crickets singing outside in autumn garden",
     "Bashō sitting peacefully in moonlit tatami room, hands resting in lap, looking out at quiet crickets in ancestral garden",
     "ref_character_basho_traveler", "ref_setting_fuji_river_trail", None),

    # Part 06: The Departure from Senju and the Great Northern Trail
    (6, 1, "Spring Dawn at River Dock",
     "spring morning dawns with luminous mist... preparing for journey to Deep North",
     "Spring dawn over Sumida River with pink-tinged morning mist, Bashō fastening waraji sandals at edge of ferry dock",
     "ref_character_basho_traveler", "ref_setting_senju_dock", "ref_props_travel_gear"),
    (6, 2, "Tearful Farewell at Senju",
     "circle of devoted disciples accompanied pilgrims to Senju... spring departs, birds weep",
     "River barge at Senju boat landing, circle of weeping disciples bowing in farewell as Bashō steps onto northern riverbank",
     "ref_character_basho_traveler", "ref_setting_senju_dock", None),
    (6, 3, "Northern Highway Horizon",
     "turning his back on Edo's river towers... gazing ahead toward long unpaved northern highway",
     "Bashō turning his back on Edo's river towers, gazing ahead toward long unpaved highway vanishing into morning mist",
     "ref_character_basho_traveler", "ref_setting_senju_dock", "ref_props_travel_gear"),
    (6, 4, "Kawai Sora with Travel Pack",
     "companion Kawai Sora... carrying heavy wicker backpack holding journals, ink, provisions",
     "Kawai Sora standing by milestone marker, wearing travel robes and woven straw backpack, checking road maps",
     "ref_character_sora", "ref_setting_senju_dock", "ref_props_travel_oi"),
    (6, 5, "Walking Plains of Musashino",
     "two pilgrims walking side by side down wide earthen highway through green flowering plains",
     "Two traveling poets walking side by side down wide earthen highway through green flowering plains, skylarks soaring",
     "ref_character_basho_traveler", "ref_setting_senju_dock", None),
    (6, 6, "Cherry Blossom Teahouse",
     "roadside teahouse sheltered beneath spreading branches of flowering wild cherry tree",
     "Rustic highway teahouse under blooming weeping cherry tree, pink petals floating down around two seated travelers",
     "ref_character_basho_traveler", "ref_setting_senju_dock", None),
    (6, 7, "Cryptomeria Pine Shadows",
     "shadows of roadside cryptomeria trees stretch across quiet packed-dirt trail",
     "Long golden afternoon shadows of giant roadside cryptomeria trees stretching across the quiet packed-dirt trail",
     "ref_character_basho_traveler", "ref_setting_senju_dock", "ref_props_travel_gear"),
    (6, 8, "Irrigated Rice Terraces at Dusk",
     "walking beside quiet canals feeding green rice paddies, gurgling mountain water",
     "Clear mountain water gurgling through wooden canal gates beside vibrant green flooded rice terraces at twilight",
     "ref_character_basho_traveler", "ref_setting_senju_dock", None),
    (6, 9, "Post Town Footbath",
     "rural post town inn... wooden basin of steaming warm water for washing tired feet",
     "Rustic post town travelers' inn entryway, wooden basin of steaming warm water for washing feet, straw sandals set aside",
     "ref_character_basho_traveler", "ref_setting_senju_dock", None),
    (6, 10, "Post Town Inn Night Rest",
     "candle flickering softly... night breeze through bamboo lattice, drifting into deep sleep",
     "Bashō and Sora resting peacefully in simple post inn chamber, candle flickering softly, night breeze through lattice",
     "ref_character_basho_traveler", "ref_setting_senju_dock", None),
]
