"""
HistorySnooze Script Producer - Canonical Beats (Parts 10 to 12)
Module: canonical_beats_p10_p12.py
Rule <= 150 lines compliant.
"""

from typing import Any, List, Tuple

RAW_BEATS_P10_P12: List[Tuple[Any, ...]] = [
    # Part 10: The Weeping Willows and Twilight of Kisakata
    (10, 1, "Kisakata Lagoon Twilight",
     "melancholy rain-washed twilight blankets quiet saltwater lagoon of Kisakata, pine-covered islands",
     "Kisakata saltwater lagoon dotted with pine-crested islets, weeping willows trailing in still water under grey twilight",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),
    (10, 2, "Walking Shoreline Drizzle",
     "walking with Bashō along wet sandy shoreline in summer drizzle, weeping willows brushing water",
     "Bashō walking along wet shore of Kisakata lagoon, carrying bamboo staff, soft summer drizzle rippling the surface",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", "ref_props_travel_gear"),
    (10, 3, "Silk-Tree Blossoms Still Life",
     "Kisakata in the rain— / Seishi sleeps with silk-tree blossoms. Raindrop-washed pink flowers",
     "Macro still life of delicate pink silk-tree blossoms washed with raindrops beside Bashō's brush and verse slip",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", "ref_props_inkstone_brush"),
    (10, 4, "Thatched Kanmanji Gate",
     "winding footpath toward ancient temple of Kanmanji nestled among pines overlooking lagoon",
     "Ancient thatched timber gate of Kanmanji temple surrounded by weathered pine groves overlooking Kisakata lagoon",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),
    (10, 5, "Clouds Parting Over Chōkai",
     "sitting upon covered temple veranda... watching clearing clouds reveal peak of Mount Chōkai",
     "Bashō seated on Kanmanji temple veranda watching clearing clouds reveal majestic snow-crested peak of Mount Chokai",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),
    (10, 6, "Mirror Reflection of Chōkai",
     "reflection of Mount Chōkai trembling in clear water of lagoon, pale evening sunset glow",
     "Mount Chokai's volcanic cone perfectly reflected in the still evening mirror of Kisakata lagoon, pink sunset clouds above",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),
    (10, 7, "Moonlit Pavilion Deck",
     "stepping out onto wooden deck of pavilion, moonlight tracing sparkling silver path across lagoon",
     "Bashō standing on moonlit temple deck, silver moonlight shimmering across lagoon waters and silhouetted pine islands",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),
    (10, 8, "Tidal Lapping Against Pilings",
     "gentle rhythmic lapping of tidal waters against wooden pilings, heart releasing lingering sorrow",
     "Serene close view of clear tidal water lapping gently against mossy wooden pilings and smooth granite boulders at night",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),
    (10, 9, "Kanmanji Temple Guest Room",
     "murmur of ocean swells against distant dunes... settling onto tatami mats in temple chamber",
     "Kanmanji temple guest room in soft lantern glow, open screens framing peaceful night lagoon, bedding laid out on tatami",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),
    (10, 10, "Sacred Stone Lantern Night",
     "sacred temple lanterns cast soft amber glow on stone paths... slipping into deep restorative sleep",
     "Exterior stone lanterns glowing warmly along mossy path outside temple chamber under starry sky, quiet restful night",
     "ref_character_basho_traveler", "ref_setting_kisakata_lagoon", None),

    # Part 11: The Barrier of Shirakawa and the Southern Return
    (11, 1, "Autumn at Shirakawa Barrier",
     "golden sunlight of early autumn bathes ancient wooden watchtowers of Shirakawa Barrier",
     "Ancient wooden watchtower and gate of Shirakawa Barrier bathed in golden autumn light, maple leaves falling on trail",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", "ref_props_travel_gear"),
    (11, 2, "Admirers Greeting the Poet",
     "news of safe return spreads ahead, literary circles celebrate, admirers offer lodging",
     "Roadside post town crowd and local poets greeting Master Bashō with reverent bows along bustling southern highway",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", None),
    (11, 3, "Slipping Away to Solitude",
     "politely declines noisy adulation, slipping away down peaceful bamboo lane toward Lake Biwa",
     "Bashō in simple travel robes quietly slipping away down a peaceful bamboo lane away from the crowded highway town",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", "ref_props_travel_gear"),
    (11, 4, "Lake Biwa Shoreline Sunrise",
     "walking along reed-lined shores of Lake Biwa at sunrise, calm blue waters stretching to mountains",
     "Solitary figure walking along reed-lined shores of Lake Biwa at sunrise, calm blue waters stretching toward distant mountains",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", None),
    (11, 5, "Meditating at Ishiyama Temple",
     "seclusion at ancient temple of Ishiyama on Seta River, meditating in sacred temple hall",
     "Ishiyama-dera temple hall perched on dark volcanic rock overlooking river, Bashō seated in quiet contemplation",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", None),
    (11, 6, "Golden Harvest Around the Lake",
     "golden rice paddies unrolling like silk scroll, farmers harvesting grain, white sails on blue water",
     "Expansive view of Lake Biwa harvest fields: golden rice paddies, farmers harvesting grain, white sails on blue lake",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", None),
    (11, 7, "Stone Lantern at Dusk",
     "resting beside ancient stone lantern on shore of Lake Biwa as white sails drift into port at dusk",
     "Bashō resting beside an ancient stone lantern on the shore of Lake Biwa as white sails drift into port at dusk",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", None),
    (11, 8, "Night Fishing Fires on Lake",
     "lakeside veranda at night... dark waters dotted with glowing amber fires of cormorant fishing boats",
     "View from lakeside veranda at night: shimmering dark waters of Lake Biwa dotted with glowing amber fishing boat fires",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", None),
    (11, 9, "Lakeside Hearth Teapot",
     "warming hands over small ceramic brazier in peaceful lakeside hut, steam curling from iron kettle",
     "Bashō warming his hands over small ceramic charcoal brazier in peaceful lakeside hut, steam curling from iron kettle",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", "ref_props_tea_hearth_irori"),
    (11, 10, "Waves Washing Southern Shore",
     "rhythm of waves washing over sandy shoreline, deep breath, drifting into peaceful sleep",
     "Quiet tatami bedroom in lakeside hermitage, moonlight filtering through paper shoji onto sleeping futon, absolute calm",
     "ref_character_basho_traveler", "ref_setting_shirakawa_barrier", None),

    # Part 12: The Hut of the Phantom Dwelling (Genjū-an)
    (12, 1, "Mountain Bamboo Hut of Genjū-an",
     "summer breeze through bamboo groves of Mount Kokunjo, secluded thatch hut of Genjū-an",
     "Rustic thatched mountain hut of Genjū-an nestled among towering green bamboo stalks on Mount Kokunjo, morning mist swirling",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", None),
    (12, 2, "Sweeping the Cedar Veranda",
     "sweeping wooden veranda with broom of dried bamboo twigs, rhythmic swish in morning light",
     "Bashō sweeping weathered wooden veranda of Genjū-an with rustic bamboo broom as morning light filters through bamboo",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", None),
    (12, 3, "Writing Record of Phantom Dwelling",
     "writing Genjū-an no Fu (Record of Phantom Dwelling)... life as fleeting illusory dwelling",
     "Bashō seated at low cedar desk inside Genjū-an, grinding sumi ink and writing his prose masterpiece on mulberry paper",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", "ref_props_inkstone_brush"),
    (12, 4, "Gathering Forest Ferns",
     "walking overgrown stone trail behind hut, picking mountain ferns beside singing brook",
     "Bashō walking mossy stone forest path gathering wild fiddlehead ferns in woven bamboo basket beside a sparkling brook",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", None),
    (12, 5, "Rhythmic Bamboo Water Pipe",
     "hollowed bamboo water pipe pouring mountain water into carved stone basin with rhythmic clack",
     "Hollowed bamboo water pipe trickling cold spring water into carved mossy stone basin in tranquil mountain garden",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", "ref_props_inkstone_brush"),
    (12, 6, "Golden Afternoon Mountain View",
     "afternoon heat softens into golden glow of dusk, sitting on open veranda gazing at mountain ridges",
     "Bashō seated on open veranda in golden late afternoon light, gazing out over layers of mist-shrouded mountain ridges",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", None),
    (12, 7, "Mindful Hermit Supper",
     "simple evening meal: bowl of freshly cooked mountain rice, salted plum, and wild green herbs",
     "Still life of simple hermit supper on unadorned cedar tray: bowl of steaming white rice, dark salted plum, and wild herbs",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", "ref_props_inkstone_brush"),
    (12, 8, "Lighting the Hermitage Lamp",
     "lighting wick of small ceramic oil lamp inside Genjū-an as darkness envelops bamboo forest",
     "Bashō lighting wick of small ceramic oil lamp inside Genjū-an as darkness envelops the mountain bamboo forest",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", None),
    (12, 9, "Moonlit Bamboo Through Screens",
     "interior view through open shoji of night bamboo grove swaying beneath crescent moon and stars",
     "Interior view through open shoji of night bamboo grove swaying gently beneath a crescent moon and glittering stars",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", None),
    (12, 10, "Restful Bamboo Slumber",
     "night air whispering through bamboo stalks, rhythmic rustle of leaves, deep mountain slumber",
     "Bashō asleep peacefully on comfortable floor futon, gentle shadows dancing on cedar ceiling, deep mountain tranquility",
     "ref_character_basho_elder", "ref_setting_genjuan_bamboo", None),
]
