"""
HistorySnooze Script Producer - Canonical Beats (Parts 13 to 15)
Module: canonical_beats_p13_p15.py
Rule <= 150 lines compliant.
"""

from typing import Any, List, Tuple

RAW_BEATS_P13_P15: List[Tuple[Any, ...]] = [
    # Part 13: The Aesthetic of Karumi (Lightness)
    (13, 1, "Golden Ginkgo Rain in Kyoto",
     "golden leaves of ancient ginkgo trees drifting through autumn air, carpeting temple courtyards",
     "Ancient temple courtyard in Kyoto covered in carpet of golden ginkgo leaves, Bashō walking slowly under raining leaves",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),
    (13, 2, "Gathering Overlooking Kamo River",
     "second-story room of disciple's home overlooking Kamo River, gathering of devoted disciples",
     "Gathering of poetry disciples around Master Bashō in second-story Kyoto room overlooking Kamo River, studying scrolls",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", "ref_props_inkstone_brush"),
    (13, 3, "Teaching the Shallow Riverbed",
     "holding a single river stone, speaking with disciples on karumi: finding beauty in daily life",
     "Bashō demonstrating with gentle smile, holding a single river stone, speaking with disciples in warm light of room",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),
    (13, 4, "Sarumino Manuscript Still Life",
     "bound volume of Sarumino (Monkey's Raincoat) anthology resting on aged cedar desk beside brush",
     "Macro still life of bound Japanese manuscript volume resting on aged cedar desk beside inkstone",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", "ref_props_inkstone_brush"),
    (13, 5, "Drying Persimmons in Kyoto",
     "quiet residential lane in eastern Kyoto, strings of bright orange persimmons hanging to dry",
     "Quiet residential lane in eastern Kyoto, strings of bright orange persimmons hanging to dry from thatched wooden eaves",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),
    (13, 6, "Craftsmen at Work",
     "craftsmen in open timber workshop fitting cedar barrel hoops, seeing poetry in ordinary tasks",
     "Craftsmen in open timber workshop fitting cedar barrel hoops with mallets, Bashō observing with peaceful admiration",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),
    (13, 7, "Rain on Tea Pavilion Eaves",
     "sheltering under wooden eaves of rustic garden tea pavilion, watching gentle autumn rain",
     "Bashō sheltering under wooden eaves of a rustic garden tea pavilion, watching gentle autumn rain drops ripple a koi pond",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),
    (13, 8, "Sunlit Wet Autumn Maples",
     "sunbeams breaking through rain clouds over Kyoto garden, wet Japanese maple leaves glowing red",
     "Sunbeams breaking through rain clouds over Kyoto garden, wet Japanese maple leaves glowing brilliant red and amber",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),
    (13, 9, "Radiant Calm on Garden Bridge",
     "standing on arched garden bridge over clear stream, gazing at sparkling wet garden with calm",
     "Bashō standing on arched garden bridge over clear stream, gazing at the sparkling wet garden with radiant inner calm",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),
    (13, 10, "Twilight Canal of Shirakawa",
     "canal path along Shirakawa in Kyoto at twilight, weeping willows, amber stone lanterns glowing",
     "Canal path along Shirakawa in Kyoto at twilight, weeping willows, amber stone lanterns glowing, peaceful evening rest",
     "ref_character_basho_elder", "ref_setting_kyoto_rakushisha", None),

    # Part 14: The Final Journey Along the Tōkaidō to Osaka
    (14, 1, "Frosty Tōkaidō Post Road",
     "walking frosty Tōkaidō post road in late autumn, white frost sparkling on wayside grasses",
     "Bashō walking frosty Tōkaidō post road in late autumn, white frost sparkling on wayside grasses, morning mist rising",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", "ref_props_travel_gear"),
    (14, 2, "Reconciling Rival Poets",
     "seated between two reconciling poetry disciples in Osaka merchant chamber, bowing with smile",
     "Bashō seated between two reconciling poetry disciples in an Osaka merchant chamber, bowing with gentle reassuring smile",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", None),
    (14, 3, "Resting in Garden Room",
     "peaceful inner garden chamber in Osaka, resting on soft tatami futon, autumn leaves visible",
     "Peaceful inner garden chamber in Osaka, Bashō resting on soft tatami futon, autumn leaves visible through sliding screen",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", None),
    (14, 4, "Loving Care of Disciples",
     "disciples kneeling tenderly by bedside in soft afternoon light, cooling brow with damp cloth",
     "Disciples kneeling tenderly by Bashō's bedside in the soft afternoon light, cooling his brow with damp cloth",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", None),
    (14, 5, "Serene Smiling Visage",
     "close portrait of Bashō's serene smiling face on resting pillow, surrounded by companions",
     "Close portrait of Bashō's serene, smiling face on the resting pillow, surrounded by gentle warmth and devoted companions",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", None),
    (14, 6, "Handshake Reunion with Student",
     "traveler disciple kneeling at doorway in dusty robes, Bashō holding his hand in reunion",
     "Traveler disciple kneeling at the doorway in dusty travel robes, Bashō holding his hand in heartfelt reunion",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", None),
    (14, 7, "Propped Up with Bamboo Brush",
     "propped up on tatami cushions, holding slender bamboo brush with trembling hand over washi",
     "Bashō propped up on tatami cushions, holding slender bamboo brush with trembling hand over a fresh white washi scroll",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", "ref_props_inkstone_brush"),
    (14, 8, "The Death Poem in Sumi Ink",
     "macro view of fresh black sumi brushstrokes of death poem: dreams wander over withered moors",
     "Macro intimate view of the fresh black sumi brushstrokes of Bashō's final death poem on fibrous mulberry paper",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", "ref_props_inkstone_brush"),
    (14, 9, "Dreams Over Withered Moors",
     "vision of vast withered autumn moor beneath tranquil twilight sky, solitary spirit path",
     "Vision of expansive dreamscape: vast withered autumn moor beneath a tranquil twilight sky, a solitary spirit path",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", None),
    (14, 10, "Peaceful Candlelit Departure",
     "peaceful final stillness in chamber, disciples bowing low in silence, moonlight on tatami",
     "Peaceful final stillness in candlelit chamber, disciples bowing low in reverent silence, moonlight spilling across tatami",
     "ref_character_basho_elder", "ref_setting_tokaido_highway", None),

    # Part 15: The Eternal Trail & Hypnotic Bedtime Wind-Down
    (15, 1, "Dreamscape of Sacred Trails",
     "composite landscape dreamscape: cedar mountains, Sumida marsh, northern trail under twilight",
     "Grand composite landscape dreamscape: misty cedar mountains, peaceful Sumida river marsh, and winding northern road",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
    (15, 2, "Peace Residing Within",
     "serene mountain hermitage overlooking calm moonlit valley, warm amber lanterns glowing",
     "Serene mountain hermitage overlooking calm moonlit valley, warm amber lanterns glowing peacefully in distance",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
    (15, 3, "Worn Sandals by Milestone",
     "worn travel straw sandals (waraji) and smooth bamboo staff resting against mossy milestone",
     "Still life of worn travel straw sandals and smooth bamboo staff resting against an ancient mossy stone milestone",
     "ref_character_basho_elder", "ref_setting_withered_moor", "ref_props_travel_gear"),
    (15, 4, "Solitary Mountain Ridge Dawn",
     "solitary traveler standing on mountain ridge overlooking sunrise clouds, hands in sleeves",
     "Solitary traveler standing on mountain ridge overlooking sunrise clouds, hands resting peacefully in loose sleeves",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
    (15, 5, "Milky Way Celestial Harmony",
     "Milky Way (River of Heaven) arching across deep indigo night sky above mountain ridges",
     "Majestic celestial view of the Milky Way arching across deep indigo night sky above silhouetted mountain ridges",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
    (15, 6, "Candlelit Tatami Chamber",
     "tranquil candlelit tatami room, sliding paper shoji open to reveal cool starry night",
     "Tranquil candlelit tatami room, sliding paper shoji open to reveal cool starry night and tranquil bamboo shadows",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
    (15, 7, "Soft Glowing Lamp & Quilt",
     "soft glowing oil lamp on low cedar shelf, gentle ambient light washing over clean tatami",
     "Soft glowing oil lamp on low cedar shelf, gentle ambient light washing over clean tatami mats and folded woven quilt",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
    (15, 8, "Fragrant Mountain Futon",
     "comfortable sleeping futon with thick indigo cotton quilt laid out neatly on tatami mats",
     "Inviting, comfortable sleeping futon with thick indigo cotton quilt laid out neatly on fragrant rush tatami mats",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
    (15, 9, "Bamboo Water Drop Echo",
     "clear water drop falling from bamboo spigot into dark stone basin, delicate ripples expanding",
     "Close serene view of clear water drop falling from bamboo spigot into dark stone water basin, delicate ripples expanding",
     "ref_character_basho_elder", "ref_setting_withered_moor", "ref_props_inkstone_brush"),
    (15, 10, "Midnight Starlit Hermitage",
     "exterior view of quiet thatched mountain hut at midnight, deep blue starlit sky, eternal peace",
     "Exterior view of quiet thatched mountain hut at midnight, deep blue starlit sky, single soft amber glow within, eternal peace",
     "ref_character_basho_elder", "ref_setting_withered_moor", None),
]
