"""
HistorySnooze Script Producer - Canonical Beats (Parts 01 to 03)
Module: canonical_beats_p01_p03.py
Rule <= 150 lines compliant.
"""

from typing import Any, List, Tuple

RAW_BEATS_P01_P03: List[Tuple[Any, ...]] = [
    # Part 01: The Whispering Pines of Iga-Ueno and the Young Master
    (1, 1, "Ueno Mountain Trail at Twilight",
     "standing upon a winding dirt lane on the misty outskirts of Ueno Castle... amber glow into lavender twilight",
     "Winding dirt lane on misty outskirts of Ueno Castle in Iga Province at lavender twilight, feathery red pines, distant farmsteads",
     "ref_character_basho_young", "ref_setting_iga_ueno", "ref_props_travel_gear"),
    (1, 2, "Misty Hills of Iga",
     "cedar woodsmoke drifting from humble farmsteads nestled among the hills... physical stamina required",
     "Humble thatch-roofed farmsteads nestled among misty green hills of Iga, sweet cedar woodsmoke drifting, weeping bamboo",
     "ref_character_basho_young", "ref_setting_iga_ueno", None),
    (1, 3, "Dim the Lights Transition",
     "Now, dim the lights, maybe turn on a fan for that soft background hum, and let’s ease into tonight’s journey",
     "Twilight deepening into indigo night, evening breeze carrying moisture of mountain streams, first stars glittering in pine branches",
     "ref_character_basho_young", "ref_setting_iga_ueno", None),
    (1, 4, "Young Kinsaku by the Stream",
     "walking quietly beside young Matsuo Kinsaku... sky shifts from pale bronze to a tranquil indigo",
     "Young Matsuo Kinsaku in indigo hemp traveler robe walking quietly along mountain stream path, evening stars shimmering",
     "ref_character_basho_young", "ref_setting_iga_ueno", None),
    (1, 5, "Lantern-Lit Samurai Ward",
     "earthen walls topped with dark grey ceramic roof tiles border modest samurai compounds... warm buttery light",
     "Low earthen walls and dark ceramic roof tiles of samurai district, paper shoji screens glowing with warm amber oil lamps",
     "ref_character_basho_young", "ref_setting_iga_ueno", None),
    (1, 6, "Tōdō Clan Courtyard & Study",
     "timber gateway into outer courtyard of Tōdō clan manor... Yoshitada and Kinsaku sit cross-legged on tatami",
     "Timber gateway and raked gravel courtyard of Tōdō manor, young Yoshitada and Kinsaku seated on woven tatami mats",
     "ref_character_basho_young", "ref_setting_iga_ueno", None),
    (1, 7, "Pine-Soot Inkstone Still Life",
     "beside him rests an inkstone of polished black slate, where a stick of fragrant pine-soot ink has been slowly ground",
     "Macro intimate still life of carved black slate inkstone with wet pine-soot ink, slender bamboo brush, mulberry washi scroll",
     "ref_character_basho_young", "ref_setting_iga_ueno", "ref_props_inkstone_brush"),
    (1, 8, "Exchanging Linked Verses",
     "exchange written verses on sheets of handmade mulberry paper... long, restful pauses of silent appreciation",
     "Two young samurai poets reviewing vertical haikai verse scrolls by soft lantern light, master Kigin's poetry volumes on desk",
     "ref_character_basho_young", "ref_setting_iga_ueno", "ref_props_inkstone_brush"),
    (1, 9, "Evening Roasted Barley Tea",
     "servant enters silently, placing a small ceramic pot of steaming roasted barley tea... moon rises slowly",
     "Steaming ceramic teapot and porcelain cups on low cedar table, full moon casting silver light across stone garden lanterns",
     "ref_character_basho_young", "ref_setting_iga_ueno", "ref_props_tea_hearth_irori"),
    (1, 10, "Garden Pines Beneath the Stars",
     "set down their writing brushes and sit in companionable silence, listening to night breeze murmur through garden pine trees",
     "Writing brushes resting on ceramic rests, open shoji screen revealing quiet garden pines beneath a vast tranquil starry sky",
     "ref_character_basho_young", "ref_setting_iga_ueno", "ref_props_inkstone_brush"),

    # Part 02: The Waterways of Nihonbashi and the Merchant Capital
    (2, 1, "Nihonbashi Morning Mist",
     "morning sun breaks softly through ocean mist, illuminating grand arched wooden span of Nihonbashi",
     "Grand arched wooden Nihonbashi Bridge in morning ocean mist, bustling merchants and commuters crossing wooden planks",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 2, "Master Tōshichirō in Edo",
     "walk alongside Matsuo Tōshichirō... independent professional poet and scholar",
     "Matsuo Tōshichirō in humble scholar robes walking amidst orderly morning flow of Edo craftsmen and merchants",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 3, "Canal Waterworks Office",
     "administrative overseer on municipal aqueduct project... canal-side timber office, unrolling long architectural scrolls",
     "Canal-side timber waterworks office along Kanda River, Bashō unrolling architectural blueprints and water gate clearance scrolls",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 4, "Raised Aqueduct Dikes",
     "raised earthen dikes flanking aqueduct as laborers carefully assemble wooden sluice gates",
     "Raised earthen dikes along Kanda aqueduct, laborers fitting heavy cedar sluice gates as mountain water rushes through",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 5, "Clear Mountain Runoff Basins",
     "clear mountain runoff tumbling into stone basins... tiny pine needles and sweet mountain moss",
     "Pure mountain stream water cascading into carved stone basins, floating green moss and pine needles, serene hydraulic engineering",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 6, "Master Tōsei Certification",
     "earned formal certification as haikai master... pen name Tōsei, welcoming aspiring merchant students",
     "Master Tōsei receiving aspiring merchant poetry students at sliding wooden doorway of his canal-side lodging",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 7, "Charcoal Brazier Gathering",
     "students gather around low charcoal brazier... read submitted verse slips with gentle, encouraging smiles",
     "Intimate circle of merchant students around glowing cast-iron charcoal brazier, Master Tōsei annotating verse slips",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", "ref_props_inkstone_brush"),
    (2, 8, "Quiet Midnight Room",
     "extinguishes all but one rapeseed oil lamp... dark waters of Kanda River glide silently beneath starry sky",
     "Tōsei alone in quiet chamber by single rapeseed lamp, looking out lattice window at crescent moon shimmering on Kanda River",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 9, "Night Watchman Clappers",
     "distant night watchman striking two wooden clappers together in slow, reassuring pattern",
     "Solitary Edo night watchman with paper lantern walking misty canal embankment, rhythmic wooden clappers echoing",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),
    (2, 10, "Sleeping Waters Meditation",
     "breath slows to match deep, unhurried rhythm of resting capital... floating like fallen leaf",
     "Master Tōsei seated on straw sleeping mat in deep peaceful meditation, soft moonlight casting grid shadows across tatami",
     "ref_character_basho_young", "ref_setting_edo_nihonbashi", None),

    # Part 03: The Hermitage of the Plantain Tree at Fukagawa
    (3, 1, "Crossing the Sumida by Night",
     "gentle dip of wooden oars into wide, moonlit waters of Sumida River... crossing toward marshlands of Fukagawa",
     "Small wooden ferryboat gliding across moonlit Sumida River toward marsh reeds of Fukagawa, Master Tōsei seated at the bow",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", None),
    (3, 2, "Path to the Marsh Hut",
     "step off wooden boat onto narrow earthen path... arrive at modest hermitage hut built by disciple Sampu",
     "Narrow earthen footpath through marsh reeds arriving at the rustic thatched gate of the Fukagawa hermitage hut",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", None),
    (3, 3, "Planting the Bashō Tree",
     "presents him with lush green banana plant... plantain tree takes root beside south-facing veranda",
     "Planting the broad-leafed green banana tree in damp earth outside the rustic cedarwood veranda of the hermitage",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", "ref_props_basho_leaves"),
    (3, 4, "Solitary Zazen Meditation",
     "sitting cross-legged in silent zazen meditation... mind unburdens from social obligations",
     "Master Bashō sitting in quiet Zen zazen meditation on woven tatami inside the serene, uncluttered Fukagawa hermitage",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", None),
    (3, 5, "Swaying Green Banana Leaves",
     "broad green leaves swaying gracefully over tidal marsh grasses... unforced seasonal cycles",
     "Serene panoramic view through open shoji screen: broad green banana leaves swaying gracefully over tidal marsh grasses",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", "ref_props_basho_leaves"),
    (3, 6, "Twilight on the Veranda",
     "sit beside Bashō on narrow wooden veranda as twilight gives way to velvety night... sipping hot well water",
     "Bashō seated quietly on cedar veranda in evening twilight, holding a simple ceramic tea bowl as dusk gathers over marshlands",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", None),
    (3, 7, "Rain on the Banana Leaves",
     "soft, rhythmic descent of raindrops as they gather on broad green veins of plantain tree",
     "Heavy evening raindrops splashing softly against broad, glossy green bashō banana leaves outside the open wooden window",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", "ref_props_basho_leaves"),
    (3, 8, "Inking Verse in the Storm",
     "brush moves with effortless grace across unrolled mulberry paper... old pond, frog jumps in",
     "Bashō writing haiku with slender bamboo brush on unrolled washi paper scroll by warm lantern glow while rain falls outside",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", "ref_props_inkstone_brush"),
    (3, 9, "Hearth Kettle & Rain Cadence",
     "tea kettle murmuring gently on sunken hearth... acoustic lullaby smoothing away tensions",
     "Interior wide shot of peaceful candlelit hermitage room, rustic tea kettle simmering on sunken hearth, rain falling outside",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", "ref_props_tea_hearth_irori"),
    (3, 10, "Fukagawa Slumber",
     "releasing lingering tensions into peaceful stillness... wrapped in safe shelter of marsh hut",
     "Bashō lying comfortably on sleeping futon beneath soft cotton quilt, eyes closed in serene peace as night envelops Fukagawa",
     "ref_character_basho_elder", "ref_setting_fukagawa_interior", None),
]
