"""
HistorySnooze Script Producer - Canonical Beats (Parts 07 to 09)
Module: canonical_beats_p07_p09.py
Rule <= 150 lines compliant.
"""

from typing import Any, List, Tuple

RAW_BEATS_P07_P09: List[Tuple[Any, ...]] = [
    # Part 07: The Sacred Cedars of Nikkō and the Whispering Cascades
    (7, 1, "Sacred Cedars of Nikkō",
     "morning mountain mist rising through towering ancient cryptomeria redwoods of Nikkō",
     "Giant ancient cedar trees of Nikkō rising into morning mist, stone lantern pathways winding through mossy roots",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),
    (7, 2, "Vermilion Toshogu Shrines",
     "golden pavilions of Tōshōgū shrine glowing in morning sun, vermilion gateways",
     "Ornate vermilion gate and lacquer shrine pavilion of Nikkō glowing in early sunlight filtering through forest canopy",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),
    (7, 3, "Sunbeams on Green Leaves",
     "Ah, how holy! / On green leaves and young leaves / the light of the sun!",
     "Bashō standing under sunlit emerald leaves, holding brush and paper slip, gazing up in awe at sunbeams piercing canopy",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", "ref_props_inkstone_brush"),
    (7, 4, "Urami Falls Gorge",
     "deep into rocky gorge behind shrine to Urami Falls... roaring mountain torrent",
     "Roaring mountain waterfall cascading over dark rocky precipice into crystalline emerald plunge pool, fine spray rising",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),
    (7, 5, "Cavern Behind the Waterfall",
     "stepping into damp hollow cavern behind falling curtain of water, viewing forest through spray",
     "Bashō standing inside rocky cave alcove behind waterfall, watching shimmering curtain of falling water",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),
    (7, 6, "Crystalline Stream Rapids",
     "mountain stream water tumbling over mossy emerald granite riverbed boulders",
     "Close view of swirling crystalline mountain stream water tumbling over mossy emerald granite riverbed boulders",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),
    (7, 7, "Mossy Jizō Statues",
     "ancient mossy stone Jizō statues draped in red cloth bibs, protecting travelers",
     "Row of small mossy stone Jizo guardian statues with weathered red bibs along trail as Bashō bows respectfully",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", "ref_props_travel_gear"),
    (7, 8, "Mountain Temple Supper",
     "steaming bowls of wild fiddlehead ferns, bamboo shoots, and hot miso broth",
     "Steaming bowls of hot mountain vegetable broth, wild fiddlehead ferns, and rice served on dark cedar trays",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),
    (7, 9, "Temple Veranda at Night",
     "mountain temple wooden veranda, single paper lantern glowing softly against blue forest",
     "Serene night shot of mountain temple wooden veranda, single paper lantern glowing softly against deep blue forest shadows",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),
    (7, 10, "Waterfall Lullaby Slumber",
     "sound of mountain water lulling spirit to sleep... sinking into comfortable sleeping mats",
     "Bashō resting peacefully in quiet temple chamber, eyes closed in deep tranquil relaxation as mountain winds whisper",
     "ref_character_basho_traveler", "ref_setting_nikko_cedars", None),

    # Part 08: The Cicada’s Cry at Yamadera (Ryūshakuji)
    (8, 1, "Yamadera Cliffs Approach",
     "approaching jagged granite cliffs of Yamadera, ancient mountain temple perched on sheer crags",
     "Distant dramatic view of Yamadera temple pavilions clinging precariously to towering vertical granite cliffs in summer",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),
    (8, 2, "Stone Steps Through Cedars",
     "ascent up thousand ancient moss-cushioned stone steps carved into rock under giant cedars",
     "Bashō and Sora climbing ancient moss-covered stone stairway winding between giant cryptomeria roots up rocky cliff",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", "ref_props_travel_gear"),
    (8, 3, "High Granite Precipice",
     "reaching upper ridge, overwhelming silence... weathered granite boulder framed by ancient pines",
     "Weathered granite boulder perched on mountain precipice, gnarled ancient pine branches framing sweeping valley below",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),
    (8, 4, "Composing the Cicada Haiku",
     "Stillness— / sinking into the rocks, / the cicada's cry. Brushing lines onto washi scroll",
     "Bashō seated on flat mountain rock ledge, inkstone and brush unrolled, composing famous cicada verse on paper",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", "ref_props_inkstone_brush"),
    (8, 5, "Golden Sunset Over Peaks",
     "sitting upon high stone ledge as sunset paints distant western peaks in apricot and lavender",
     "Panoramic golden sunset from Yamadera rock platform, sea of peaks glowing lavender, solitary traveler gazing out",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),
    (8, 6, "Resonant Bronze Temple Bell",
     "solitary bronze temple bell rings from nearby ridge, low resonant gong rolling through ravines",
     "Massive ancient bronze temple bell hanging in open timber belfry perched on cliff edge, swinging beam beside it",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),
    (8, 7, "Cliffside Guest Quarters",
     "temple guest quarters nestled against cliff, paper shoji glowing with soft candlelight",
     "Mountain temple guest lodge clinging to cliffside at twilight, warm candlelit shoji windows glowing against purple night",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),
    (8, 8, "Veranda View of Sleeping Valley",
     "polished wooden veranda looking down on sleeping valley, twinkling village lanterns below",
     "Bashō leaning gently against veranda cedar post, looking out over silent darkened valley with distant farm lantern glows",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),
    (8, 9, "Celadon Incense Smoldering",
     "simple incense burner made of celadon ceramic emitting delicate coil of fragrant blue smoke",
     "Simple incense burner made of celadon ceramic emitting a delicate coil of fragrant blue smoke inside quiet tatami room",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),
    (8, 10, "Cliff Cell Deep Slumber",
     "cool granite cliffs radiating ancient calmness... resting peacefully on futon in cliffside cell",
     "Bashō resting peacefully on futon in cliffside cell, moonlight tracing soft outlines on cedar walls, serene restful sleep",
     "ref_character_basho_traveler", "ref_setting_yamadera_temple", None),

    # Part 09: Gathering the May Rains: The Descent of the Mogami River
    (9, 1, "Rain Swollen Mogami River",
     "heavy summer rain pouring steadily from pearl-grey sky, drumming on swollen brown waters",
     "Swollen rushing waters of Mogami River under heavy summer rain, grey clouds hanging low over forested river bluffs",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
    (9, 2, "Boarding the Wooden Skiff",
     "boarding long wooden river skiff alongside Bashō and Sora, boatmen in straw mino raincoats",
     "Bashō and Sora stepping into slender cedarwood river boat, boatmen in straw mino raincapes holding long steering oars",
     "ref_character_basho_traveler", "ref_setting_mogami_river", "ref_props_travel_gear"),
    (9, 3, "Shiraito Falls in Gorge Mist",
     "Shiraito Falls tumbling down green canyon walls like white silk ribbons through mist",
     "Dramatic canyon gorge of Mogami River, slender white Shiraito waterfall plunging through mist into swirling torrent",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
    (9, 4, "Shooting the Roaring Rapids",
     "skiff shoots through narrow gorge with breathtaking speed, boatmen steering through eddies",
     "Wooden skiff riding swirling rapids between towering canyon cliffs, spray flying as boatmen lean into their oars",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
    (9, 5, "Gathering Summer Rains Verse",
     "Gathering the summer rains / swift flowing / is the Mogami River. Inking journal under boat canopy",
     "Bashō seated inside covered shelter of boat, sheltering his travel journal and brush from spray, eyes alight with poetry",
     "ref_character_basho_traveler", "ref_setting_mogami_river", "ref_props_inkstone_brush"),
    (9, 6, "Calming Waters of Shōnai",
     "rapids subside into wide, slow-moving sheet of water near coastal plain of Shōnai",
     "Wide, calm expanse of Mogami River flowing into flat green plains of Shonai under soft silver evening drizzle",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
    (9, 7, "Sakata River Port at Dusk",
     "skiff glides into port town of Sakata where river meets sea... storehouses and fishing junks",
     "Sakata river harbor at dusk: wooden merchant storehouses, moored fishing vessels, warm lanterns glowing on quayside",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
    (9, 8, "Merchant Chamber Hospitality",
     "sitting by open shoji screen of merchant's guest chamber, watching lanterns along river",
     "Bashō and host seated by open second-floor window in Sakata merchant house, warm lanterns reflecting in river harbor below",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
    (9, 9, "Steaming Bath Basin & Yukata",
     "cedar bath basin steaming in corner, clean yukata robes laid out on tatami mats, peaceful rest",
     "Intimate room setting with cedar bath basin steaming in corner, clean yukata robes laid out on tatami mats, peaceful rest",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
    (9, 10, "Slumber After the Rapids",
     "slow breathing matching tidal surge... safe from storm, drifting into untroubled slumber",
     "Bashō asleep on soft cotton futon, ocean breeze fluttering paper screen, moon shining silver on quiet river port",
     "ref_character_basho_traveler", "ref_setting_mogami_river", None),
]
